/**
 * Copyright 2024-2026 SEN Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
/**
 * ABAP Language Simplification Rules
 *
 * Covers: OCCURS, RANGES, HEADER LINE, FIELD-SYMBOLS typing,
 * obsolete statements, SELECT...ENDSELECT, nested SELECTs, client-specified access,
 * ABAP language changes, database access, ALV/UI, enhancement framework,
 * workflow, batch processing, RFC/communication, security, testing, performance.
 */

module.exports = [
  // ── Existing rules (001–015) ──────────────────────────────────────────

  {
    id: 'SIMPL-ABAP-001',
    category: 'ABAP Language',
    severity: 'low',
    title: 'OCCURS keyword deprecated',
    description: 'OCCURS is obsolete in ABAP. While still functional, it indicates legacy code.',
    pattern: /\bOCCURS\s+\d+/i,
    patternType: 'source',
    remediation: 'Replace with standard internal table declarations (TYPE TABLE OF).',
    simplificationId: 'S4TWL-ABAP-001',
  },
  {
    id: 'SIMPL-ABAP-002',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'BDC (Batch Data Communication) usage',
    description: 'BDC/CALL TRANSACTION relies on screen sequences that may change in Fiori.',
    pattern: /\bCALL\s+TRANSACTION\s+/i,
    patternType: 'source',
    remediation: 'Replace with BAPI calls, OData services, or direct API access.',
    simplificationId: 'S4TWL-ABAP-002',
  },
  {
    id: 'SIMPL-ABAP-003',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'Direct database modification statements',
    description: 'Direct INSERT/UPDATE/DELETE on standard SAP tables bypasses application logic.',
    pattern: /\b(INSERT INTO|UPDATE\s+|DELETE FROM)\s+(BKPF|BSEG|EKKO|EKPO|VBAK|VBAP|LIKP|LIPS|MKPF|MSEG)\b/i,
    patternType: 'source',
    remediation: 'Use BAPIs or APIs instead of direct DB modifications on standard tables.',
    simplificationId: 'S4TWL-ABAP-003',
  },
  {
    id: 'SIMPL-ABAP-004',
    category: 'ABAP Language',
    severity: 'low',
    title: 'SELECT * usage on large tables',
    description: 'SELECT * reads all columns including deprecated ones. Issues with restructured tables.',
    pattern: /\bSELECT\s+\*\s+FROM\s+(BKPF|EKKO|EKPO|VBAK|VBAP|MARA|MARC|MARD)\b/i,
    patternType: 'source',
    remediation: 'Specify explicit column list instead of SELECT *.',
    simplificationId: 'S4TWL-ABAP-004',
  },
  {
    id: 'SIMPL-ABAP-005',
    category: 'ABAP Language',
    severity: 'low',
    title: 'HEADER LINE usage',
    description: 'Internal tables WITH HEADER LINE are obsolete.',
    pattern: /\bWITH\s+HEADER\s+LINE\b/i,
    patternType: 'source',
    remediation: 'Remove HEADER LINE. Use separate work area variable.',
    simplificationId: 'S4TWL-ABAP-005',
  },
  {
    id: 'SIMPL-ABAP-006',
    category: 'ABAP Language',
    severity: 'low',
    title: 'RANGES declaration deprecated',
    description: 'RANGES statement is obsolete. Use TYPE RANGE OF instead.',
    pattern: /\bRANGES\s+\w+\s+FOR\b/i,
    patternType: 'source',
    remediation: 'Replace RANGES with TYPE RANGE OF declaration.',
    simplificationId: 'S4TWL-ABAP-006',
  },
  {
    id: 'SIMPL-ABAP-007',
    category: 'ABAP Language',
    severity: 'low',
    title: 'FIELD-SYMBOLS without typing',
    description: 'FIELD-SYMBOLS without explicit typing are considered legacy.',
    pattern: /\bFIELD-SYMBOLS\s*<\w+>\s*\./i,
    patternType: 'source',
    remediation: 'Add TYPE clause to FIELD-SYMBOLS declarations.',
    simplificationId: 'S4TWL-ABAP-007',
  },
  {
    id: 'SIMPL-ABAP-008',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'SELECT...ENDSELECT loop pattern',
    description: 'SELECT...ENDSELECT reads rows one by one. Performance anti-pattern.',
    pattern: /\bSELECT\b.*\bFROM\b[\s\S]*?\bENDSELECT\b/i,
    patternType: 'source',
    remediation: 'Replace with SELECT INTO TABLE for bulk read.',
    simplificationId: 'S4TWL-ABAP-008',
  },
  {
    id: 'SIMPL-ABAP-009',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'Nested SELECT statements',
    description: 'Nested SELECTs cause N+1 query problems. Use JOINs or FOR ALL ENTRIES.',
    pattern: /SELECT\s+.*FROM\s+\w+[\s\S]*?SELECT\s+.*FROM\s+\w+/i,
    patternType: 'source',
    remediation: 'Use JOIN, subquery, or FOR ALL ENTRIES IN to avoid nested SELECTs.',
    simplificationId: 'S4TWL-ABAP-009',
  },
  {
    id: 'SIMPL-ABAP-010',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'Client-specified database access',
    description: 'CLIENT SPECIFIED bypasses automatic client handling. Risky in S/4HANA.',
    pattern: /\bCLIENT\s+SPECIFIED\b/i,
    patternType: 'source',
    remediation: 'Remove CLIENT SPECIFIED. Use proper client handling.',
    simplificationId: 'S4TWL-ABAP-010',
  },
  {
    id: 'SIMPL-ABAP-011',
    category: 'ABAP Language',
    severity: 'low',
    title: 'Obsolete MOVE-CORRESPONDING',
    description: 'MOVE-CORRESPONDING is allowed but CORRESPONDING #() is preferred in modern ABAP.',
    pattern: /\bMOVE-CORRESPONDING\b/i,
    patternType: 'source',
    remediation: 'Consider using CORRESPONDING #() constructor expression.',
    simplificationId: 'S4TWL-ABAP-011',
  },
  {
    id: 'SIMPL-ABAP-012',
    category: 'ABAP Language',
    severity: 'low',
    title: 'COMPUTE statement obsolete',
    description: 'COMPUTE statement is obsolete syntax.',
    pattern: /\bCOMPUTE\s+\w+\s*=/i,
    patternType: 'source',
    remediation: 'Remove COMPUTE keyword, use direct assignment.',
    simplificationId: 'S4TWL-ABAP-012',
  },
  {
    id: 'SIMPL-ABAP-013',
    category: 'ABAP Language',
    severity: 'low',
    title: 'FORM/PERFORM obsolete',
    description: 'FORM/PERFORM subroutines are obsolete. Use methods instead.',
    pattern: /\bPERFORM\s+\w+\b/i,
    patternType: 'source',
    remediation: 'Refactor FORMs into class methods.',
    simplificationId: 'S4TWL-ABAP-013',
  },
  {
    id: 'SIMPL-ABAP-014',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'READ TABLE with SY-TABIX',
    description: 'READ TABLE with SY-TABIX is legacy. Use table expressions or ASSIGN.',
    pattern: /\bREAD\s+TABLE\b.*\bSY-TABIX\b/i,
    patternType: 'source',
    remediation: 'Use table expressions (itab[ key ]) or ASSIGN for modern access.',
    simplificationId: 'S4TWL-ABAP-014',
  },
  {
    id: 'SIMPL-ABAP-015',
    category: 'ABAP Language',
    severity: 'low',
    title: 'TABLES declaration obsolete',
    description: 'TABLES statement for global work areas is obsolete.',
    pattern: /^\s*TABLES:\s+\w+/im,
    patternType: 'source',
    remediation: 'Replace TABLES with typed DATA declarations.',
    simplificationId: 'S4TWL-ABAP-015',
  },

  // ── ABAP Language Changes (016–025) ───────────────────────────────────

  {
    id: 'SIMPL-ABAP-016',
    category: 'ABAP Language',
    severity: 'low',
    title: 'DESCRIBE TABLE LINES obsolete',
    description: 'DESCRIBE TABLE ... LINES is obsolete. Use lines() built-in function instead.',
    pattern: /\bDESCRIBE\s+TABLE\s+\w+\s+LINES\b/i,
    patternType: 'source',
    remediation: 'Replace DESCRIBE TABLE ... LINES with lines( itab ) expression.',
    simplificationId: 'S4TWL-ABAP-016',
  },
  {
    id: 'SIMPL-ABAP-017',
    category: 'ABAP Language',
    severity: 'low',
    title: 'TRANSLATE TO UPPER/LOWER obsolete',
    description: 'TRANSLATE ... TO UPPER CASE is obsolete. Use to_upper()/to_lower() functions.',
    pattern: /\bTRANSLATE\s+\w+\s+TO\s+(UPPER|LOWER)\s+CASE\b/i,
    patternType: 'source',
    remediation: 'Replace with to_upper( ) or to_lower( ) built-in string functions.',
    simplificationId: 'S4TWL-ABAP-017',
  },
  {
    id: 'SIMPL-ABAP-018',
    category: 'ABAP Language',
    severity: 'low',
    title: 'CONDENSE NO-GAPS obsolete pattern',
    description: 'CONDENSE with NO-GAPS is obsolete. Use condense() string function in modern ABAP.',
    pattern: /\bCONDENSE\s+\w+\s+NO-GAPS\b/i,
    patternType: 'source',
    remediation: 'Replace with condense( val = str del = ` ` ) string expression.',
    simplificationId: 'S4TWL-ABAP-018',
  },
  {
    id: 'SIMPL-ABAP-019',
    category: 'ABAP Language',
    severity: 'low',
    title: 'CONCATENATE statement obsolete',
    description: 'CONCATENATE is obsolete. Use string templates or concat_lines_of() instead.',
    pattern: /\bCONCATENATE\s+\w+/i,
    patternType: 'source',
    remediation: 'Replace CONCATENATE with string templates |{ var1 }{ var2 }| or && operator.',
    simplificationId: 'S4TWL-ABAP-019',
  },
  {
    id: 'SIMPL-ABAP-020',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'CREATE OBJECT obsolete syntax',
    description: 'CREATE OBJECT is obsolete. Use NEW operator for object instantiation.',
    pattern: /\bCREATE\s+OBJECT\s+\w+/i,
    patternType: 'source',
    remediation: 'Replace CREATE OBJECT ref with ref = NEW class( ... ).',
    simplificationId: 'S4TWL-ABAP-020',
  },
  {
    id: 'SIMPL-ABAP-021',
    category: 'ABAP Language',
    severity: 'low',
    title: 'CALL METHOD obsolete syntax',
    description: 'CALL METHOD is obsolete. Use direct functional method call syntax.',
    pattern: /\bCALL\s+METHOD\s+\w+/i,
    patternType: 'source',
    remediation: 'Replace CALL METHOD obj->method with obj->method( ) functional call.',
    simplificationId: 'S4TWL-ABAP-021',
  },
  {
    id: 'SIMPL-ABAP-022',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'ABAP CDS views should replace SE11 views',
    description: 'SE11 dictionary views are legacy. CDS views are the standard in S/4HANA.',
    pattern: /\bSELECT\s+.*\bFROM\s+(V_\w+|ZV_\w+|YV_\w+)\b/i,
    patternType: 'source',
    remediation: 'Replace SE11 dictionary views with ABAP CDS views for better HANA optimization.',
    simplificationId: 'S4TWL-ABAP-022',
  },
  {
    id: 'SIMPL-ABAP-023',
    category: 'ABAP Language',
    severity: 'low',
    title: 'WRITE statement in non-list programs',
    description: 'WRITE statement for ALV output is legacy. Use CL_SALV_TABLE or Fiori apps.',
    pattern: /\bWRITE\s*[:/]\s+/i,
    patternType: 'source',
    remediation: 'Replace WRITE-based lists with CL_SALV_TABLE, ALV Grid, or Fiori UI.',
    simplificationId: 'S4TWL-ABAP-023',
  },
  {
    id: 'SIMPL-ABAP-024',
    category: 'ABAP Language',
    severity: 'low',
    title: 'REFRESH statement obsolete',
    description: 'REFRESH statement is obsolete. Use CLEAR for internal tables.',
    pattern: /\bREFRESH\s+\w+/i,
    patternType: 'source',
    remediation: 'Replace REFRESH itab with CLEAR itab.',
    simplificationId: 'S4TWL-ABAP-024',
  },
  {
    id: 'SIMPL-ABAP-025',
    category: 'ABAP Language',
    severity: 'low',
    title: 'FREE statement for table cleanup',
    description: 'FREE releases memory immediately. Consider whether CLEAR is sufficient.',
    pattern: /\bFREE\s+\w+/i,
    patternType: 'source',
    remediation: 'Use CLEAR unless explicit memory release is needed; review usage context.',
    simplificationId: 'S4TWL-ABAP-025',
  },

  // ── Database Access (026–033) ─────────────────────────────────────────

  {
    id: 'SIMPL-ABAP-026',
    category: 'Database Access',
    severity: 'high',
    title: 'Native SQL via EXEC SQL',
    description: 'EXEC SQL bypasses Open SQL and HANA optimization. Restricted in S/4HANA.',
    pattern: /\bEXEC\s+SQL\b/i,
    patternType: 'source',
    remediation: 'Replace EXEC SQL with Open SQL, ABAP CDS views, or ADBC (CL_SQL_STATEMENT).',
    simplificationId: 'S4TWL-ABAP-026',
  },
  {
    id: 'SIMPL-ABAP-027',
    category: 'Database Access',
    severity: 'medium',
    title: 'FOR ALL ENTRIES without prior empty check',
    description: 'FOR ALL ENTRIES IN without checking if the driver table is empty returns all rows.',
    pattern: /\bFOR\s+ALL\s+ENTRIES\s+IN\b/i,
    patternType: 'source',
    remediation: 'Always check IF itab IS NOT INITIAL before FOR ALL ENTRIES IN itab.',
    simplificationId: 'S4TWL-ABAP-027',
  },
  {
    id: 'SIMPL-ABAP-028',
    category: 'Database Access',
    severity: 'medium',
    title: 'Table buffering bypass with BYPASSING BUFFER',
    description: 'BYPASSING BUFFER forces database read and can cause performance issues on HANA.',
    pattern: /\bBYPASSING\s+BUFFER\b/i,
    patternType: 'source',
    remediation: 'Remove BYPASSING BUFFER unless absolutely required. HANA handles buffering differently.',
    simplificationId: 'S4TWL-ABAP-028',
  },
  {
    id: 'SIMPL-ABAP-029',
    category: 'Database Access',
    severity: 'medium',
    title: 'ORDER BY PRIMARY KEY performance',
    description: 'ORDER BY PRIMARY KEY may be inefficient on HANA. Explicit ORDER BY is preferred.',
    pattern: /\bORDER\s+BY\s+PRIMARY\s+KEY\b/i,
    patternType: 'source',
    remediation: 'Replace ORDER BY PRIMARY KEY with explicit field list for HANA optimization.',
    simplificationId: 'S4TWL-ABAP-029',
  },
  {
    id: 'SIMPL-ABAP-030',
    category: 'Database Access',
    severity: 'high',
    title: 'Cluster/pool table access (obsolete table types)',
    description: 'Cluster and pool tables are converted to transparent tables in S/4HANA. Direct access patterns may change.',
    pattern: /\bSELECT\s+.*\bFROM\s+(BSEG|KONV|CDPOS|RFBLG|BSET|CDCLS)\b/i,
    patternType: 'source',
    remediation: 'Review access to former cluster/pool tables. Indexes and access patterns may differ.',
    simplificationId: 'S4TWL-ABAP-030',
  },
  {
    id: 'SIMPL-ABAP-031',
    category: 'Database Access',
    severity: 'medium',
    title: 'ABAP Database Connectivity (ADBC) recommended',
    description: 'CL_SQL_CONNECTION and CL_SQL_STATEMENT provide modern native SQL access via ADBC.',
    pattern: /\bCL_SQL_CONNECTION\b/i,
    patternType: 'source',
    remediation: 'Ensure ADBC usage follows S/4HANA best practices. Prefer CDS views when possible.',
    simplificationId: 'S4TWL-ABAP-031',
  },
  {
    id: 'SIMPL-ABAP-032',
    category: 'Database Access',
    severity: 'medium',
    title: 'UP TO n ROWS missing on large tables',
    description: 'SELECT without UP TO n ROWS on large tables may cause memory and performance issues on HANA.',
    pattern: /\bSELECT\s+.*\bFROM\s+(ACDOCA|MATDOC|BKPF|MSEG|VBFA)\b(?![\s\S]*?\bUP\s+TO\b)/i,
    patternType: 'source',
    remediation: 'Add UP TO n ROWS or WHERE clauses to limit data on large S/4HANA tables.',
    simplificationId: 'S4TWL-ABAP-032',
  },
  {
    id: 'SIMPL-ABAP-033',
    category: 'Database Access',
    severity: 'low',
    title: 'INTO CORRESPONDING FIELDS performance',
    description: 'INTO CORRESPONDING FIELDS OF TABLE may have overhead. Explicit field mapping preferred.',
    pattern: /\bINTO\s+CORRESPONDING\s+FIELDS\s+OF\s+TABLE\b/i,
    patternType: 'source',
    remediation: 'Consider explicit field mapping or matching structure for better performance.',
    simplificationId: 'S4TWL-ABAP-033',
  },

  // ── ALV/UI Changes (034–039) ──────────────────────────────────────────

  {
    id: 'SIMPL-ABAP-034',
    category: 'ALV/UI',
    severity: 'medium',
    title: 'Classic ALV function modules deprecated',
    description: 'REUSE_ALV_GRID_DISPLAY and REUSE_ALV_LIST_DISPLAY are legacy. Use CL_SALV_TABLE.',
    pattern: /\bREUSE_ALV_(GRID|LIST)_DISPLAY\b/i,
    patternType: 'source',
    remediation: 'Migrate to CL_SALV_TABLE or CL_GUI_ALV_GRID for ALV output.',
    simplificationId: 'S4TWL-ABAP-034',
  },
  {
    id: 'SIMPL-ABAP-035',
    category: 'ALV/UI',
    severity: 'medium',
    title: 'CL_GUI_ALV_GRID direct usage',
    description: 'CL_GUI_ALV_GRID requires SAP GUI. Consider CL_SALV_TABLE for Fiori compatibility.',
    pattern: /\bCL_GUI_ALV_GRID\b/i,
    patternType: 'source',
    remediation: 'Evaluate migration to CL_SALV_TABLE with IDA or Fiori Elements list report.',
    simplificationId: 'S4TWL-ABAP-035',
  },
  {
    id: 'SIMPL-ABAP-036',
    category: 'ALV/UI',
    severity: 'high',
    title: 'SAP GUI dynpro screens (CALL SCREEN)',
    description: 'CALL SCREEN dynpro-based UIs are legacy. Fiori/UI5 is the standard in S/4HANA.',
    pattern: /\bCALL\s+SCREEN\s+\d+/i,
    patternType: 'source',
    remediation: 'Plan migration to SAP Fiori / SAPUI5 apps. Use Fiori Elements where possible.',
    simplificationId: 'S4TWL-ABAP-036',
  },
  {
    id: 'SIMPL-ABAP-037',
    category: 'ALV/UI',
    severity: 'medium',
    title: 'SELECTION-SCREEN legacy pattern',
    description: 'SELECTION-SCREEN with complex layouts may not render well in Fiori.',
    pattern: /\bSELECTION-SCREEN\s+BEGIN\s+OF\s+BLOCK\b/i,
    patternType: 'source',
    remediation: 'Simplify selection screens. Consider Fiori app with filter bar for user selection.',
    simplificationId: 'S4TWL-ABAP-037',
  },
  {
    id: 'SIMPL-ABAP-038',
    category: 'ALV/UI',
    severity: 'high',
    title: 'Web Dynpro ABAP to be replaced',
    description: 'Web Dynpro ABAP applications should be replaced by Fiori/UI5 in S/4HANA.',
    pattern: /\bCL_WD_\w+|IF_WD_\w+/i,
    patternType: 'source',
    remediation: 'Migrate Web Dynpro ABAP apps to SAPUI5/Fiori. Use Fiori Elements for standard patterns.',
    simplificationId: 'S4TWL-ABAP-038',
  },
  {
    id: 'SIMPL-ABAP-039',
    category: 'ALV/UI',
    severity: 'medium',
    title: 'ALV IDA for large datasets',
    description: 'CL_SALV_GUI_TABLE_IDA provides ALV with Integrated Data Access for HANA-optimized display.',
    pattern: /\bCL_SALV_GUI_TABLE_IDA\b/i,
    patternType: 'source',
    remediation: 'ALV IDA is the recommended approach for large datasets. Ensure CDS view is used as data source.',
    simplificationId: 'S4TWL-ABAP-039',
  },

  // ── Enhancement Framework (040–045) ───────────────────────────────────

  {
    id: 'SIMPL-ABAP-040',
    category: 'Enhancement Framework',
    severity: 'high',
    title: 'Customer exits (CMOD/SMOD) deprecated',
    description: 'Classic customer exits (CMOD/SMOD) are deprecated. BAdIs are the standard.',
    pattern: /\bCALL\s+CUSTOMER-FUNCTION\s+'\d+'/i,
    patternType: 'source',
    remediation: 'Migrate customer exits to new BAdI implementations (Enhancement Spot/BAdI).',
    simplificationId: 'S4TWL-ABAP-040',
  },
  {
    id: 'SIMPL-ABAP-041',
    category: 'Enhancement Framework',
    severity: 'medium',
    title: 'Classic BAdI (BADI_) usage',
    description: 'Classic BAdI definitions (GET BADI/CALL BADI) replaced by new Enhancement Framework BAdIs.',
    pattern: /\b(GET\s+BADI|CALL\s+BADI)\b/i,
    patternType: 'source',
    remediation: 'Verify BAdI still exists in S/4HANA. Migrate to new BAdI framework if needed.',
    simplificationId: 'S4TWL-ABAP-041',
  },
  {
    id: 'SIMPL-ABAP-042',
    category: 'Enhancement Framework',
    severity: 'medium',
    title: 'User exit USEREXIT_ pattern',
    description: 'User exits (USEREXIT_*) in includes are legacy. Many replaced by BAdIs in S/4HANA.',
    pattern: /\bUSEREXIT_\w+/i,
    patternType: 'source',
    remediation: 'Check if the user exit is still active. Migrate logic to corresponding BAdI.',
    simplificationId: 'S4TWL-ABAP-042',
  },
  {
    id: 'SIMPL-ABAP-043',
    category: 'Enhancement Framework',
    severity: 'medium',
    title: 'Business Transaction Events (BTE)',
    description: 'BTEs (FIBF) used in FI may have changes due to new accounting structure in S/4HANA.',
    pattern: /\bFIBF\b|OPEN_FI_PERFORM_\w+/i,
    patternType: 'source',
    remediation: 'Review BTEs for compatibility with new general ledger and ACDOCA architecture.',
    simplificationId: 'S4TWL-ABAP-043',
  },
  {
    id: 'SIMPL-ABAP-044',
    category: 'Enhancement Framework',
    severity: 'medium',
    title: 'Enhancement implementation via ENHANCEMENT-POINT',
    description: 'Implicit and explicit enhancement points may be affected by code changes in S/4HANA.',
    pattern: /\bENHANCEMENT-POINT\b|ENHANCEMENT\s+\d+/i,
    patternType: 'source',
    remediation: 'Verify enhancement points still exist in target S/4HANA release. Test thoroughly.',
    simplificationId: 'S4TWL-ABAP-044',
  },
  {
    id: 'SIMPL-ABAP-045',
    category: 'Enhancement Framework',
    severity: 'low',
    title: 'Modification assistant (SMOD adjustments)',
    description: 'Direct SAP code modifications via modification assistant require adjustment after upgrade.',
    pattern: /\bMODIFICATION\s+ADJUSTMENT\b|SPAU\b|SPDD\b/i,
    patternType: 'source',
    remediation: 'Reduce modifications. Convert to BAdI or Enhancement implementations where possible.',
    simplificationId: 'S4TWL-ABAP-045',
  },

  // ── Workflow (046–049) ────────────────────────────────────────────────

  {
    id: 'SIMPL-ABAP-046',
    category: 'Workflow',
    severity: 'medium',
    title: 'SAP Business Workflow (SWDD/SWO1)',
    description: 'Classic workflow definitions may need adjustment for S/4HANA business objects.',
    pattern: /\b(SWO1|SWDD|SWW_WI)\b|SWE_EVENT_CREATE/i,
    patternType: 'source',
    remediation: 'Review workflow definitions. Ensure business object events still trigger correctly.',
    simplificationId: 'S4TWL-ABAP-046',
  },
  {
    id: 'SIMPL-ABAP-047',
    category: 'Workflow',
    severity: 'medium',
    title: 'Flexible Workflow for S/4HANA',
    description: 'S/4HANA introduces Flexible Workflow scenarios for standard approval processes.',
    pattern: /\bSWFLEX_|FLEXIBLE_WORKFLOW\b/i,
    patternType: 'source',
    remediation: 'Evaluate SAP Flexible Workflow for standard approval scenarios (PO, PR, etc.).',
    simplificationId: 'S4TWL-ABAP-047',
  },
  {
    id: 'SIMPL-ABAP-048',
    category: 'Workflow',
    severity: 'medium',
    title: 'Workflow business object type changes',
    description: 'Workflow business object types (BUS2012, BUS2032, etc.) may have changed in S/4HANA.',
    pattern: /\bBUS20[0-9]{2}\b/i,
    patternType: 'source',
    remediation: 'Verify business object types and their methods/events in S/4HANA SWO1.',
    simplificationId: 'S4TWL-ABAP-048',
  },
  {
    id: 'SIMPL-ABAP-049',
    category: 'Workflow',
    severity: 'low',
    title: 'Workflow inbox integration with Fiori',
    description: 'My Inbox (Fiori) replaces SBWP for workflow task processing in S/4HANA.',
    pattern: /\bSBWP\b|SAP_WAPI_\w+/i,
    patternType: 'source',
    remediation: 'Ensure custom workflow tasks are visible in Fiori My Inbox app.',
    simplificationId: 'S4TWL-ABAP-049',
  },

  // ── Batch Processing (050–053) ────────────────────────────────────────

  {
    id: 'SIMPL-ABAP-050',
    category: 'Batch Processing',
    severity: 'medium',
    title: 'Classic batch job scheduling (SM36)',
    description: 'Classic batch job framework (SM36/SM37) works but Application Jobs are preferred.',
    pattern: /\bJOB_OPEN\b|JOB_CLOSE\b|JOB_SUBMIT\b/i,
    patternType: 'source',
    remediation: 'Evaluate migration to S/4HANA Application Jobs framework for new developments.',
    simplificationId: 'S4TWL-ABAP-050',
  },
  {
    id: 'SIMPL-ABAP-051',
    category: 'Batch Processing',
    severity: 'medium',
    title: 'Application Jobs framework (CL_APJ_)',
    description: 'CL_APJ_RT_API is the S/4HANA Application Jobs runtime API for modern scheduling.',
    pattern: /\bCL_APJ_\w+/i,
    patternType: 'source',
    remediation: 'Use Application Jobs framework for new batch processes. Register job catalog entry.',
    simplificationId: 'S4TWL-ABAP-051',
  },
  {
    id: 'SIMPL-ABAP-052',
    category: 'Batch Processing',
    severity: 'medium',
    title: 'Background RFC (bgRFC) replaces tRFC/qRFC',
    description: 'Transactional RFC (tRFC) and queued RFC (qRFC) replaced by bgRFC in S/4HANA.',
    pattern: /\bCALL\s+FUNCTION\s+.*IN\s+BACKGROUND\s+TASK\b/i,
    patternType: 'source',
    remediation: 'Migrate from tRFC/qRFC to bgRFC for asynchronous processing.',
    simplificationId: 'S4TWL-ABAP-052',
  },
  {
    id: 'SIMPL-ABAP-053',
    category: 'Batch Processing',
    severity: 'low',
    title: 'SUBMIT report via job',
    description: 'SUBMIT ... VIA JOB pattern requires review for Application Jobs compatibility.',
    pattern: /\bSUBMIT\s+\w+\s+.*VIA\s+JOB\b/i,
    patternType: 'source',
    remediation: 'Review SUBMIT VIA JOB usage. Consider Application Jobs for Fiori-integrated scheduling.',
    simplificationId: 'S4TWL-ABAP-053',
  },

  // ── RFC/Communication (054–059) ───────────────────────────────────────

  {
    id: 'SIMPL-ABAP-054',
    category: 'RFC/Communication',
    severity: 'medium',
    title: 'Synchronous RFC (sRFC) destination usage',
    description: 'RFC destinations and CALL FUNCTION ... DESTINATION should be reviewed for S/4HANA.',
    pattern: /\bCALL\s+FUNCTION\s+.*\bDESTINATION\b/i,
    patternType: 'source',
    remediation: 'Review RFC destinations. Consider web services, OData, or ABAP channels instead.',
    simplificationId: 'S4TWL-ABAP-054',
  },
  {
    id: 'SIMPL-ABAP-055',
    category: 'RFC/Communication',
    severity: 'medium',
    title: 'HTTP client legacy class',
    description: 'CL_HTTP_CLIENT is legacy. CL_WEB_HTTP_CLIENT_MANAGER is the modern replacement.',
    pattern: /\bCL_HTTP_CLIENT\b/i,
    patternType: 'source',
    remediation: 'Use CL_WEB_HTTP_CLIENT_MANAGER for HTTP communication in ABAP Cloud.',
    simplificationId: 'S4TWL-ABAP-055',
  },
  {
    id: 'SIMPL-ABAP-056',
    category: 'RFC/Communication',
    severity: 'medium',
    title: 'ABAP Messaging Channels (AMC)',
    description: 'ABAP Messaging Channels enable push-based communication in S/4HANA.',
    pattern: /\bAMC_\w+|CL_AMC_\w+/i,
    patternType: 'source',
    remediation: 'Use ABAP Messaging Channels for real-time push notifications in S/4HANA.',
    simplificationId: 'S4TWL-ABAP-056',
  },
  {
    id: 'SIMPL-ABAP-057',
    category: 'RFC/Communication',
    severity: 'medium',
    title: 'ABAP Push Channels (APC)',
    description: 'ABAP Push Channels support WebSocket communication for Fiori apps.',
    pattern: /\bAPC_\w+|CL_APC_\w+/i,
    patternType: 'source',
    remediation: 'Ensure ABAP Push Channel configuration is compatible with S/4HANA landscape.',
    simplificationId: 'S4TWL-ABAP-057',
  },
  {
    id: 'SIMPL-ABAP-058',
    category: 'RFC/Communication',
    severity: 'low',
    title: 'SOTR (short text repository) for OTR texts',
    description: 'Online Text Repository (SOTR) usage should be reviewed for Fiori text handling.',
    pattern: /\bSOTR_\w+/i,
    patternType: 'source',
    remediation: 'Review SOTR text handling for Fiori app internationalization requirements.',
    simplificationId: 'S4TWL-ABAP-058',
  },
  {
    id: 'SIMPL-ABAP-059',
    category: 'RFC/Communication',
    severity: 'high',
    title: 'ABAP Cloud (Steampunk) restricted API usage',
    description: 'ABAP Cloud development model restricts APIs to released objects only.',
    pattern: /\bIF_RAP_\w+|CL_RAP_\w+/i,
    patternType: 'source',
    remediation: 'Ensure only released APIs are used. Check ABAP Cloud API compatibility via ADT.',
    simplificationId: 'S4TWL-ABAP-059',
  },

  // ── Security (060–064) ────────────────────────────────────────────────

  {
    id: 'SIMPL-ABAP-060',
    category: 'Security',
    severity: 'high',
    title: 'AUTHORITY-CHECK usage review',
    description: 'AUTHORITY-CHECK statements must be reviewed for new authorization objects in S/4HANA.',
    pattern: /\bAUTHORITY-CHECK\s+OBJECT\b/i,
    patternType: 'source',
    remediation: 'Review authorization objects. New S/4HANA apps may require new auth objects.',
    simplificationId: 'S4TWL-ABAP-060',
  },
  {
    id: 'SIMPL-ABAP-061',
    category: 'Security',
    severity: 'high',
    title: 'SUIM role analysis required',
    description: 'SUIM (User Information System) role analysis needed for S/4HANA migration.',
    pattern: /\bSUIM\b|AGR_1251|AGR_DEFINE/i,
    patternType: 'source',
    remediation: 'Run SUIM analysis. Map existing roles to S/4HANA Fiori catalog/group requirements.',
    simplificationId: 'S4TWL-ABAP-061',
  },
  {
    id: 'SIMPL-ABAP-062',
    category: 'Security',
    severity: 'medium',
    title: 'Privileged access with SAP_ALL check',
    description: 'SAP_ALL profile assignments must be reviewed. S/4HANA has stricter access controls.',
    pattern: /\bSAP_ALL\b|SAP_NEW\b/i,
    patternType: 'source',
    remediation: 'Replace SAP_ALL with specific role assignments. Use SAP_NEW only during upgrade.',
    simplificationId: 'S4TWL-ABAP-062',
  },
  {
    id: 'SIMPL-ABAP-063',
    category: 'Security',
    severity: 'medium',
    title: 'CDS view access control (DCL)',
    description: 'CDS Data Control Language (DCL) required for CDS view authorization in S/4HANA.',
    pattern: /\b@AccessControl\b|DEFINE\s+ROLE\b/i,
    patternType: 'source',
    remediation: 'Implement DCL access control annotations on custom CDS views.',
    simplificationId: 'S4TWL-ABAP-063',
  },
  {
    id: 'SIMPL-ABAP-064',
    category: 'Security',
    severity: 'medium',
    title: 'ICF service node security',
    description: 'ICF (Internet Communication Framework) service nodes need security review for S/4HANA.',
    pattern: /\bSICF\b|ICF_\w+/i,
    patternType: 'source',
    remediation: 'Review ICF services. Deactivate unused nodes. Secure active OData/HTTP endpoints.',
    simplificationId: 'S4TWL-ABAP-064',
  },

  // ── Testing (065–070) ─────────────────────────────────────────────────

  {
    id: 'SIMPL-ABAP-065',
    category: 'Testing',
    severity: 'medium',
    title: 'ABAP Unit test class required',
    description: 'ABAP Unit tests are mandatory for custom code quality in S/4HANA projects.',
    pattern: /\bFOR\s+TESTING\b|CL_ABAP_UNIT_ASSERT\b/i,
    patternType: 'source',
    remediation: 'Ensure ABAP Unit tests exist for all custom classes and function modules.',
    simplificationId: 'S4TWL-ABAP-065',
  },
  {
    id: 'SIMPL-ABAP-066',
    category: 'Testing',
    severity: 'high',
    title: 'ATC (ABAP Test Cockpit) checks mandatory',
    description: 'ATC checks are mandatory in S/4HANA. All custom code must pass ATC validation.',
    pattern: /\bATC_\w+|CL_CI_\w+/i,
    patternType: 'source',
    remediation: 'Run ATC checks on all custom code. Fix all priority 1 and 2 findings.',
    simplificationId: 'S4TWL-ABAP-066',
  },
  {
    id: 'SIMPL-ABAP-067',
    category: 'Testing',
    severity: 'medium',
    title: 'Code Inspector (SCI) checks',
    description: 'Code Inspector checks should be run before migration to identify issues early.',
    pattern: /\bSCI_\w+|CODE_INSPECTOR\b/i,
    patternType: 'source',
    remediation: 'Run Code Inspector with S/4HANA readiness check variant before migration.',
    simplificationId: 'S4TWL-ABAP-067',
  },
  {
    id: 'SIMPL-ABAP-068',
    category: 'Testing',
    severity: 'medium',
    title: 'Test double framework usage',
    description: 'CL_ABAP_TESTDOUBLE provides test isolation. Essential for unit testing in S/4HANA.',
    pattern: /\bCL_ABAP_TESTDOUBLE\b/i,
    patternType: 'source',
    remediation: 'Use test double framework for mocking dependencies in ABAP Unit tests.',
    simplificationId: 'S4TWL-ABAP-068',
  },
  {
    id: 'SIMPL-ABAP-069',
    category: 'Testing',
    severity: 'low',
    title: 'SQL test environment for CDS',
    description: 'CL_CDS_TEST_ENVIRONMENT provides isolated testing for CDS views.',
    pattern: /\bCL_CDS_TEST_ENVIRONMENT\b/i,
    patternType: 'source',
    remediation: 'Use CDS test environment for unit testing CDS views with mock data.',
    simplificationId: 'S4TWL-ABAP-069',
  },
  {
    id: 'SIMPL-ABAP-070',
    category: 'Testing',
    severity: 'medium',
    title: 'ABAP Unit risk level and duration',
    description: 'ABAP Unit tests must declare RISK LEVEL and DURATION for proper CI/CD integration.',
    pattern: /\bRISK\s+LEVEL\s+(HARMLESS|DANGEROUS|CRITICAL)\b/i,
    patternType: 'source',
    remediation: 'Set appropriate RISK LEVEL and DURATION on all test classes.',
    simplificationId: 'S4TWL-ABAP-070',
  },

  // ── Performance / HANA Optimization (071–080) ─────────────────────────

  {
    id: 'SIMPL-ABAP-071',
    category: 'Performance',
    severity: 'high',
    title: 'Code pushdown to HANA opportunity',
    description: 'ABAP logic that aggregates, sorts, or filters large datasets should be pushed to HANA.',
    pattern: /\bLOOP\s+AT\b[\s\S]*?\b(COLLECT|SUM|AT\s+(END|NEW)\s+OF)\b/i,
    patternType: 'source',
    remediation: 'Push aggregation logic to CDS views or AMDP procedures for HANA optimization.',
    simplificationId: 'S4TWL-ABAP-071',
  },
  {
    id: 'SIMPL-ABAP-072',
    category: 'Performance',
    severity: 'medium',
    title: 'AMDP (ABAP Managed Database Procedure)',
    description: 'AMDP allows writing HANA SQLScript within ABAP methods for complex logic.',
    pattern: /\bBY\s+DATABASE\s+PROCEDURE\b|AMDP\b/i,
    patternType: 'source',
    remediation: 'Use AMDP for complex calculations that benefit from HANA in-memory processing.',
    simplificationId: 'S4TWL-ABAP-072',
  },
  {
    id: 'SIMPL-ABAP-073',
    category: 'Performance',
    severity: 'medium',
    title: 'SORT after SELECT redundancy',
    description: 'Sorting in ABAP after SELECT is redundant if ORDER BY is used in SQL.',
    pattern: /\bSELECT\b[\s\S]*?\bINTO\s+TABLE\b[\s\S]*?\bSORT\b/i,
    patternType: 'source',
    remediation: 'Use ORDER BY in SELECT statement instead of SORT on internal table.',
    simplificationId: 'S4TWL-ABAP-073',
  },
  {
    id: 'SIMPL-ABAP-074',
    category: 'Performance',
    severity: 'medium',
    title: 'DELETE ADJACENT DUPLICATES optimization',
    description: 'DELETE ADJACENT DUPLICATES can be replaced by SELECT DISTINCT at database level.',
    pattern: /\bDELETE\s+ADJACENT\s+DUPLICATES\b/i,
    patternType: 'source',
    remediation: 'Use SELECT DISTINCT or GROUP BY in SQL to eliminate duplicates at DB level.',
    simplificationId: 'S4TWL-ABAP-074',
  },
  {
    id: 'SIMPL-ABAP-075',
    category: 'Performance',
    severity: 'medium',
    title: 'Internal table LOOP with WHERE vs HANA',
    description: 'LOOP AT itab WHERE performs sequential scan. Filter at database level instead.',
    pattern: /\bLOOP\s+AT\s+\w+\s+(INTO|ASSIGNING)\s+.*\bWHERE\b/i,
    patternType: 'source',
    remediation: 'Move filtering to SELECT WHERE clause to leverage HANA query optimization.',
    simplificationId: 'S4TWL-ABAP-075',
  },
  {
    id: 'SIMPL-ABAP-076',
    category: 'Performance',
    severity: 'high',
    title: 'CDS views replace ABAP data retrieval',
    description: 'CDS views are the preferred data access layer in S/4HANA, replacing ABAP SELECTs.',
    pattern: /\bDEFINE\s+VIEW\b.*\bAS\s+SELECT\b/i,
    patternType: 'source',
    remediation: 'Leverage CDS views for data access. Use associations instead of JOINs where possible.',
    simplificationId: 'S4TWL-ABAP-076',
  },
  {
    id: 'SIMPL-ABAP-077',
    category: 'Performance',
    severity: 'medium',
    title: 'Secondary index usage on HANA',
    description: 'Secondary indexes on HANA columnar tables behave differently than on traditional DB.',
    pattern: /\bCREATE\s+INDEX\b|SE11.*INDEX/i,
    patternType: 'source',
    remediation: 'Review secondary indexes. HANA columnar storage may not need traditional indexes.',
    simplificationId: 'S4TWL-ABAP-077',
  },
  {
    id: 'SIMPL-ABAP-078',
    category: 'Performance',
    severity: 'medium',
    title: 'Parallel processing with SPTA framework',
    description: 'SPTA framework (SPTA_PARA_PROCESS_M) enables parallelism for mass processing.',
    pattern: /\bSPTA_PARA_PROCESS_M\b/i,
    patternType: 'source',
    remediation: 'Review parallel processing setup for HANA. Ensure work packages are sized correctly.',
    simplificationId: 'S4TWL-ABAP-078',
  },
  {
    id: 'SIMPL-ABAP-079',
    category: 'Performance',
    severity: 'low',
    title: 'ABAP SQL hints for HANA',
    description: 'ABAP SQL supports database hints for HANA-specific query optimization.',
    pattern: /\b%_HINTS\b|DB_HINT\b/i,
    patternType: 'source',
    remediation: 'Use ABAP SQL hints sparingly. Prefer CDS annotations and HANA auto-optimization.',
    simplificationId: 'S4TWL-ABAP-079',
  },
  {
    id: 'SIMPL-ABAP-080',
    category: 'Performance',
    severity: 'medium',
    title: 'COLLECT statement performance on HANA',
    description: 'COLLECT into hashed table is efficient but code pushdown via CDS may be better.',
    pattern: /\bCOLLECT\s+\w+\s+INTO\b/i,
    patternType: 'source',
    remediation: 'Replace COLLECT with CDS view aggregation or GROUP BY in ABAP SQL.',
    simplificationId: 'S4TWL-ABAP-080',
  },
];
