/**
 * ABAP Language Simplification Rules
 *
 * Covers: OCCURS, RANGES, HEADER LINE, FIELD-SYMBOLS typing,
 * obsolete statements, SELECT...ENDSELECT, nested SELECTs, client-specified access.
 */

module.exports = [
  {
    id: 'SIMPL-ABAP-001',
    category: 'ABAP Language',
    severity: 'low',
    title: 'OCCURS keyword deprecated',
    description: 'OCCURS is obsolete in ABAP. While still functional, it indicates legacy code.',
    pattern: /\bOCCURS\s+\d+/i,
    patternType: 'source',
    remediation: 'Replace with standard internal table declarations (TYPE TABLE OF).',
    simplificationId: 'S4TWL-ABAP-001',
  },
  {
    id: 'SIMPL-ABAP-002',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'BDC (Batch Data Communication) usage',
    description: 'BDC/CALL TRANSACTION relies on screen sequences that may change in Fiori.',
    pattern: /\bCALL\s+TRANSACTION\s+/i,
    patternType: 'source',
    remediation: 'Replace with BAPI calls, OData services, or direct API access.',
    simplificationId: 'S4TWL-ABAP-002',
  },
  {
    id: 'SIMPL-ABAP-003',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'Direct database modification statements',
    description: 'Direct INSERT/UPDATE/DELETE on standard SAP tables bypasses application logic.',
    pattern: /\b(INSERT INTO|UPDATE\s+|DELETE FROM)\s+(BKPF|BSEG|EKKO|EKPO|VBAK|VBAP|LIKP|LIPS|MKPF|MSEG)\b/i,
    patternType: 'source',
    remediation: 'Use BAPIs or APIs instead of direct DB modifications on standard tables.',
    simplificationId: 'S4TWL-ABAP-003',
  },
  {
    id: 'SIMPL-ABAP-004',
    category: 'ABAP Language',
    severity: 'low',
    title: 'SELECT * usage on large tables',
    description: 'SELECT * reads all columns including deprecated ones. Issues with restructured tables.',
    pattern: /\bSELECT\s+\*\s+FROM\s+(BKPF|EKKO|EKPO|VBAK|VBAP|MARA|MARC|MARD)\b/i,
    patternType: 'source',
    remediation: 'Specify explicit column list instead of SELECT *.',
    simplificationId: 'S4TWL-ABAP-004',
  },
  {
    id: 'SIMPL-ABAP-005',
    category: 'ABAP Language',
    severity: 'low',
    title: 'HEADER LINE usage',
    description: 'Internal tables WITH HEADER LINE are obsolete.',
    pattern: /\bWITH\s+HEADER\s+LINE\b/i,
    patternType: 'source',
    remediation: 'Remove HEADER LINE. Use separate work area variable.',
    simplificationId: 'S4TWL-ABAP-005',
  },
  {
    id: 'SIMPL-ABAP-006',
    category: 'ABAP Language',
    severity: 'low',
    title: 'RANGES declaration deprecated',
    description: 'RANGES statement is obsolete. Use TYPE RANGE OF instead.',
    pattern: /\bRANGES\s+\w+\s+FOR\b/i,
    patternType: 'source',
    remediation: 'Replace RANGES with TYPE RANGE OF declaration.',
    simplificationId: 'S4TWL-ABAP-006',
  },
  {
    id: 'SIMPL-ABAP-007',
    category: 'ABAP Language',
    severity: 'low',
    title: 'FIELD-SYMBOLS without typing',
    description: 'FIELD-SYMBOLS without explicit typing are considered legacy.',
    pattern: /\bFIELD-SYMBOLS\s*<\w+>\s*\./i,
    patternType: 'source',
    remediation: 'Add TYPE clause to FIELD-SYMBOLS declarations.',
    simplificationId: 'S4TWL-ABAP-007',
  },
  {
    id: 'SIMPL-ABAP-008',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'SELECT...ENDSELECT loop pattern',
    description: 'SELECT...ENDSELECT reads rows one by one. Performance anti-pattern.',
    pattern: /\bSELECT\b.*\bFROM\b[\s\S]*?\bENDSELECT\b/i,
    patternType: 'source',
    remediation: 'Replace with SELECT INTO TABLE for bulk read.',
    simplificationId: 'S4TWL-ABAP-008',
  },
  {
    id: 'SIMPL-ABAP-009',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'Nested SELECT statements',
    description: 'Nested SELECTs cause N+1 query problems. Use JOINs or FOR ALL ENTRIES.',
    pattern: /SELECT\s+.*FROM\s+\w+[\s\S]*?SELECT\s+.*FROM\s+\w+/i,
    patternType: 'source',
    remediation: 'Use JOIN, subquery, or FOR ALL ENTRIES IN to avoid nested SELECTs.',
    simplificationId: 'S4TWL-ABAP-009',
  },
  {
    id: 'SIMPL-ABAP-010',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'Client-specified database access',
    description: 'CLIENT SPECIFIED bypasses automatic client handling. Risky in S/4HANA.',
    pattern: /\bCLIENT\s+SPECIFIED\b/i,
    patternType: 'source',
    remediation: 'Remove CLIENT SPECIFIED. Use proper client handling.',
    simplificationId: 'S4TWL-ABAP-010',
  },
  {
    id: 'SIMPL-ABAP-011',
    category: 'ABAP Language',
    severity: 'low',
    title: 'Obsolete MOVE-CORRESPONDING',
    description: 'MOVE-CORRESPONDING is allowed but CORRESPONDING #() is preferred in modern ABAP.',
    pattern: /\bMOVE-CORRESPONDING\b/i,
    patternType: 'source',
    remediation: 'Consider using CORRESPONDING #() constructor expression.',
    simplificationId: 'S4TWL-ABAP-011',
  },
  {
    id: 'SIMPL-ABAP-012',
    category: 'ABAP Language',
    severity: 'low',
    title: 'COMPUTE statement obsolete',
    description: 'COMPUTE statement is obsolete syntax.',
    pattern: /\bCOMPUTE\s+\w+\s*=/i,
    patternType: 'source',
    remediation: 'Remove COMPUTE keyword, use direct assignment.',
    simplificationId: 'S4TWL-ABAP-012',
  },
  {
    id: 'SIMPL-ABAP-013',
    category: 'ABAP Language',
    severity: 'low',
    title: 'FORM/PERFORM obsolete',
    description: 'FORM/PERFORM subroutines are obsolete. Use methods instead.',
    pattern: /\bPERFORM\s+\w+\b/i,
    patternType: 'source',
    remediation: 'Refactor FORMs into class methods.',
    simplificationId: 'S4TWL-ABAP-013',
  },
  {
    id: 'SIMPL-ABAP-014',
    category: 'ABAP Language',
    severity: 'medium',
    title: 'READ TABLE with SY-TABIX',
    description: 'READ TABLE with SY-TABIX is legacy. Use table expressions or ASSIGN.',
    pattern: /\bREAD\s+TABLE\b.*\bSY-TABIX\b/i,
    patternType: 'source',
    remediation: 'Use table expressions (itab[ key ]) or ASSIGN for modern access.',
    simplificationId: 'S4TWL-ABAP-014',
  },
  {
    id: 'SIMPL-ABAP-015',
    category: 'ABAP Language',
    severity: 'low',
    title: 'TABLES declaration obsolete',
    description: 'TABLES statement for global work areas is obsolete.',
    pattern: /^\s*TABLES:\s+\w+/im,
    patternType: 'source',
    remediation: 'Replace TABLES with typed DATA declarations.',
    simplificationId: 'S4TWL-ABAP-015',
  },
];
