/**
 * Business Partner (BP) Simplification Rules
 *
 * Covers: Customer/Vendor → BP migration, CVI synchronization,
 * contact persons, bank details, partner functions, BP relationship
 * categories, tax numbers, address management, communication data,
 * customer hierarchy, vendor hierarchy, credit management in BP,
 * BP groups, BP roles, and API migration.
 */

module.exports = [
  {
    id: 'SIMPL-BP-001',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer master tables deprecated',
    description: 'KNA1, KNB1, KNVV (customer master) are deprecated. Business Partner (BUT000) is the master.',
    pattern: /\b(KNA1|KNB1|KNVV|KNB5|KNVK)\b/i,
    patternType: 'source',
    remediation: 'Use Business Partner tables (BUT000, BUT020, BUT050, BUT100) or API_BUSINESS_PARTNER.',
    simplificationId: 'S4TWL-MD-BP-001',
  },
  {
    id: 'SIMPL-BP-002',
    category: 'Business Partner',
    severity: 'high',
    title: 'Vendor master tables deprecated',
    description: 'LFA1, LFB1 (vendor master) are deprecated. Business Partner (BUT000) is the master.',
    pattern: /\b(LFA1|LFB1|LFB5|LFBK)\b/i,
    patternType: 'source',
    remediation: 'Use Business Partner tables or API_BUSINESS_PARTNER OData service.',
    simplificationId: 'S4TWL-MD-BP-002',
  },
  {
    id: 'SIMPL-BP-003',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Customer/Vendor BAPIs deprecated',
    description: 'BAPI_CUSTOMER_* and BAPI_VENDOR_* function modules are deprecated.',
    pattern: /\b(BAPI_CUSTOMER_|BAPI_VENDOR_)\w+/i,
    patternType: 'source',
    remediation: 'Use API_BUSINESS_PARTNER OData service or CDS-based APIs.',
    simplificationId: 'S4TWL-MD-BP-003',
  },
  {
    id: 'SIMPL-BP-004',
    category: 'Business Partner',
    severity: 'high',
    title: 'Contact person tables changed',
    description: 'KNVK (customer contact) is deprecated. Contact persons managed via BP relationships.',
    pattern: /\bKNVK\b/i,
    patternType: 'source',
    remediation: 'Use BP contact person relationship category. Use BUT050/BUT051.',
    simplificationId: 'S4TWL-MD-BP-004',
  },
  {
    id: 'SIMPL-BP-005',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Bank details migration to BP',
    description: 'Customer/vendor bank details (KNBK/LFBK) migrated to BP bank details.',
    pattern: /\b(KNBK|LFBK)\b/i,
    patternType: 'source',
    remediation: 'Use BUT0BK for BP bank details.',
    simplificationId: 'S4TWL-MD-BP-005',
  },
  {
    id: 'SIMPL-BP-006',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer/vendor number sync required',
    description: 'BP number, customer number, and vendor number must be synchronized.',
    pattern: /\b(KUNNR|LIFNR).*(?:CONVERT|NUMBER_GET|ASSIGN)\b/i,
    patternType: 'source',
    remediation: 'Use BP number ranges and synchronization. Configure CVI (Customer Vendor Integration).',
    simplificationId: 'S4TWL-MD-BP-006',
  },
  {
    id: 'SIMPL-BP-007',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Partner function determination changed',
    description: 'Partner functions now route through BP. VBPA partner fields affected.',
    pattern: /\bVBPA\b/i,
    patternType: 'source',
    remediation: 'Review partner function determination for BP integration.',
    simplificationId: 'S4TWL-MD-BP-007',
  },
  {
    id: 'SIMPL-BP-008',
    category: 'Business Partner',
    severity: 'medium',
    title: 'BP relationship categories',
    description: 'BP relationships (BUT050, BUT051) replace direct customer/vendor links.',
    pattern: /\b(BUT050|BUT051|BUT0BK|BUT020)\b/i,
    patternType: 'source',
    remediation: 'Review BP relationship category usage and ensure proper setup.',
    simplificationId: 'S4TWL-MD-BP-008',
  },
  {
    id: 'SIMPL-BP-009',
    category: 'Business Partner',
    severity: 'medium',
    title: 'CVI synchronization required',
    description: 'Customer Vendor Integration (CVI) must be configured for BP synchronization.',
    pattern: /\bCVI_|SMT_|SY-SUBRC.*CUSTOMER_|VENDOR_/i,
    patternType: 'source',
    remediation: 'Configure CVI for bidirectional synchronization between BP and customer/vendor.',
    simplificationId: 'S4TWL-MD-BP-009',
  },
  {
    id: 'SIMPL-BP-010',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer/vendor creation transactions deprecated',
    description: 'XD01/XD02/XK01/XK02 replaced by BP transaction.',
    pattern: /\b(XD01|XD02|XD03|XK01|XK02|XK03|FD01|FD02|FK01|FK02)\b/i,
    patternType: 'source',
    remediation: 'Use BP transaction or API_BUSINESS_PARTNER for master data maintenance.',
    simplificationId: 'S4TWL-MD-BP-010',
  },
  {
    id: 'SIMPL-BP-011',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Customer hierarchy changes',
    description: 'Customer hierarchy (KNVH) affected by BP migration.',
    pattern: /\bKNVH\b/i,
    patternType: 'source',
    remediation: 'Review customer hierarchy for BP-based hierarchy.',
    simplificationId: 'S4TWL-MD-BP-011',
  },
  {
    id: 'SIMPL-BP-012',
    category: 'Business Partner',
    severity: 'low',
    title: 'Tax number handling changes',
    description: 'Tax numbers managed via BP tax number table.',
    pattern: /\b(DFKKBPTAXNUM|J_1BTAXNUMBE)\b/i,
    patternType: 'source',
    remediation: 'Use BP tax number management.',
    simplificationId: 'S4TWL-MD-BP-012',
  },
  // ── Rules 013–038: expanded coverage ──
  {
    id: 'SIMPL-BP-013',
    category: 'Business Partner',
    severity: 'high',
    title: 'BUT000 central BP table usage',
    description: 'BUT000 is the central Business Partner table in S/4HANA. All customer and vendor master records are stored here. Direct SELECT on BUT000 should use CDS views where possible.',
    pattern: /\bBUT000\b/i,
    patternType: 'source',
    remediation: 'Use CDS view I_BusinessPartner or API_BUSINESS_PARTNER OData service instead of direct table access.',
    simplificationId: 'S4TWL-MD-BP-013',
  },
  {
    id: 'SIMPL-BP-014',
    category: 'Business Partner',
    severity: 'high',
    title: 'BP role assignment required',
    description: 'Business Partners must be assigned roles (e.g., FLCU00 for customer, FLVN00 for vendor, BUP003 for employee). Missing BP roles cause CVI synchronization failures.',
    pattern: /\b(BUT100|BP_ROLE|FLCU00|FLVN00|FLCU01|FLVN01|BUP001|BUP002|BUP003)\b/i,
    patternType: 'source',
    remediation: 'Ensure all Business Partners have correct BP roles assigned. Map legacy customer/vendor roles to appropriate BP role categories.',
    simplificationId: 'S4TWL-MD-BP-014',
  },
  {
    id: 'SIMPL-BP-015',
    category: 'Business Partner',
    severity: 'medium',
    title: 'BP grouping controls number ranges',
    description: 'BP grouping (BU_GROUP) determines number range, partner type, and allowed roles. Incorrect grouping prevents customer/vendor creation.',
    pattern: /\b(BU_GROUP|BP_GROUP|TB003|TB004)\b/i,
    patternType: 'source',
    remediation: 'Define BP grouping categories and assign appropriate number ranges and allowed BP roles per group.',
    simplificationId: 'S4TWL-MD-BP-015',
  },
  {
    id: 'SIMPL-BP-016',
    category: 'Business Partner',
    severity: 'high',
    title: 'CVI mapping configuration tables',
    description: 'CVI mapping tables (CVI_CUST_LINK, CVI_VEND_LINK) link BP number to customer/vendor number. Missing entries break synchronization.',
    pattern: /\b(CVI_CUST_LINK|CVI_VEND_LINK|CVIS_|CVI_EI_)\w*/i,
    patternType: 'source',
    remediation: 'Ensure CVI mapping tables are populated. Use transaction BUPA_PRE_DA for pre-conversion data alignment.',
    simplificationId: 'S4TWL-MD-BP-016',
  },
  {
    id: 'SIMPL-BP-017',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer/vendor number range synchronization',
    description: 'In S/4HANA, BP number, customer number, and vendor number must use the same number or be mapped. Same-number approach is recommended.',
    pattern: /\b(SNRO|NUMBER_RANGE_|NROBJ)\b.*\b(BP|DEBITOR|KREDITOR|BU_PARTNER)\b/i,
    patternType: 'source',
    remediation: 'Configure synchronized number ranges for BP, customer, and vendor. Use same-number approach where possible.',
    simplificationId: 'S4TWL-MD-BP-017',
  },
  {
    id: 'SIMPL-BP-018',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Customer sales area data in BP context',
    description: 'Customer sales area data (KNVV fields) is still maintained but accessed through BP layer. Custom code reading KNVV directly needs review.',
    pattern: /\bKNVV\b.*\b(SELECT|READ|LOOP)\b|\b(SELECT|READ|LOOP)\b.*\bKNVV\b/i,
    patternType: 'source',
    remediation: 'Use I_CustomerSalesArea CDS view or API_BUSINESS_PARTNER with sales area extension.',
    simplificationId: 'S4TWL-MD-BP-018',
  },
  {
    id: 'SIMPL-BP-019',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Vendor purchasing organization data in BP context',
    description: 'Vendor purchasing data (LFM1, LFM2) is accessed through BP layer. Direct table access needs migration.',
    pattern: /\b(LFM1|LFM2)\b/i,
    patternType: 'source',
    remediation: 'Use I_SupplierPurchasingOrg CDS view or API_BUSINESS_PARTNER with purchasing extension.',
    simplificationId: 'S4TWL-MD-BP-019',
  },
  {
    id: 'SIMPL-BP-020',
    category: 'Business Partner',
    severity: 'medium',
    title: 'BP address management (BUT020/ADRC)',
    description: 'BP address data is managed through BUT020 (address assignment) and ADRC (address data). Customer/vendor address tables are compatibility views.',
    pattern: /\b(BUT020|ADRC|ADDR\d_|ADR[0-9])\b/i,
    patternType: 'source',
    remediation: 'Use BP address management APIs. Access address data through I_BPContactToAddress or I_Address CDS views.',
    simplificationId: 'S4TWL-MD-BP-020',
  },
  {
    id: 'SIMPL-BP-021',
    category: 'Business Partner',
    severity: 'medium',
    title: 'BP communication data (ADR2/ADR3/ADR6)',
    description: 'Phone (ADR2), fax (ADR3), and email (ADR6) data is managed through central address management linked to BP.',
    pattern: /\b(ADR2|ADR3|ADR6|ADR12|ADRP)\b/i,
    patternType: 'source',
    remediation: 'Use BP communication data APIs. Access through I_AddressEmailAddress, I_AddressPhoneNumber CDS views.',
    simplificationId: 'S4TWL-MD-BP-021',
  },
  {
    id: 'SIMPL-BP-022',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer/vendor tax number migration',
    description: 'Tax numbers (STCD1-STCD5 in KNA1/LFA1) are migrated to BP tax number table (DFKKBPTAXNUM). Tax classification also moves to BP.',
    pattern: /\b(STCD1|STCD2|STCD3|STCD4|STCD5|FITYP)\b/i,
    patternType: 'source',
    remediation: 'Use DFKKBPTAXNUM for BP tax numbers. Access via I_BusinessPartnerTaxNumber CDS view.',
    simplificationId: 'S4TWL-MD-BP-022',
  },
  {
    id: 'SIMPL-BP-023',
    category: 'Business Partner',
    severity: 'medium',
    title: 'BP industry sector classification',
    description: 'Industry sector (BUT0IS) replaces direct industry fields in KNA1/LFA1. Industry classification system must be configured.',
    pattern: /\b(BUT0IS|BU_ID_TYPE|BU_ID_NUMBER)\b/i,
    patternType: 'source',
    remediation: 'Configure industry sector classification for BP. Map legacy industry codes to BP industry sectors.',
    simplificationId: 'S4TWL-MD-BP-023',
  },
  {
    id: 'SIMPL-BP-024',
    category: 'Business Partner',
    severity: 'high',
    title: 'Contact person BP relationship',
    description: 'Contact persons are now separate BP records (type person) linked to organization BP via relationship category BUR001. KNVK data migrates to BUT050/BUT051.',
    pattern: /\b(BUR001|BUR010|BUR011|CONTACT_PERSON|BUT051)\b/i,
    patternType: 'source',
    remediation: 'Create BP records for contact persons and link via relationship. Use I_BPContactToFuncAndDept CDS view.',
    simplificationId: 'S4TWL-MD-BP-024',
  },
  {
    id: 'SIMPL-BP-025',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Partner function table VBPA changes',
    description: 'Sales document partner functions (VBPA) now reference BP numbers. Custom partner determination logic must account for BP integration.',
    pattern: /\b(VBPA|J_1BSDPARN|TPAR)\b/i,
    patternType: 'source',
    remediation: 'Review partner function determination for BP. Verify VBPA-KUNNR is populated via CVI. Use I_SalesDocumentPartner CDS view.',
    simplificationId: 'S4TWL-MD-BP-025',
  },
  {
    id: 'SIMPL-BP-026',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Purchase order partner function changes',
    description: 'Purchasing document partner functions (EKPA) now reference BP numbers. Custom partner logic in purchasing must be reviewed.',
    pattern: /\bEKPA\b/i,
    patternType: 'source',
    remediation: 'Review EKPA partner functions for BP integration. Ensure vendor numbers are synced through CVI.',
    simplificationId: 'S4TWL-MD-BP-026',
  },
  {
    id: 'SIMPL-BP-027',
    category: 'Business Partner',
    severity: 'high',
    title: 'Vendor hierarchy changes',
    description: 'Vendor hierarchy (WYT3) is affected by BP migration. Vendor sub-ranges must be mapped to BP.',
    pattern: /\b(WYT3|EINA|EINE)\b.*\b(LIFNR|VENDOR)\b|\bWYT3\b/i,
    patternType: 'source',
    remediation: 'Review vendor hierarchy structures. Map vendor sub-ranges to BP hierarchy if applicable.',
    simplificationId: 'S4TWL-MD-BP-027',
  },
  {
    id: 'SIMPL-BP-028',
    category: 'Business Partner',
    severity: 'high',
    title: 'Credit management data in BP',
    description: 'Credit management master data (KNKK) is linked to BP in SAP Credit Management (FSCM). Credit segment data must reference BP number.',
    pattern: /\b(KNKK|KNKA|UKM_BUSINESS_PARTNER|UKM_BP_CMS_SGM)\b/i,
    patternType: 'source',
    remediation: 'Migrate credit management to FSCM. Link credit segments to BP. Use UKM_BUSINESS_PARTNER for credit data.',
    simplificationId: 'S4TWL-MD-BP-028',
  },
  {
    id: 'SIMPL-BP-029',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Customer dunning data in BP context',
    description: 'Customer dunning area data (KNB5) is accessed through BP layer. Dunning procedures must reference BP.',
    pattern: /\bKNB5\b/i,
    patternType: 'source',
    remediation: 'Access dunning data through I_CustomerDunning CDS view. Ensure BP synchronization for dunning.',
    simplificationId: 'S4TWL-MD-BP-029',
  },
  {
    id: 'SIMPL-BP-030',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Withholding tax data in BP context',
    description: 'Customer/vendor withholding tax data (LFBW/KNBW) migrated to BP withholding tax management.',
    pattern: /\b(LFBW|KNBW|WITH_ITEM)\b/i,
    patternType: 'source',
    remediation: 'Use BP withholding tax tables. Access via I_CustomerWithHoldingTax or I_SupplierWithHoldingTax CDS views.',
    simplificationId: 'S4TWL-MD-BP-030',
  },
  {
    id: 'SIMPL-BP-031',
    category: 'Business Partner',
    severity: 'low',
    title: 'BP identification numbers',
    description: 'Identification numbers (DUNS, tax registration, etc.) stored in BUT0ID. Legacy identification fields in KNA1/LFA1 are deprecated.',
    pattern: /\b(BUT0ID|BU_ID_TYPE|BU_ID_NUMBER)\b/i,
    patternType: 'source',
    remediation: 'Use BUT0ID for identification numbers. Access through I_BPIdentificationNumber CDS view.',
    simplificationId: 'S4TWL-MD-BP-031',
  },
  {
    id: 'SIMPL-BP-032',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Customer/vendor display transactions deprecated',
    description: 'VD03/VD02/MK03/MK02 (customer/vendor display/change via accounting) replaced by BP transaction.',
    pattern: /\b(VD01|VD02|VD03|MK01|MK02|MK03)\b/i,
    patternType: 'source',
    remediation: 'Use BP transaction for master data display/change. Access through Fiori apps Manage Business Partner.',
    simplificationId: 'S4TWL-MD-BP-032',
  },
  {
    id: 'SIMPL-BP-033',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer/vendor integration BAdIs',
    description: 'CVI BAdIs (CUSTOMER_ADD_DATA, VENDOR_ADD_DATA) are critical for mapping custom fields between BP and customer/vendor views.',
    pattern: /\b(CUSTOMER_ADD_DATA|VENDOR_ADD_DATA|BUPA_|CVI_CUSTOM_)\w*/i,
    patternType: 'source',
    remediation: 'Implement CVI BAdIs for custom field mapping. Register custom segments in CVI configuration.',
    simplificationId: 'S4TWL-MD-BP-033',
  },
  {
    id: 'SIMPL-BP-034',
    category: 'Business Partner',
    severity: 'medium',
    title: 'BP pre-conversion data alignment tool',
    description: 'BUPA_PRE_DA transaction must be run to identify and fix data inconsistencies before migration. Duplicate check is critical.',
    pattern: /\b(BUPA_PRE_DA|MDS_LOAD_COCKPIT|MDS_BP_)\w*/i,
    patternType: 'source',
    remediation: 'Run BUPA_PRE_DA to identify duplicate customers/vendors. Resolve all data inconsistencies before conversion.',
    simplificationId: 'S4TWL-MD-BP-034',
  },
  {
    id: 'SIMPL-BP-035',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Customer company code data in BP context',
    description: 'Customer company code data (KNB1) is maintained as a compatibility view. New developments should use BP APIs.',
    pattern: /\bKNB1\b.*\b(SELECT|UPDATE|INSERT)\b|\b(SELECT|UPDATE|INSERT)\b.*\bKNB1\b/i,
    patternType: 'source',
    remediation: 'Use I_CustomerCompany CDS view or API_BUSINESS_PARTNER for company code level data.',
    simplificationId: 'S4TWL-MD-BP-035',
  },
  {
    id: 'SIMPL-BP-036',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Vendor company code data in BP context',
    description: 'Vendor company code data (LFB1) is maintained as a compatibility view. New developments should use BP APIs.',
    pattern: /\bLFB1\b.*\b(SELECT|UPDATE|INSERT)\b|\b(SELECT|UPDATE|INSERT)\b.*\bLFB1\b/i,
    patternType: 'source',
    remediation: 'Use I_SupplierCompany CDS view or API_BUSINESS_PARTNER for company code level data.',
    simplificationId: 'S4TWL-MD-BP-036',
  },
  {
    id: 'SIMPL-BP-037',
    category: 'Business Partner',
    severity: 'high',
    title: 'Dual maintenance of customer/vendor and BP',
    description: 'In S/4HANA there is no dual maintenance. BP is the single point of entry. Legacy transactions that write directly to KNA1/LFA1 will cause data inconsistencies.',
    pattern: /\b(SD_CUSTOMER_MAINTAIN|VENDOR_MAINTAIN|IDOC_INPUT_CREMAS|IDOC_INPUT_DEBMAS)\b/i,
    patternType: 'source',
    remediation: 'Use BP API or transaction for all master data changes. Remove any direct writes to KNA1/LFA1 tables.',
    simplificationId: 'S4TWL-MD-BP-037',
  },
  {
    id: 'SIMPL-BP-038',
    category: 'Business Partner',
    severity: 'medium',
    title: 'BP search help and matchcode changes',
    description: 'Customer/vendor search helps (matchcodes) reference BP search. Custom search helps on KNA1/LFA1 need adaptation.',
    pattern: /\b(DEBIA|DEBIE|KREDA|KREDE|SEARCH_HELP_)\w*.*\b(KUNNR|LIFNR)\b/i,
    patternType: 'source',
    remediation: 'Use BP search helps or build custom search helps on BUT000. Review collective search helps.',
    simplificationId: 'S4TWL-MD-BP-038',
  },
];
