/**
 * Business Partner (BP) Simplification Rules
 *
 * Covers: Customer/Vendor → BP migration, contact persons,
 * bank details, partner functions, BP relationship categories.
 */

module.exports = [
  {
    id: 'SIMPL-BP-001',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer master tables deprecated',
    description: 'KNA1, KNB1, KNVV (customer master) are deprecated. Business Partner (BUT000) is the master.',
    pattern: /\b(KNA1|KNB1|KNVV|KNB5|KNVK)\b/i,
    patternType: 'source',
    remediation: 'Use Business Partner tables (BUT000, BUT020, BUT050, BUT100) or API_BUSINESS_PARTNER.',
    simplificationId: 'S4TWL-MD-BP-001',
  },
  {
    id: 'SIMPL-BP-002',
    category: 'Business Partner',
    severity: 'high',
    title: 'Vendor master tables deprecated',
    description: 'LFA1, LFB1 (vendor master) are deprecated. Business Partner (BUT000) is the master.',
    pattern: /\b(LFA1|LFB1|LFB5|LFBK)\b/i,
    patternType: 'source',
    remediation: 'Use Business Partner tables or API_BUSINESS_PARTNER OData service.',
    simplificationId: 'S4TWL-MD-BP-002',
  },
  {
    id: 'SIMPL-BP-003',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Customer/Vendor BAPIs deprecated',
    description: 'BAPI_CUSTOMER_* and BAPI_VENDOR_* function modules are deprecated.',
    pattern: /\b(BAPI_CUSTOMER_|BAPI_VENDOR_)\w+/i,
    patternType: 'source',
    remediation: 'Use API_BUSINESS_PARTNER OData service or CDS-based APIs.',
    simplificationId: 'S4TWL-MD-BP-003',
  },
  {
    id: 'SIMPL-BP-004',
    category: 'Business Partner',
    severity: 'high',
    title: 'Contact person tables changed',
    description: 'KNVK (customer contact) is deprecated. Contact persons managed via BP relationships.',
    pattern: /\bKNVK\b/i,
    patternType: 'source',
    remediation: 'Use BP contact person relationship category. Use BUT050/BUT051.',
    simplificationId: 'S4TWL-MD-BP-004',
  },
  {
    id: 'SIMPL-BP-005',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Bank details migration to BP',
    description: 'Customer/vendor bank details (KNBK/LFBK) migrated to BP bank details.',
    pattern: /\b(KNBK|LFBK)\b/i,
    patternType: 'source',
    remediation: 'Use BUT0BK for BP bank details.',
    simplificationId: 'S4TWL-MD-BP-005',
  },
  {
    id: 'SIMPL-BP-006',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer/vendor number sync required',
    description: 'BP number, customer number, and vendor number must be synchronized.',
    pattern: /\b(KUNNR|LIFNR).*(?:CONVERT|NUMBER_GET|ASSIGN)\b/i,
    patternType: 'source',
    remediation: 'Use BP number ranges and synchronization. Configure CVI (Customer Vendor Integration).',
    simplificationId: 'S4TWL-MD-BP-006',
  },
  {
    id: 'SIMPL-BP-007',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Partner function determination changed',
    description: 'Partner functions now route through BP. VBPA partner fields affected.',
    pattern: /\bVBPA\b/i,
    patternType: 'source',
    remediation: 'Review partner function determination for BP integration.',
    simplificationId: 'S4TWL-MD-BP-007',
  },
  {
    id: 'SIMPL-BP-008',
    category: 'Business Partner',
    severity: 'medium',
    title: 'BP relationship categories',
    description: 'BP relationships (BUT050, BUT051) replace direct customer/vendor links.',
    pattern: /\b(BUT050|BUT051|BUT0BK|BUT020)\b/i,
    patternType: 'source',
    remediation: 'Review BP relationship category usage and ensure proper setup.',
    simplificationId: 'S4TWL-MD-BP-008',
  },
  {
    id: 'SIMPL-BP-009',
    category: 'Business Partner',
    severity: 'medium',
    title: 'CVI synchronization required',
    description: 'Customer Vendor Integration (CVI) must be configured for BP synchronization.',
    pattern: /\bCVI_|SMT_|SY-SUBRC.*CUSTOMER_|VENDOR_/i,
    patternType: 'source',
    remediation: 'Configure CVI for bidirectional synchronization between BP and customer/vendor.',
    simplificationId: 'S4TWL-MD-BP-009',
  },
  {
    id: 'SIMPL-BP-010',
    category: 'Business Partner',
    severity: 'high',
    title: 'Customer/vendor creation transactions deprecated',
    description: 'XD01/XD02/XK01/XK02 replaced by BP transaction.',
    pattern: /\b(XD01|XD02|XD03|XK01|XK02|XK03|FD01|FD02|FK01|FK02)\b/i,
    patternType: 'source',
    remediation: 'Use BP transaction or API_BUSINESS_PARTNER for master data maintenance.',
    simplificationId: 'S4TWL-MD-BP-010',
  },
  {
    id: 'SIMPL-BP-011',
    category: 'Business Partner',
    severity: 'medium',
    title: 'Customer hierarchy changes',
    description: 'Customer hierarchy (KNVH) affected by BP migration.',
    pattern: /\bKNVH\b/i,
    patternType: 'source',
    remediation: 'Review customer hierarchy for BP-based hierarchy.',
    simplificationId: 'S4TWL-MD-BP-011',
  },
  {
    id: 'SIMPL-BP-012',
    category: 'Business Partner',
    severity: 'low',
    title: 'Tax number handling changes',
    description: 'Tax numbers managed via BP tax number table.',
    pattern: /\b(DFKKBPTAXNUM|J_1BTAXNUMBE)\b/i,
    patternType: 'source',
    remediation: 'Use BP tax number management.',
    simplificationId: 'S4TWL-MD-BP-012',
  },
];
