/**
 * BW / Analytics Rules
 *
 * Covers transition from BW extractors and data sources to
 * S/4HANA embedded analytics (CDS views), BW/4HANA migration,
 * and classic BW compatibility concerns.
 * Extended: module-specific extractor migration, BW/4HANA specifics,
 * SAC integration, embedded analytics CDS, real-time replication, DWC.
 */

module.exports = [
  // ── Extractor Changes ────────────────────────────────────────
  {
    id: 'SIMPL-BW-001',
    title: 'FI Extractors Replaced',
    description: 'Classic FI extractors (0FI_GL_*, 0FI_AR_*, 0FI_AP_*) replaced by CDS-based extraction from ACDOCA.',
    severity: 'critical',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(0FI_GL_|0FI_AR_|0FI_AP_|\bFAGLFLEXT\b|0FI_AA_)/i,
    patternType: 'source',
    remediation: 'Migrate to CDS-based extractors (e.g., I_GLAccountLineItem). Review BW data flow for ACDOCA sourcing.',
  },
  {
    id: 'SIMPL-BW-002',
    title: 'CO Extractors Changed',
    description: 'CO extractors (0CO_OM_*, 0CO_PC_*) impacted by universal journal. Cost element tables removed.',
    severity: 'high',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(0CO_OM_|0CO_PC_|0CO_PA_|\bCOSS\b|\bCOSP\b)/i,
    patternType: 'source',
    remediation: 'Replace CO extractors with ACDOCA/ACDOCP-based CDS extractors.',
  },
  {
    id: 'SIMPL-BW-003',
    title: 'MM/SD Extractors Updated',
    description: 'Logistics extractors (2LIS_*) restructured. Some setup tables (LBWE) logic changed.',
    severity: 'high',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(2LIS_0[1-9]|2LIS_1[1-3]|\bLBWE\b|\bMC_SETUP\b)/i,
    patternType: 'source',
    remediation: 'Review logistics extractor activation. Validate setup table fills and delta handling.',
  },
  {
    id: 'SIMPL-BW-004',
    title: 'Asset Extractors Changed',
    description: 'Asset accounting extractors impacted by new asset accounting (ACDOCA-based, no ANLP/ANLC index).',
    severity: 'high',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(0FIAA_|0AM_|\bANLP\b|\bANLC\b)/i,
    patternType: 'source',
    remediation: 'Migrate to new asset analytics extractors sourcing from ANEK/ANEP via ACDOCA.',
  },

  // ── CDS Views / Embedded Analytics ───────────────────────────
  {
    id: 'SIMPL-BW-005',
    title: 'Embedded Analytics via CDS Views',
    description: 'S/4HANA promotes CDS-based embedded analytics over classic BW reporting for operational analytics.',
    severity: 'medium',
    category: 'BW – Embedded Analytics',
    sNote: '2381257',
    pattern: /\b(CDS_VIEW|I_JOURNAL|C_GLLINE|ANALYTICAL_QUERY)\b/i,
    patternType: 'source',
    remediation: 'Evaluate which BW reports can be replaced by embedded analytics CDS views.',
  },
  {
    id: 'SIMPL-BW-006',
    title: 'Query Migration to BW/4HANA',
    description: 'Classic BW queries on BEx must be evaluated for migration to BW/4HANA composite providers.',
    severity: 'medium',
    category: 'BW – Embedded Analytics',
    sNote: '2381257',
    pattern: /\b(BEX_QUERY|RSZCOMPDIR|RSZELTDIR|MULTIPROVIDER)\b/i,
    patternType: 'source',
    remediation: 'Assess BEx queries for BW/4HANA compatibility. Migrate to composite providers where applicable.',
  },

  // ── Data Source Compatibility ────────────────────────────────
  {
    id: 'SIMPL-BW-007',
    title: 'Custom Extractors Validation',
    description: 'Custom extractors (Z* datasources) must be validated against S/4HANA table model changes.',
    severity: 'high',
    category: 'BW – Custom Extractors',
    sNote: '2381257',
    pattern: /\b(RSA[1-3]|ROOSOURCE|EXTRACTION)\b|Z[A-Z0-9]+_DS/i,
    patternType: 'source',
    remediation: 'Test all custom extractors. Replace references to removed tables (BSEG, BKPF, KONV, etc.).',
  },
  {
    id: 'SIMPL-BW-008',
    title: 'InfoObject Compatibility',
    description: 'InfoObjects referencing removed or changed S/4HANA fields need master data reloads.',
    severity: 'medium',
    category: 'BW – Data Model',
    sNote: '2381257',
    pattern: /\b(INFOOBJECT|RSDODSO|RSDIOBJ|ADSO)\b/i,
    patternType: 'source',
    remediation: 'Review InfoObject definitions against S/4HANA data model. Reload master data where fields changed.',
  },

  // ── Module-Specific Extractor Migration ──────────────────────
  {
    id: 'SIMPL-BW-009',
    title: 'HR/HCM Extractors Migration',
    description: 'HR extractors (0HR_PA_*, 0HR_PT_*, 0HR_PY_*) must be evaluated for SuccessFactors migration or direct CDS-based extraction from S/4HANA HCM. PA infotype extractors reference changed table structures.',
    severity: 'high',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(0HR_PA_|0HR_PT_|0HR_PY_|0HR_OM_|\bPA_INFOTYPE\b)/i,
    patternType: 'source',
    remediation: 'Evaluate HR extractor migration path. For cloud HCM, use SuccessFactors OData APIs. For on-premise, validate CDS extractors.',
  },
  {
    id: 'SIMPL-BW-010',
    title: 'PP/QM Extractors Restructured',
    description: 'Production planning extractors (2LIS_04*, 2LIS_05*) and quality management extractors (0QM_*) are restructured. Shop floor and inspection lot extraction logic may change with new data model.',
    severity: 'high',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(2LIS_04|2LIS_05|0QM_|0PP_|\bAFKO_EXT\b)/i,
    patternType: 'source',
    remediation: 'Validate PP/QM extractors. Test production order and inspection lot delta extraction after S/4HANA migration.',
  },
  {
    id: 'SIMPL-BW-011',
    title: 'PM/CS Extractors for Maintenance Analytics',
    description: 'Plant maintenance extractors (0PM_*, 0CS_*) must be validated against S/4HANA maintenance order and notification data model changes. Equipment and functional location hierarchies may impact extraction.',
    severity: 'medium',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(0PM_|0CS_|\bPM_ORDER_EXT\b|\bNOTIF_EXT\b)/i,
    patternType: 'source',
    remediation: 'Validate PM/CS extractors. Test maintenance order, notification, and equipment hierarchy extraction.',
  },
  {
    id: 'SIMPL-BW-012',
    title: 'Treasury and Cash Management Extractors',
    description: 'Treasury extractors (0FITV_*, 0FICM_*) impacted by S/4HANA cash management and treasury changes. Bank accounting integration with ACDOCA affects transaction-level extraction.',
    severity: 'medium',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(0FITV_|0FICM_|\bTREASURY_EXT\b|\bCASH_MGMT_EXT\b)/i,
    patternType: 'source',
    remediation: 'Validate treasury and cash management extractors. Test extraction from new cash management data model.',
  },
  {
    id: 'SIMPL-BW-013',
    title: 'Profitability Analysis (CO-PA) Extractors',
    description: 'CO-PA extractors (0CO_PA_*) significantly impacted by account-based CO-PA becoming the primary approach in S/4HANA. Costing-based CO-PA extractors require ACDOCP-based replacement.',
    severity: 'critical',
    category: 'BW – Extractors',
    sNote: '2381257',
    pattern: /(0CO_PA_|CO_PA_EXT|\bCE[1-9][A-Z0-9]+\b|\bACDOCP\b)/i,
    patternType: 'source',
    remediation: 'Migrate CO-PA extractors to account-based CO-PA via ACDOCP. Rebuild profitability reports on universal journal.',
  },

  // ── BW/4HANA Migration Specifics ─────────────────────────────
  {
    id: 'SIMPL-BW-014',
    title: 'InfoCube to Advanced DSO Migration',
    description: 'BW/4HANA removes classic InfoCubes. All InfoCubes must be migrated to Advanced DataStore Objects (ADSO) with appropriate modeling (inbound, active, change log layers).',
    severity: 'critical',
    category: 'BW – BW/4HANA',
    sNote: '2381257',
    pattern: /\b(INFOCUBE|RSDCUBE|RSKCUBE|CUBE_MIGRATE)\b/i,
    patternType: 'source',
    remediation: 'Migrate all InfoCubes to ADSO using BW/4HANA transfer tool. Define inbound and reporting layer per ADSO.',
  },
  {
    id: 'SIMPL-BW-015',
    title: 'MultiProvider to Composite Provider Migration',
    description: 'BW/4HANA replaces MultiProviders with Composite Providers. Union and join semantics must be reviewed and rebuilt using new composite provider modeling.',
    severity: 'high',
    category: 'BW – BW/4HANA',
    sNote: '2381257',
    pattern: /\b(MULTIPROVIDER|RSDMULTIPROV|COMPOSITE_PROV|UNION_QUERY)\b/i,
    patternType: 'source',
    remediation: 'Migrate MultiProviders to Composite Providers. Review union/join definitions and field mapping.',
  },
  {
    id: 'SIMPL-BW-016',
    title: 'Classic DSO to Advanced DSO Migration',
    description: 'Classic DataStore Objects (write-optimized, standard) must be migrated to Advanced DSO types. Activation behavior, change log handling, and SID generation options differ in ADSO.',
    severity: 'high',
    category: 'BW – BW/4HANA',
    sNote: '2381257',
    pattern: /\b(CLASSIC_DSO|RSDODSO|WRITE_OPT_DSO|STD_DSO|DSO_MIGRATE)\b/i,
    patternType: 'source',
    remediation: 'Migrate classic DSOs to Advanced DSOs. Configure activation type and change log settings per data flow requirements.',
  },
  {
    id: 'SIMPL-BW-017',
    title: 'BEx Query to BW/4HANA Query Migration',
    description: 'BEx queries must be converted to BW/4HANA-compatible queries. BEx features like conditions, exceptions, and custom structures need evaluation for compatibility.',
    severity: 'high',
    category: 'BW – BW/4HANA',
    sNote: '2381257',
    pattern: /\b(BEX_MIGRATE|QUERY_CONVERT|BEX_EXCEPTION|BEX_CONDITION|CUSTOM_STRUCT)\b/i,
    patternType: 'source',
    remediation: 'Evaluate BEx queries for BW/4HANA compatibility. Convert unsupported features to Analysis Office or SAC equivalents.',
  },

  // ── SAP Analytics Cloud (SAC) Integration ────────────────────
  {
    id: 'SIMPL-BW-018',
    title: 'SAP Analytics Cloud Live Connection',
    description: 'SAC live connection to S/4HANA embedded analytics allows real-time reporting without data replication. CDS analytical queries exposed as live data sources replace BW-based dashboards.',
    severity: 'medium',
    category: 'BW – SAC Integration',
    sNote: '2381257',
    pattern: /\b(SAC_LIVE|LIVE_CONNECT|SAC_S4|ANALYTICS_CLOUD)\b/i,
    patternType: 'source',
    remediation: 'Evaluate SAC live connection for operational reports. Configure InA service for CDS query exposure to SAC.',
  },
  {
    id: 'SIMPL-BW-019',
    title: 'SAC Import Connection for BW Data',
    description: 'SAC import connection enables scheduled data replication from BW/4HANA to SAC for planning, predictive, and blended analytics. BW queries serve as import data sources.',
    severity: 'medium',
    category: 'BW – SAC Integration',
    sNote: '2381257',
    pattern: /\b(SAC_IMPORT|SAC_SCHED|SAC_PLANNING|SAC_PREDICT)\b/i,
    patternType: 'source',
    remediation: 'Configure SAC import connections for BW/4HANA data sources. Set up scheduling for data replication.',
  },
  {
    id: 'SIMPL-BW-020',
    title: 'Analysis for Office (AfO) Migration to SAC',
    description: 'Analysis for Office (AfO) workbooks consuming BW queries should be evaluated for migration to SAC stories. Complex AfO features (design mode, custom formulas) may require redesign.',
    severity: 'low',
    category: 'BW – SAC Integration',
    sNote: '2381257',
    pattern: /\b(AFO_WORKBOOK|ANALYSIS_OFFICE|AFO_MIGRATE|AFO_FORMULA)\b/i,
    patternType: 'source',
    remediation: 'Evaluate AfO workbooks for SAC story migration. Identify complex features requiring redesign in SAC.',
  },

  // ── Embedded Analytics CDS Views ─────────────────────────────
  {
    id: 'SIMPL-BW-021',
    title: 'CDS Analytical Query Design',
    description: 'S/4HANA CDS analytical queries (annotation @Analytics.query: true) replace many BW queries for operational reporting. Custom CDS views must follow VDM naming conventions (I_, C_, P_ prefixes).',
    severity: 'medium',
    category: 'BW – Embedded Analytics',
    sNote: '2381257',
    pattern: /\b(CDS_ANALYTIC|ANALYTIC_QUERY|VDM_VIEW|I_GLACCOUNTLINE)\b|@Analytics[.]query/i,
    patternType: 'source',
    remediation: 'Identify BW queries replaceable by CDS analytical queries. Follow VDM naming conventions for custom CDS views.',
  },
  {
    id: 'SIMPL-BW-022',
    title: 'KPI Tile and Fiori Analytical Apps',
    description: 'S/4HANA Fiori analytical apps and KPI tiles consume CDS analytical queries directly. Migration from BW-based dashboards to Fiori analytical launchpad tiles requires CDS view preparation.',
    severity: 'medium',
    category: 'BW – Embedded Analytics',
    sNote: '2381257',
    pattern: /\b(KPI_TILE|FIORI_ANALYTIC|SMART_BUSINESS|SSB_KPI)\b/i,
    patternType: 'source',
    remediation: 'Configure Fiori KPI tiles consuming CDS views. Migrate dashboard content to Fiori analytical applications.',
  },

  // ── Real-Time Replication ────────────────────────────────────
  {
    id: 'SIMPL-BW-023',
    title: 'SLT-Based Real-Time Replication',
    description: 'SAP Landscape Transformation (SLT) real-time replication from S/4HANA to BW/4HANA must be reconfigured for changed table structures. Trigger-based replication on removed tables (BSEG, KONV) will fail.',
    severity: 'high',
    category: 'BW – Real-Time',
    sNote: '2381257',
    pattern: /\b(SLT_REPL|REAL_TIME_REPL|DMIS_REPL|TRIGGER_REPL)\b/i,
    patternType: 'source',
    remediation: 'Reconfigure SLT replication for S/4HANA table changes. Replace replication on removed tables with ACDOCA-based sourcing.',
  },
  {
    id: 'SIMPL-BW-024',
    title: 'ODP-Based Delta Extraction Framework',
    description: 'Operational Data Provisioning (ODP) replaces classic BW service API as the standard extraction framework. ODP sources include CDS views, ABAP extractors, and SLT-based replication.',
    severity: 'high',
    category: 'BW – Real-Time',
    sNote: '2381257',
    pattern: /\b(ODP_EXTRACT|ODP_SOURCE|ODP_DELTA|RODPS_REPL)\b/i,
    patternType: 'source',
    remediation: 'Migrate classic extraction to ODP framework. Configure ODP data sources for CDS-based and ABAP extractor-based extraction.',
  },

  // ── Data Warehouse Cloud Integration ─────────────────────────
  {
    id: 'SIMPL-BW-025',
    title: 'SAP Datasphere (Data Warehouse Cloud) Integration',
    description: 'SAP Datasphere (formerly DWC) provides cloud-based data warehousing with federation and replication from S/4HANA and BW/4HANA. Evaluate hybrid scenarios for analytics landscape simplification.',
    severity: 'medium',
    category: 'BW – Cloud Integration',
    sNote: '2381257',
    pattern: /\b(DWC_INT|DATASPHERE|DATA_WAREHOUSE_CLOUD|DWC_FEDERATE)\b/i,
    patternType: 'source',
    remediation: 'Evaluate SAP Datasphere for cloud analytics. Configure federation or replication connections from S/4HANA.',
  },
  {
    id: 'SIMPL-BW-026',
    title: 'BW Bridge for Datasphere',
    description: 'BW Bridge enables running BW/4HANA data models inside SAP Datasphere for customers migrating to cloud analytics. Existing BW objects can be transferred to BW Bridge spaces.',
    severity: 'low',
    category: 'BW – Cloud Integration',
    sNote: '2381257',
    pattern: /\b(BW_BRIDGE|DWC_BRIDGE|BRIDGE_SPACE|BW_CLOUD)\b/i,
    patternType: 'source',
    remediation: 'Evaluate BW Bridge for cloud migration of BW data models. Assess object compatibility for transfer to Datasphere.',
  },
  {
    id: 'SIMPL-BW-027',
    title: 'Open SQL and HANA Calculation View Migration',
    description: 'Custom HANA calculation views and native SQL-based reporting used alongside BW must be evaluated. S/4HANA table structure changes affect any native HANA views referencing removed or changed tables.',
    severity: 'high',
    category: 'BW – Data Model',
    sNote: '2381257',
    pattern: /\b(CALC_VIEW|HANA_VIEW|NATIVE_SQL|CV_REPORT|HANA_ANALYTIC)\b/i,
    patternType: 'source',
    remediation: 'Validate HANA calculation views against S/4HANA table changes. Migrate to CDS views where possible for upgrade stability.',
  },
  {
    id: 'SIMPL-BW-028',
    title: 'Process Chain and Data Flow Automation',
    description: 'BW process chains orchestrating extraction, transformation, and loading must be validated. Chains referencing deprecated InfoProviders, extractors, or transformation rules need reconfiguration for BW/4HANA.',
    severity: 'high',
    category: 'BW – Data Model',
    sNote: '2381257',
    pattern: /\b(PROCESS_CHAIN|RSPC|DATA_FLOW|ETL_CHAIN|CHAIN_MONITOR)\b/i,
    patternType: 'source',
    remediation: 'Validate process chains end-to-end. Update references to migrated InfoProviders and extractors in all chain steps.',
  },
];
