/**
 * Copyright 2024-2026 SEN Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
/**
 * Enhancement/Extensibility Simplification Rules
 *
 * Covers: User exits -> BAdIs, SMOD/CMOD, modification flags,
 * Enhancement Spot patterns, implicit enhancements, BTE,
 * classic vs new BAdIs, customer exits deprecation, USEREXIT_*,
 * enhancement spots and sections, modification browser (SE95),
 * custom transactions using removed tables, custom reports
 * using deprecated APIs, enhancement point framework,
 * key user extensibility, custom CDS views and extensibility.
 */

module.exports = [
  {
    id: 'SIMPL-ENH-001',
    category: 'Enhancements',
    severity: 'medium',
    title: 'User Exit usage (SMOD/CMOD)',
    description: 'User Exits via SMOD/CMOD are deprecated. BAdIs are the standard enhancement mechanism.',
    pattern: /\bUSEREXIT_|CUSTOMER-FUNCTION\b/i,
    patternType: 'source',
    remediation: 'Migrate to equivalent BAdI implementations.',
    simplificationId: 'S4TWL-ENH-001',
  },
  {
    id: 'SIMPL-ENH-002',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Modification of standard SAP objects',
    description: 'Direct modifications to standard objects require manual adjustment after each upgrade.',
    pattern: /^Y\d{3}|^ZXXX/i,
    patternType: 'objectName',
    remediation: 'Replace modifications with BAdI or Enhancement Spot implementations.',
    simplificationId: 'S4TWL-ENH-002',
  },
  {
    id: 'SIMPL-ENH-003',
    category: 'Enhancements',
    severity: 'medium',
    title: 'SMOD enhancement usage',
    description: 'SMOD-based enhancements are legacy. Migrate to new Enhancement Framework.',
    pattern: /\bSMOD\b/i,
    patternType: 'source',
    remediation: 'Replace SMOD enhancements with Enhancement Spots or BAdIs.',
    simplificationId: 'S4TWL-ENH-003',
  },
  {
    id: 'SIMPL-ENH-004',
    category: 'Enhancements',
    severity: 'medium',
    title: 'CMOD project enhancements',
    description: 'CMOD projects contain user exits that need migration to BAdIs.',
    pattern: /\bCMOD\b/i,
    patternType: 'source',
    remediation: 'Migrate CMOD enhancement projects to BAdI implementations.',
    simplificationId: 'S4TWL-ENH-004',
  },
  {
    id: 'SIMPL-ENH-005',
    category: 'Enhancements',
    severity: 'high',
    title: 'Modification flag in standard code',
    description: 'Modifications flagged by correction instructions need review after upgrade.',
    pattern: /\bmodification\s+flag|BEGIN\s+OF\s+INSERT\b/i,
    patternType: 'source',
    remediation: 'Remove modifications. Use Enhancement Spots or Key User Extensibility.',
    simplificationId: 'S4TWL-ENH-005',
  },
  {
    id: 'SIMPL-ENH-006',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Enhancement Spot pattern detected',
    description: 'Code uses Enhancement Spot framework, which is the correct approach.',
    pattern: /\bENHANCEMENT\s+\d+\b/i,
    patternType: 'source',
    remediation: 'Review Enhancement Spot implementations for S/4HANA compatibility.',
    simplificationId: 'S4TWL-ENH-006',
  },
  {
    id: 'SIMPL-ENH-007',
    category: 'Enhancements',
    severity: 'low',
    title: 'Implicit enhancement usage',
    description: 'Implicit enhancements may conflict with S/4HANA code changes.',
    pattern: /\bENHANCEMENT-POINT\b/i,
    patternType: 'source',
    remediation: 'Review implicit enhancements for conflicts with S/4HANA code.',
    simplificationId: 'S4TWL-ENH-007',
  },
  {
    id: 'SIMPL-ENH-008',
    category: 'Enhancements',
    severity: 'high',
    title: 'BTE (Business Transaction Events) usage',
    description: 'BTE interfaces may have changed event parameters in S/4HANA.',
    pattern: /\b(OPEN_FI_|BAPI_BTE_)\w+/i,
    patternType: 'source',
    remediation: 'Review BTE implementations for S/4HANA parameter changes.',
    simplificationId: 'S4TWL-ENH-008',
  },
  {
    id: 'SIMPL-ENH-009',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Classic BAdI (GET BADI) usage',
    description: 'Classic BAdIs (GET BADI/CALL BADI) should be reviewed for S/4HANA.',
    pattern: /\b(GET\s+BADI|CALL\s+BADI)\b/i,
    patternType: 'source',
    remediation: 'Review BAdI implementations for changed filter values or interfaces.',
    simplificationId: 'S4TWL-ENH-009',
  },
  // ── Rules 010–035: expanded coverage ──
  {
    id: 'SIMPL-ENH-010',
    category: 'Enhancements',
    severity: 'high',
    title: 'USEREXIT_* function module pattern',
    description: 'USEREXIT_* named function modules are the classic user exit pattern from SD, MM, and other modules. These are deprecated in favor of BAdIs in S/4HANA.',
    pattern: /\bUSEREXIT_\w+/i,
    patternType: 'source',
    remediation: 'Identify the replacement BAdI for each USEREXIT. Use transaction SE18 to find equivalent new BAdI definitions.',
    simplificationId: 'S4TWL-ENH-010',
  },
  {
    id: 'SIMPL-ENH-011',
    category: 'Enhancements',
    severity: 'high',
    title: 'Customer exit function modules (EXIT_*)',
    description: 'EXIT_* named function modules are customer exit implementations. These need migration to BAdI implementations in S/4HANA.',
    pattern: /\bEXIT_\w+_\d{3}\b/i,
    patternType: 'source',
    remediation: 'Replace EXIT_ function module implementations with equivalent BAdI. Map each exit to the corresponding BAdI definition.',
    simplificationId: 'S4TWL-ENH-011',
  },
  {
    id: 'SIMPL-ENH-012',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Enhancement Section (ENHANCEMENT-SECTION)',
    description: 'Enhancement sections define replaceable code blocks in standard programs. Review for compatibility with S/4HANA standard code changes.',
    pattern: /\bENHANCEMENT-SECTION\b/i,
    patternType: 'source',
    remediation: 'Review enhancement section implementations. The replaced standard code may have changed in S/4HANA.',
    simplificationId: 'S4TWL-ENH-012',
  },
  {
    id: 'SIMPL-ENH-013',
    category: 'Enhancements',
    severity: 'medium',
    title: 'END-ENHANCEMENT-SECTION pattern',
    description: 'End of enhancement section markers indicate replaced standard code blocks that must be validated against S/4HANA code.',
    pattern: /\bEND-ENHANCEMENT-SECTION\b/i,
    patternType: 'source',
    remediation: 'Verify the original standard code that was replaced still exists and has not been restructured in S/4HANA.',
    simplificationId: 'S4TWL-ENH-013',
  },
  {
    id: 'SIMPL-ENH-014',
    category: 'Enhancements',
    severity: 'high',
    title: 'Modification browser (SE95) adjustments needed',
    description: 'All modifications registered in SE95 must be reviewed. Modifications to removed or restructured objects will fail in S/4HANA.',
    pattern: /\bSE95\b|MODIFICATION_BROWSER/i,
    patternType: 'source',
    remediation: 'Run SE95 modification browser. Catalog all modifications and plan migration to BAdI or enhancement spots.',
    simplificationId: 'S4TWL-ENH-014',
  },
  {
    id: 'SIMPL-ENH-015',
    category: 'Enhancements',
    severity: 'high',
    title: 'Custom transactions referencing removed tables',
    description: 'Custom transactions (Z*/Y*) that reference removed or replaced tables (BSEG, BSID, BSIK, KONV, etc.) will fail or perform poorly.',
    pattern: /\b(CALL\s+TRANSACTION|LEAVE\s+TO\s+TRANSACTION)\s+['"]Z\w+['"]/i,
    patternType: 'source',
    remediation: 'Identify all custom transactions and review their underlying reports for removed table access. Migrate to CDS-based data access.',
    simplificationId: 'S4TWL-ENH-015',
  },
  {
    id: 'SIMPL-ENH-016',
    category: 'Enhancements',
    severity: 'high',
    title: 'Custom reports using deprecated FI APIs',
    description: 'Custom reports using deprecated financial APIs (FAGL_GET_LINE_ITEMS, FI_ITEMS_SELECT, etc.) need migration to ACDOCA-based access.',
    pattern: /\b(FAGL_GET_LINE_ITEMS|FI_ITEMS_SELECT|FI_DOCUMENT_READ|BAPI_GL_GETGLACCBALANCE)\b/i,
    patternType: 'source',
    remediation: 'Replace deprecated FI APIs with CDS views (I_JournalEntryItem, I_GLAccountLineItem) or ACDOCA direct access.',
    simplificationId: 'S4TWL-ENH-016',
  },
  {
    id: 'SIMPL-ENH-017',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Custom reports using deprecated MM APIs',
    description: 'Custom reports using deprecated MM function modules (ME_READ_PO_FOR_PRINTING, BAPI_PO_GETDETAIL, etc.) need review.',
    pattern: /\b(ME_READ_PO_FOR_PRINTING|BAPI_PO_GETDETAIL|BAPI_PO_GETITEMS|MM_READ_MATERIAL_DOC)\b/i,
    patternType: 'source',
    remediation: 'Replace with API_PURCHASEORDER_PROCESS_SRV or CDS views I_PurchaseOrder, I_PurchaseOrderItem.',
    simplificationId: 'S4TWL-ENH-017',
  },
  {
    id: 'SIMPL-ENH-018',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Custom reports using deprecated SD APIs',
    description: 'Custom reports using deprecated SD function modules (SD_SALESDOCUMENT_READ, BAPI_SALESORDER_GETLIST, etc.) need review.',
    pattern: /\b(SD_SALESDOCUMENT_READ|BAPI_SALESORDER_GETLIST|RV_ORDER_FLOW_INFORMATION)\b/i,
    patternType: 'source',
    remediation: 'Replace with API_SALES_ORDER_SRV or CDS views I_SalesOrder, I_SalesOrderItem.',
    simplificationId: 'S4TWL-ENH-018',
  },
  {
    id: 'SIMPL-ENH-019',
    category: 'Enhancements',
    severity: 'high',
    title: 'New BAdI (class-based) implementation',
    description: 'New-style BAdIs use class-based implementation (SE18/SE19). These are the target enhancement mechanism but must be reviewed for filter value changes.',
    pattern: /\bCL_EXITHANDLER\s*=>\s*GET_INSTANCE\b/i,
    patternType: 'source',
    remediation: 'Review new BAdI implementations via SE19. Verify filter values and interface signatures against S/4HANA definitions.',
    simplificationId: 'S4TWL-ENH-019',
  },
  {
    id: 'SIMPL-ENH-020',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Classic BAdI definition (SE18 old style)',
    description: 'Classic BAdI definitions (pre-Enhancement Framework) may have been migrated to new BAdIs in S/4HANA. Implementation classes need review.',
    pattern: /\bCL_BADI_|IF_EX_\w+/i,
    patternType: 'source',
    remediation: 'Check if classic BAdI has been migrated to new BAdI in S/4HANA. Update implementation class references accordingly.',
    simplificationId: 'S4TWL-ENH-020',
  },
  {
    id: 'SIMPL-ENH-021',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Key User Extensibility (custom fields)',
    description: 'S/4HANA Cloud and on-premise support Key User Extensibility for custom fields, custom logic, and custom CDS views without ABAP development.',
    pattern: /\bCUSTOM_FIELD|CF_FIELD_|INCL_EEW_\w+/i,
    patternType: 'source',
    remediation: 'Evaluate Key User Extensibility for simple field extensions. Use Custom Fields and Logic app in Fiori Launchpad.',
    simplificationId: 'S4TWL-ENH-021',
  },
  {
    id: 'SIMPL-ENH-022',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Custom CDS view extensibility',
    description: 'Custom CDS views (Z*/Y*) that extend standard CDS views must use EXTEND VIEW syntax for forward compatibility.',
    pattern: /\b(EXTEND\s+VIEW|@AbapCatalog\.sqlViewAppendName)\b/i,
    patternType: 'source',
    remediation: 'Use CDS view extensions (EXTEND VIEW) instead of custom copies. Ensure annotations are compatible with S/4HANA.',
    simplificationId: 'S4TWL-ENH-022',
  },
  {
    id: 'SIMPL-ENH-023',
    category: 'Enhancements',
    severity: 'high',
    title: 'Custom CDS views on removed tables',
    description: 'Custom CDS views that reference removed or replaced tables (BSEG, KONV, GLT0, etc.) will either fail or use slow compatibility views.',
    pattern: /\bdefine\s+view\b.*\b(BSEG|BSID|BSIK|BSAD|BSAK|KONV|KONP|GLT0|FAGLFLEXT|COBK|COEP)\b/i,
    patternType: 'source',
    remediation: 'Rewrite custom CDS views to use ACDOCA, PRCD_ELEMENTS, or standard S/4HANA CDS views as data sources.',
    simplificationId: 'S4TWL-ENH-023',
  },
  {
    id: 'SIMPL-ENH-024',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Enhancement point (ENHANCEMENT-POINT) usage',
    description: 'Enhancement points provide insertion points in standard code. Implementations must be reviewed for S/4HANA code changes at the insertion point.',
    pattern: /\bENHANCEMENT-POINT\s+\w+\b/i,
    patternType: 'source',
    remediation: 'Review all enhancement point implementations. Verify the surrounding standard code context has not changed in S/4HANA.',
    simplificationId: 'S4TWL-ENH-024',
  },
  {
    id: 'SIMPL-ENH-025',
    category: 'Enhancements',
    severity: 'medium',
    title: 'ABAP append structures on changed tables',
    description: 'Append structures (CI_ includes) on tables that are removed or restructured in S/4HANA (BSEG, KONV, etc.) will not work.',
    pattern: /\b(CI_BSEG|CI_KONV|CI_COEP|CI_COBK|CI_BSID|CI_BSIK)\b/i,
    patternType: 'source',
    remediation: 'Migrate append structures to the replacement tables. For BSEG use ACDOCA extension. For KONV use PRCD_ELEMENTS extension.',
    simplificationId: 'S4TWL-ENH-025',
  },
  {
    id: 'SIMPL-ENH-026',
    category: 'Enhancements',
    severity: 'high',
    title: 'Custom includes in standard structures',
    description: 'Custom includes (ZZ*, YY*) in standard SAP structures may conflict with S/4HANA structural changes.',
    pattern: /\bINCLUDE\s+(ZZ|YY)\w+/i,
    patternType: 'source',
    remediation: 'Review all custom includes in standard structures. Ensure no field name conflicts with new S/4HANA fields.',
    simplificationId: 'S4TWL-ENH-026',
  },
  {
    id: 'SIMPL-ENH-027',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Screen exits and subscreens',
    description: 'Screen exits (CALL SUBSCREEN) in customer function groups may reference screens that have changed in S/4HANA or been replaced by Fiori.',
    pattern: /\bCALL\s+SUBSCREEN\b.*\bZ\w+|CALL\s+SUBSCREEN\b.*\bY\w+/i,
    patternType: 'source',
    remediation: 'Review screen exits for compatibility. Consider migrating custom screen logic to Fiori UI extensions.',
    simplificationId: 'S4TWL-ENH-027',
  },
  {
    id: 'SIMPL-ENH-028',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Menu exits usage',
    description: 'Menu exits (CALL CUSTOMER-FUNCTION for GUI status) add custom menu entries. Some base transactions are removed in S/4HANA.',
    pattern: /\bCALL\s+CUSTOMER-FUNCTION\b/i,
    patternType: 'source',
    remediation: 'Review menu exits. If the base transaction is removed, migrate to Fiori app extension or custom Fiori tile.',
    simplificationId: 'S4TWL-ENH-028',
  },
  {
    id: 'SIMPL-ENH-029',
    category: 'Enhancements',
    severity: 'high',
    title: 'Substitution and validation rules (GGB1/GGB4)',
    description: 'FI substitution (GGB1) and validation (GGB4) rules may reference fields that have moved to ACDOCA or been removed.',
    pattern: /\b(GGB1|GGB4|OBBH|OB28|GCX2)\b/i,
    patternType: 'source',
    remediation: 'Review all substitution and validation rules. Verify field references against S/4HANA ACDOCA structure.',
    simplificationId: 'S4TWL-ENH-029',
  },
  {
    id: 'SIMPL-ENH-030',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Custom workflow tasks referencing removed objects',
    description: 'Custom workflow tasks (TS*) that reference removed transactions, BAPIs, or function modules will fail in S/4HANA.',
    pattern: /\b(SWO1|PFTC|TS\d{8})\b/i,
    patternType: 'source',
    remediation: 'Review custom workflow tasks and object types. Migrate references to S/4HANA compatible APIs and transactions.',
    simplificationId: 'S4TWL-ENH-030',
  },
  {
    id: 'SIMPL-ENH-031',
    category: 'Enhancements',
    severity: 'high',
    title: 'Custom RFC function modules using removed tables',
    description: 'Custom RFC-enabled function modules (Z_RFC_*, Y_RFC_*) that access removed tables will fail when called by external systems.',
    pattern: /\bFUNCTION\s+['"]?(Z_RFC_|Y_RFC_)\w+/i,
    patternType: 'source',
    remediation: 'Review all custom RFC function modules for removed table access. Migrate to CDS-based OData services where possible.',
    simplificationId: 'S4TWL-ENH-031',
  },
  {
    id: 'SIMPL-ENH-032',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Custom IDocs using deprecated segments',
    description: 'Custom IDoc types and segments that reference deprecated fields or structures need review for S/4HANA compatibility.',
    pattern: /\b(IDOC_INPUT_|IDOC_OUTPUT_|SEGMENTS\s+Z\w+|SEGMENT\s+TYPE\s+Z\w+)\b/i,
    patternType: 'source',
    remediation: 'Review custom IDoc segments for deprecated field references. Update segment definitions for S/4HANA data model.',
    simplificationId: 'S4TWL-ENH-032',
  },
  {
    id: 'SIMPL-ENH-033',
    category: 'Enhancements',
    severity: 'medium',
    title: 'In-App Extensibility (S/4HANA Cloud model)',
    description: 'S/4HANA supports In-App Extensibility for custom fields, custom logic, and custom analytical queries without classic ABAP.',
    pattern: /\b(EXTENSIBILITY|IN_APP_FEATURES|CUSTOM_ENTITY)\b/i,
    patternType: 'source',
    remediation: 'Evaluate In-App Extensibility for cloud-ready enhancements. Use Custom Fields, Custom Logic, and Custom CDS views.',
    simplificationId: 'S4TWL-ENH-033',
  },
  {
    id: 'SIMPL-ENH-034',
    category: 'Enhancements',
    severity: 'low',
    title: 'Side-by-side extensibility via SAP BTP',
    description: 'Complex extensions can be implemented as side-by-side applications on SAP BTP, keeping the S/4HANA core clean.',
    pattern: /\b(BTP_|SIDE_BY_SIDE|CAP_APPLICATION|RAP_)\w*/i,
    patternType: 'source',
    remediation: 'Consider side-by-side extensibility on SAP BTP for complex custom applications. Use RAP (ABAP RESTful Application Programming) for on-stack extensions.',
    simplificationId: 'S4TWL-ENH-034',
  },
  {
    id: 'SIMPL-ENH-035',
    category: 'Enhancements',
    severity: 'high',
    title: 'Custom programs using obsolete ABAP statements',
    description: 'Custom programs using obsolete ABAP statements (MOVE-CORRESPONDING ... KEEPING TARGET LINES on internal tables with header, etc.) flagged in S/4HANA strict mode.',
    pattern: /\b(OCCURS\s+\d+|TABLES\s+\w+\s+STRUCTURE|FIELD-GROUPS|EXTRACT\s+|HEADER\s+LINE)\b/i,
    patternType: 'source',
    remediation: 'Replace obsolete ABAP statements with modern equivalents. Use ABAP cleaner tool for automated refactoring.',
    simplificationId: 'S4TWL-ENH-035',
  },
];
