/**
 * Enhancement/Extensibility Simplification Rules
 *
 * Covers: User exits → BAdIs, SMOD/CMOD, modification flags,
 * Enhancement Spot patterns, implicit enhancements.
 */

module.exports = [
  {
    id: 'SIMPL-ENH-001',
    category: 'Enhancements',
    severity: 'medium',
    title: 'User Exit usage (SMOD/CMOD)',
    description: 'User Exits via SMOD/CMOD are deprecated. BAdIs are the standard enhancement mechanism.',
    pattern: /\bUSEREXIT_|CUSTOMER-FUNCTION\b/i,
    patternType: 'source',
    remediation: 'Migrate to equivalent BAdI implementations.',
    simplificationId: 'S4TWL-ENH-001',
  },
  {
    id: 'SIMPL-ENH-002',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Modification of standard SAP objects',
    description: 'Direct modifications to standard objects require manual adjustment after each upgrade.',
    pattern: /^Y\d{3}|^ZXXX/i,
    patternType: 'objectName',
    remediation: 'Replace modifications with BAdI or Enhancement Spot implementations.',
    simplificationId: 'S4TWL-ENH-002',
  },
  {
    id: 'SIMPL-ENH-003',
    category: 'Enhancements',
    severity: 'medium',
    title: 'SMOD enhancement usage',
    description: 'SMOD-based enhancements are legacy. Migrate to new Enhancement Framework.',
    pattern: /\bSMOD\b/i,
    patternType: 'source',
    remediation: 'Replace SMOD enhancements with Enhancement Spots or BAdIs.',
    simplificationId: 'S4TWL-ENH-003',
  },
  {
    id: 'SIMPL-ENH-004',
    category: 'Enhancements',
    severity: 'medium',
    title: 'CMOD project enhancements',
    description: 'CMOD projects contain user exits that need migration to BAdIs.',
    pattern: /\bCMOD\b/i,
    patternType: 'source',
    remediation: 'Migrate CMOD enhancement projects to BAdI implementations.',
    simplificationId: 'S4TWL-ENH-004',
  },
  {
    id: 'SIMPL-ENH-005',
    category: 'Enhancements',
    severity: 'high',
    title: 'Modification flag in standard code',
    description: 'Modifications flagged by correction instructions need review after upgrade.',
    pattern: /\bmodification\s+flag|BEGIN\s+OF\s+INSERT\b/i,
    patternType: 'source',
    remediation: 'Remove modifications. Use Enhancement Spots or Key User Extensibility.',
    simplificationId: 'S4TWL-ENH-005',
  },
  {
    id: 'SIMPL-ENH-006',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Enhancement Spot pattern detected',
    description: 'Code uses Enhancement Spot framework, which is the correct approach.',
    pattern: /\bENHANCEMENT\s+\d+\b/i,
    patternType: 'source',
    remediation: 'Review Enhancement Spot implementations for S/4HANA compatibility.',
    simplificationId: 'S4TWL-ENH-006',
  },
  {
    id: 'SIMPL-ENH-007',
    category: 'Enhancements',
    severity: 'low',
    title: 'Implicit enhancement usage',
    description: 'Implicit enhancements may conflict with S/4HANA code changes.',
    pattern: /\bENHANCEMENT-POINT\b/i,
    patternType: 'source',
    remediation: 'Review implicit enhancements for conflicts with S/4HANA code.',
    simplificationId: 'S4TWL-ENH-007',
  },
  {
    id: 'SIMPL-ENH-008',
    category: 'Enhancements',
    severity: 'high',
    title: 'BTE (Business Transaction Events) usage',
    description: 'BTE interfaces may have changed event parameters in S/4HANA.',
    pattern: /\b(OPEN_FI_|BAPI_BTE_)\w+/i,
    patternType: 'source',
    remediation: 'Review BTE implementations for S/4HANA parameter changes.',
    simplificationId: 'S4TWL-ENH-008',
  },
  {
    id: 'SIMPL-ENH-009',
    category: 'Enhancements',
    severity: 'medium',
    title: 'Classic BAdI (GET BADI) usage',
    description: 'Classic BAdIs (GET BADI/CALL BADI) should be reviewed for S/4HANA.',
    pattern: /\b(GET\s+BADI|CALL\s+BADI)\b/i,
    patternType: 'source',
    remediation: 'Review BAdI implementations for changed filter values or interfaces.',
    simplificationId: 'S4TWL-ENH-009',
  },
];
