/**
 * Copyright 2024-2026 SEN Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
/**
 * Finance (FI) Simplification Rules
 *
 * Covers: New GL (ACDOCA), Asset Accounting, AP, AR, Bank Accounting,
 * Tax, Closing, and Financial Reporting changes in S/4HANA.
 */

module.exports = [
  // ── New GL / Universal Journal ──────────────────────────────
  {
    id: 'SIMPL-FI-001',
    category: 'Finance - New GL',
    severity: 'critical',
    title: 'BSEG direct access removed',
    description: 'Table BSEG is replaced by ACDOCA (Universal Journal) in S/4HANA. Direct SELECT on BSEG will fail or return incomplete data.',
    pattern: /\bBSEG\b/i,
    patternType: 'source',
    remediation: 'Replace BSEG access with ACDOCA or CDS views I_JournalEntry / I_JournalEntryItem.',
    simplificationId: 'S4TWL-FI-001',
  },
  {
    id: 'SIMPL-FI-002',
    category: 'Finance - New GL',
    severity: 'critical',
    title: 'Customer/Vendor line item tables removed',
    description: 'Tables BSID, BSIK, BSAD, BSAK (open/cleared items) are removed. Data consolidated in ACDOCA.',
    pattern: /\b(BSID|BSIK|BSAD|BSAK)\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with appropriate filters or CDS views I_OperationalAcctgDocItem.',
    simplificationId: 'S4TWL-FI-002',
  },
  {
    id: 'SIMPL-FI-003',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'GL line item tables removed',
    description: 'Tables BSIS, BSAS (GL open/cleared items) are removed in S/4HANA.',
    pattern: /\b(BSIS|BSAS)\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with GL account filters or CDS views.',
    simplificationId: 'S4TWL-FI-003',
  },
  {
    id: 'SIMPL-FI-004',
    category: 'Finance - New GL',
    severity: 'critical',
    title: 'BKPF header table restructured',
    description: 'BKPF is restructured in S/4HANA. Fields may be moved or removed. Direct access should use CDS views.',
    pattern: /\bSELECT\s+.*\bFROM\s+BKPF\b/i,
    patternType: 'source',
    remediation: 'Use CDS view I_JournalEntry for document headers.',
    simplificationId: 'S4TWL-FI-004',
  },
  {
    id: 'SIMPL-FI-005',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'GLT0 totals table removed',
    description: 'GLT0 (GL account balance) is removed. Totals are calculated from ACDOCA.',
    pattern: /\bGLT0\b/i,
    patternType: 'source',
    remediation: 'Use CDS view I_GLAccountBalance or calculate from ACDOCA.',
    simplificationId: 'S4TWL-FI-005',
  },
  {
    id: 'SIMPL-FI-006',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'FAGLFLEXA table removed',
    description: 'FAGLFLEXA (New GL line items) is replaced by ACDOCA.',
    pattern: /\bFAGLFLEXA\b/i,
    patternType: 'source',
    remediation: 'Replace with ACDOCA or CDS view I_JournalEntryItem.',
    simplificationId: 'S4TWL-FI-006',
  },
  {
    id: 'SIMPL-FI-007',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'FAGLFLEXT totals table removed',
    description: 'FAGLFLEXT (New GL totals) removed. Totals from ACDOCA aggregation.',
    pattern: /\bFAGLFLEXT\b/i,
    patternType: 'source',
    remediation: 'Use CDS view I_GLAccountLineItem or aggregate from ACDOCA.',
    simplificationId: 'S4TWL-FI-007',
  },
  {
    id: 'SIMPL-FI-008',
    category: 'Finance - New GL',
    severity: 'medium',
    title: 'Special ledger tables (GLT*) removed',
    description: 'Special ledger tables (GLT1, GLT2, etc.) are removed. Use ACDOCA ledger concept.',
    pattern: /\bGLT[1-9]\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with ledger field (RLDNR) for multi-ledger reporting.',
    simplificationId: 'S4TWL-FI-008',
  },
  {
    id: 'SIMPL-FI-009',
    category: 'Finance - New GL',
    severity: 'medium',
    title: 'Document splitting config changed',
    description: 'Document splitting rules are simplified. Classic splitting rules may not apply.',
    pattern: /\b(FAGL_SPLINFO|FAGL_SPLIT_|BSEG_ADD)\b/i,
    patternType: 'source',
    remediation: 'Review document splitting configuration. Use S/4HANA document splitting.',
    simplificationId: 'S4TWL-FI-009',
  },
  {
    id: 'SIMPL-FI-010',
    category: 'Finance - New GL',
    severity: 'medium',
    title: 'BAPI_ACC_DOCUMENT_POST changes',
    description: 'BAPI_ACC_DOCUMENT_POST has new mandatory fields in S/4HANA.',
    pattern: /\bBAPI_ACC_DOCUMENT_POST\b/i,
    patternType: 'source',
    remediation: 'Review BAPI parameters. Add EXTENSION1/EXTENSION2 structures for new fields.',
    simplificationId: 'S4TWL-FI-010',
  },

  // ── Asset Accounting ────────────────────────────────────────
  {
    id: 'SIMPL-FI-011',
    category: 'Finance - Asset Accounting',
    severity: 'critical',
    title: 'Classic asset tables ANLP/ANLC removed',
    description: 'ANLP (periodic values), ANLC (cumulated values) are removed. New AA uses ACDOCA.',
    pattern: /\b(ANLP|ANLC)\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA for asset values or CDS views I_FixedAssetBalance*.',
    simplificationId: 'S4TWL-FI-AA-001',
  },
  {
    id: 'SIMPL-FI-012',
    category: 'Finance - Asset Accounting',
    severity: 'high',
    title: 'ANLB depreciation areas changed',
    description: 'ANLB structure changed. Depreciation areas are now linked to ledgers.',
    pattern: /\bANLB\b/i,
    patternType: 'source',
    remediation: 'Review depreciation area to ledger mapping. Use CDS views.',
    simplificationId: 'S4TWL-FI-AA-002',
  },
  {
    id: 'SIMPL-FI-013',
    category: 'Finance - Asset Accounting',
    severity: 'high',
    title: 'Asset BAPIs deprecated',
    description: 'BAPI_ASSET_POSTCAP, BAPI_ASSET_RETIREMENT and others changed in new AA.',
    pattern: /\bBAPI_ASSET_(POSTCAP|RETIREMENT|ACQUISITION|TRANSFER)\b/i,
    patternType: 'source',
    remediation: 'Use API_FIXEDASSET or reviewed BAPI interfaces for new Asset Accounting.',
    simplificationId: 'S4TWL-FI-AA-003',
  },
  {
    id: 'SIMPL-FI-014',
    category: 'Finance - Asset Accounting',
    severity: 'medium',
    title: 'ANLA asset master changes',
    description: 'ANLA table structure has new fields for new Asset Accounting.',
    pattern: /\bANLA\b(?!.*CDS)/i,
    patternType: 'source',
    remediation: 'Review ANLA field usage. Consider CDS view I_FixedAsset.',
    simplificationId: 'S4TWL-FI-AA-004',
  },

  // ── Accounts Payable ───────────────────────────────────────
  {
    id: 'SIMPL-FI-015',
    category: 'Finance - AP',
    severity: 'high',
    title: 'Payment program RFFOUS_T changes',
    description: 'Classic payment program RFFOUS_T is replaced by payment medium workbench.',
    pattern: /\bRFFOUS_T\b/i,
    patternType: 'source',
    remediation: 'Migrate to Payment Medium Workbench (PMW) or Payment Factory.',
    simplificationId: 'S4TWL-FI-AP-001',
  },
  {
    id: 'SIMPL-FI-016',
    category: 'Finance - AP',
    severity: 'medium',
    title: 'REGUH/REGUP payment tables changed',
    description: 'Payment run tables REGUH (header) and REGUP (items) are restructured.',
    pattern: /\b(REGUH|REGUP)\b/i,
    patternType: 'source',
    remediation: 'Use CDS views for payment document access.',
    simplificationId: 'S4TWL-FI-AP-002',
  },
  {
    id: 'SIMPL-FI-017',
    category: 'Finance - AP',
    severity: 'medium',
    title: 'Vendor open items BSIK removed',
    description: 'BSIK (vendor open items) replaced by ACDOCA filtering.',
    pattern: /\bBSIK\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with vendor account type filter.',
    simplificationId: 'S4TWL-FI-AP-003',
  },

  // ── Accounts Receivable ────────────────────────────────────
  {
    id: 'SIMPL-FI-018',
    category: 'Finance - AR',
    severity: 'medium',
    title: 'Dispute management changes',
    description: 'Classic dispute management (UDM_DISPUTE) replaced by FSCM dispute management.',
    pattern: /\b(UDM_DISPUTE|FDM_CUST)\b/i,
    patternType: 'source',
    remediation: 'Migrate to FSCM Dispute Management.',
    simplificationId: 'S4TWL-FI-AR-001',
  },
  {
    id: 'SIMPL-FI-019',
    category: 'Finance - AR',
    severity: 'medium',
    title: 'Customer open items BSID removed',
    description: 'BSID (customer open items) replaced by ACDOCA filtering.',
    pattern: /\bBSID\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with customer account type filter.',
    simplificationId: 'S4TWL-FI-AR-002',
  },

  // ── Bank Accounting ────────────────────────────────────────
  {
    id: 'SIMPL-FI-020',
    category: 'Finance - Bank',
    severity: 'medium',
    title: 'Electronic bank statement changes',
    description: 'FEBEP/FEBKO tables restructured. Advanced Payment Management replaces classic bank statements.',
    pattern: /\b(FEBEP|FEBKO|FEBA)\b/i,
    patternType: 'source',
    remediation: 'Review bank statement processing. Consider Advanced Payment Management.',
    simplificationId: 'S4TWL-FI-BANK-001',
  },

  // ── Tax ────────────────────────────────────────────────────
  {
    id: 'SIMPL-FI-021',
    category: 'Finance - Tax',
    severity: 'medium',
    title: 'Tax reporting changes',
    description: 'Tax reporting tables (e.g., BSET) are removed. Tax data in ACDOCA.',
    pattern: /\bBSET\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA tax fields or CDS views for tax reporting.',
    simplificationId: 'S4TWL-FI-TAX-001',
  },
  {
    id: 'SIMPL-FI-022',
    category: 'Finance - Tax',
    severity: 'low',
    title: 'Withholding tax table changes',
    description: 'WITH_ITEM table restructured in S/4HANA.',
    pattern: /\bWITH_ITEM\b/i,
    patternType: 'source',
    remediation: 'Review withholding tax access patterns.',
    simplificationId: 'S4TWL-FI-TAX-002',
  },

  // ── Closing ────────────────────────────────────────────────
  {
    id: 'SIMPL-FI-023',
    category: 'Finance - Closing',
    severity: 'medium',
    title: 'Foreign currency valuation changes',
    description: 'FAGL_FC_VALUATION replaces classic SAPF100. Valuation results in ACDOCA.',
    pattern: /\bSAPF100\b/i,
    patternType: 'source',
    remediation: 'Use FAGL_FC_VALUATION or Financial Closing cockpit.',
    simplificationId: 'S4TWL-FI-CLOSE-001',
  },
  {
    id: 'SIMPL-FI-024',
    category: 'Finance - Closing',
    severity: 'medium',
    title: 'GR/IR clearing changes',
    description: 'Automatic GR/IR clearing (F.19) changed. WRX table removed.',
    pattern: /\bWRX\b/i,
    patternType: 'source',
    remediation: 'Use S/4HANA GR/IR clearing or MR11 changes.',
    simplificationId: 'S4TWL-FI-CLOSE-002',
  },

  // ── Financial Reporting ────────────────────────────────────
  {
    id: 'SIMPL-FI-025',
    category: 'Finance - Reporting',
    severity: 'high',
    title: 'Classic FI reports deprecated',
    description: 'Reports like FBL1N, FBL3N, FBL5N use compatibility views. Performance may degrade.',
    pattern: /\b(FBL1N|FBL3N|FBL5N|FAGLL03)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori apps (e.g., Manage Journal Entries) or analytical CDS views.',
    simplificationId: 'S4TWL-FI-RPT-001',
  },
  {
    id: 'SIMPL-FI-026',
    category: 'Finance - Reporting',
    severity: 'medium',
    title: 'Report Writer/Painter compatibility',
    description: 'Report Writer/Painter reports using removed tables will fail.',
    pattern: /\b(GR55|GRR[1-9])\b/i,
    patternType: 'source',
    remediation: 'Recreate reports using CDS-based analytical queries or SAC.',
    simplificationId: 'S4TWL-FI-RPT-002',
  },

  // ── Cost Element merge ─────────────────────────────────────
  {
    id: 'SIMPL-FI-027',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'Cost element tables CSKA/CSKB removed',
    description: 'Cost element master (CSKA, CSKB) removed. Cost elements merged into GL accounts.',
    pattern: /\b(CSKA|CSKB)\b/i,
    patternType: 'source',
    remediation: 'Use GL account master (SKA1/SKB1) or CDS view I_GLAccountInChartOfAccounts.',
    simplificationId: 'S4TWL-CO-001',
  },

  // ── Ledger Group changes ───────────────────────────────────
  {
    id: 'SIMPL-FI-028',
    category: 'Finance - New GL',
    severity: 'medium',
    title: 'Ledger group access changes',
    description: 'FINSC_LEDGER, FAGL_TLDGRP tables restructured for new ledger concept.',
    pattern: /\b(FINSC_LEDGER|FAGL_TLDGRP)\b/i,
    patternType: 'source',
    remediation: 'Use CDS views for ledger configuration access.',
    simplificationId: 'S4TWL-FI-LDG-001',
  },

  // ── Consolidation ──────────────────────────────────────────
  {
    id: 'SIMPL-FI-029',
    category: 'Finance - Consolidation',
    severity: 'high',
    title: 'Classic consolidation (EC-CS) removed',
    description: 'EC-CS consolidation tables (ECMCA, ECMCT) removed. Use Group Reporting.',
    pattern: /\b(ECMCA|ECMCT|EC_CS)\b/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Group Reporting or SAP Analytics Cloud.',
    simplificationId: 'S4TWL-FI-CONS-001',
  },

  // ── Cash Management ────────────────────────────────────────
  {
    id: 'SIMPL-FI-030',
    category: 'Finance - Cash Management',
    severity: 'high',
    title: 'Classic cash management replaced',
    description: 'Classic cash management (FDSR, liquidity forecast) replaced by S/4HANA Cash Management.',
    pattern: /\b(FDSR|FLQIT|FLQITEM)\b/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Cash Management based on Bank Account Management.',
    simplificationId: 'S4TWL-FI-CM-001',
  },

  // ══════════════════════════════════════════════════════════════
  // ── NEW RULES (031–080) ───────────────────────────────────────
  // ══════════════════════════════════════════════════════════════

  // ── New Asset Accounting (continued) ────────────────────────
  {
    id: 'SIMPL-FI-031',
    category: 'Finance - Asset Accounting',
    severity: 'critical',
    title: 'ANEK/ANEP asset document tables replaced by ACDOCA',
    description: 'Asset document header ANEK and line item ANEP are removed in new Asset Accounting. All asset postings are stored in ACDOCA.',
    pattern: /\b(ANEK|ANEP)\b/i,
    patternType: 'source',
    remediation: 'Replace ANEK/ANEP reads with ACDOCA filtered by asset-related fields or use CDS view I_FixedAssetPostingItem.',
    simplificationId: 'S4TWL-FI-AA-005',
    sNote: '2169891',
  },
  {
    id: 'SIMPL-FI-032',
    category: 'Finance - Asset Accounting',
    severity: 'critical',
    title: 'Parallel valuation mandatory in new Asset Accounting',
    description: 'New Asset Accounting requires depreciation areas to be mapped to ledgers for parallel valuation. The classic delta depreciation area approach is removed.',
    pattern: /\b(ANKA|T093_).*\b(DELTA|AFABER)\b/i,
    patternType: 'source',
    remediation: 'Map each depreciation area to a leading or non-leading ledger. Configure parallel valuation in ACDOCA via transaction AFAMA.',
    simplificationId: 'S4TWL-FI-AA-006',
    sNote: '2217543',
  },
  {
    id: 'SIMPL-FI-033',
    category: 'Finance - Asset Accounting',
    severity: 'high',
    title: 'Depreciation areas must post to ACDOCA ledger',
    description: 'All active depreciation areas must be assigned to a real-time posting ledger. Statistical depreciation areas posting only to CO are no longer supported without ledger assignment.',
    pattern: /\bT093B\b/i,
    patternType: 'source',
    remediation: 'Review T093B (depreciation area specifications) and assign each area to a ledger via transaction AFAMA. Use SAP Note 2220773 for migration guidance.',
    simplificationId: 'S4TWL-FI-AA-007',
    sNote: '2220773',
  },
  {
    id: 'SIMPL-FI-034',
    category: 'Finance - Asset Accounting',
    severity: 'high',
    title: 'Asset depreciation run AFAB changes for new AA',
    description: 'Transaction AFAB (depreciation run) behavior changed in new Asset Accounting. Depreciation posts directly to ACDOCA per ledger instead of batch summarization.',
    pattern: /\bAFAB\b/i,
    patternType: 'source',
    remediation: 'Review depreciation run scheduling. Use FAA_DEPRECIATION_POST or Fiori app Manage Fixed Asset Depreciation Runs.',
    simplificationId: 'S4TWL-FI-AA-008',
    sNote: '2237725',
  },
  {
    id: 'SIMPL-FI-035',
    category: 'Finance - Asset Accounting',
    severity: 'medium',
    title: 'ANKT asset text table restructured',
    description: 'ANKT (asset type text) and related customizing tables have structural changes in new Asset Accounting for S/4HANA.',
    pattern: /\b(ANKT|ANKA)\b/i,
    patternType: 'source',
    remediation: 'Use CDS views I_FixedAssetType or I_FixedAssetTypeName for asset type access.',
    simplificationId: 'S4TWL-FI-AA-009',
  },

  // ── Bank Accounting (continued) ─────────────────────────────
  {
    id: 'SIMPL-FI-036',
    category: 'Finance - Bank',
    severity: 'high',
    title: 'Bank Communication Management replaces classic DMEE',
    description: 'Classic DMEE (Data Medium Exchange Engine) tree definitions for payment files are replaced by Bank Communication Management (BCM) in S/4HANA.',
    pattern: /\b(DMEE|OBPM1|DMEE_TREE)\b/i,
    patternType: 'source',
    remediation: 'Migrate payment format trees to BCM. Use transaction BCM_CONFIG or Fiori app Manage Payment File Formats.',
    simplificationId: 'S4TWL-FI-BANK-002',
    sNote: '2196238',
  },
  {
    id: 'SIMPL-FI-037',
    category: 'Finance - Bank',
    severity: 'medium',
    title: 'Classic lockbox processing replaced',
    description: 'Classic lockbox transaction FLB2 and function module FI_LOCKBOX_IMPORT are replaced by Advanced Payment Management lockbox processing.',
    pattern: /\b(FLB2|FI_LOCKBOX_IMPORT|FLBP)\b/i,
    patternType: 'source',
    remediation: 'Migrate to Advanced Payment Management (APM) for lockbox processing. Use Fiori app Process Lockbox Files.',
    simplificationId: 'S4TWL-FI-BANK-003',
    sNote: '2476534',
  },
  {
    id: 'SIMPL-FI-038',
    category: 'Finance - Bank',
    severity: 'medium',
    title: 'Payment Medium Workbench format changes',
    description: 'Classic payment medium programs (RFFO*) are replaced by Payment Medium Workbench (PMW) format definitions. Country-specific payment programs are deprecated.',
    pattern: /\b(RFFO[A-Z]{2,4}|RFFOD__|RFFOE__|RFFOBR_U)\b/i,
    patternType: 'source',
    remediation: 'Migrate all classic payment medium programs to PMW formats via transaction OBPM. Use SAP Note 2198573 for country-specific mappings.',
    simplificationId: 'S4TWL-FI-BANK-004',
    sNote: '2198573',
  },
  {
    id: 'SIMPL-FI-039',
    category: 'Finance - Bank',
    severity: 'medium',
    title: 'Bank account master data BAM migration',
    description: 'House bank configuration (T012/T012K) is extended by Bank Account Management (BAM). Bank accounts must be maintained centrally in BAM.',
    pattern: /\b(T012K|T012\b|BNKA)\b/i,
    patternType: 'source',
    remediation: 'Migrate house bank accounts to Bank Account Management (BAM). Use Fiori app Manage Bank Accounts and transaction BAM_MIGRATE.',
    simplificationId: 'S4TWL-FI-BANK-005',
    sNote: '2425486',
  },

  // ── Tax (continued) ─────────────────────────────────────────
  {
    id: 'SIMPL-FI-040',
    category: 'Finance - Tax',
    severity: 'high',
    title: 'Tax code determination via condition technique mandatory',
    description: 'Classic tax code determination logic is replaced by condition-based tax code determination in S/4HANA. Hard-coded tax code assignments in custom code must be migrated.',
    pattern: /\b(TAXCODE_DETERMINE|FI_TAX_CODE_DETERMINE|J_1B_NFE_TAX)\b/i,
    patternType: 'source',
    remediation: 'Implement condition-based tax code determination. Configure access sequences via transaction OBYZ. Review SAP Note 2253541.',
    simplificationId: 'S4TWL-FI-TAX-003',
    sNote: '2253541',
  },
  {
    id: 'SIMPL-FI-041',
    category: 'Finance - Tax',
    severity: 'medium',
    title: 'Extended withholding tax configuration changes',
    description: 'Extended withholding tax tables (T059Z, T059P) are restructured. Function module WITHHOLDING_TAX_CALCULATE has parameter changes.',
    pattern: /\b(T059Z|T059P|WITHHOLDING_TAX_CALCULATE)\b/i,
    patternType: 'source',
    remediation: 'Review extended withholding tax configuration. Use CDS views for withholding tax reporting and update FM call parameters per SAP Note 2363186.',
    simplificationId: 'S4TWL-FI-TAX-004',
    sNote: '2363186',
  },
  {
    id: 'SIMPL-FI-042',
    category: 'Finance - Tax',
    severity: 'high',
    title: 'VAT reporting moved to ACDOCA-based extraction',
    description: 'Classic VAT return programs (RFUMSV00, RFUMSV25) are replaced by ACDOCA-based VAT reporting. Tax register tables are obsolete.',
    pattern: /\b(RFUMSV00|RFUMSV25|RFUMSV50)\b/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Advanced Compliance Reporting for VAT returns. Use Fiori app Run Tax Returns or CDS-based tax reporting.',
    simplificationId: 'S4TWL-FI-TAX-005',
    sNote: '2488653',
  },
  {
    id: 'SIMPL-FI-043',
    category: 'Finance - Tax',
    severity: 'medium',
    title: 'Country-specific tax transaction changes (Brazil J1B)',
    description: 'Brazil-specific tax transactions J1BTAX, J1BNFE, and related function modules have significant changes for nota fiscal processing in S/4HANA.',
    pattern: /\b(J1BTAX|J1BNFE|J_1B_NFE_CREATE|J_1BNFDOC)\b/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Document and Reporting Compliance (DRC) for Brazil. Review SAP Note 2709153 for J1B migration.',
    simplificationId: 'S4TWL-FI-TAX-006',
    sNote: '2709153',
  },
  {
    id: 'SIMPL-FI-044',
    category: 'Finance - Tax',
    severity: 'low',
    title: 'Tax jurisdiction code table T007A changes',
    description: 'Tax jurisdiction processing and table T007A have structural changes in S/4HANA. Custom tax determination exits may need adjustment.',
    pattern: /\b(T007A|T007V|TAX_JURISDICTION)\b/i,
    patternType: 'source',
    remediation: 'Review tax jurisdiction configuration. Adjust custom BADI implementations for tax code determination.',
    simplificationId: 'S4TWL-FI-TAX-007',
  },

  // ── Financial Closing (continued) ───────────────────────────
  {
    id: 'SIMPL-FI-045',
    category: 'Finance - Closing',
    severity: 'high',
    title: 'Fast Close cockpit replaces classic closing transactions',
    description: 'Classic period-end closing transactions (F101, AJAB, ASKB) are consolidated into the Financial Closing cockpit (FCLM_CLC) in S/4HANA.',
    pattern: /\b(FCLM_CLC|CLCTMPL|F101\b|CLOCOS)\b/i,
    patternType: 'source',
    remediation: 'Use the Financial Closing cockpit or Fiori app Manage Closing Tasks. Integrate with SAP S/4HANA Advanced Financial Closing.',
    simplificationId: 'S4TWL-FI-CLOSE-003',
    sNote: '2437280',
  },
  {
    id: 'SIMPL-FI-046',
    category: 'Finance - Closing',
    severity: 'high',
    title: 'Intercompany reconciliation changes',
    description: 'Classic intercompany reconciliation (transaction F.5F, report SAPF150) is replaced by Intercompany Matching and Reconciliation in S/4HANA.',
    pattern: /\b(SAPF150|ICR_MATCH|F\.5F)\b/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Intercompany Matching and Reconciliation. Use Fiori app Intercompany Reconciliation or transaction ICR_RECON.',
    simplificationId: 'S4TWL-FI-CLOSE-004',
    sNote: '2534578',
  },
  {
    id: 'SIMPL-FI-047',
    category: 'Finance - Closing',
    severity: 'medium',
    title: 'Reclassification program SAPF100V replaced',
    description: 'Classic reclassification program SAPF100V and sort key-based receivable/payable reclassification are replaced by FAGL_FC_TRANSLATION.',
    pattern: /\b(SAPF100V|SAPF101|FAGL_FC_TRANSLATION)\b/i,
    patternType: 'source',
    remediation: 'Use FAGL_FC_TRANSLATION for reclassification or Fiori app Run Foreign Currency Valuation.',
    simplificationId: 'S4TWL-FI-CLOSE-005',
  },
  {
    id: 'SIMPL-FI-048',
    category: 'Finance - Closing',
    severity: 'medium',
    title: 'Financial close automation task scheduling',
    description: 'Custom ABAP scheduling of closing tasks via SM36/SM37 job chains should be migrated to the Advanced Financial Closing orchestration framework.',
    pattern: /\b(CLCTMPL_DEF|FIN_CLOSE_|FCLM_TASK_PROCESS)\b/i,
    patternType: 'source',
    remediation: 'Migrate closing task orchestration to SAP Advanced Financial Closing. Use ODATA service API_FINANCIALCLOSE_TASK_SRV.',
    simplificationId: 'S4TWL-FI-CLOSE-006',
    sNote: '2612092',
  },

  // ── Cash Management (continued) ─────────────────────────────
  {
    id: 'SIMPL-FI-049',
    category: 'Finance - Cash Management',
    severity: 'high',
    title: 'Cash position tables FDSB/FDSA removed',
    description: 'Classic cash position tables FDSB (memo records), FDSA (G/L planning data) are replaced by new Cash Management flow objects stored in FLQCFLOW.',
    pattern: /\b(FDSB|FDSA)\b/i,
    patternType: 'source',
    remediation: 'Migrate to new Cash Management. Use FLQCFLOW for cash flow data and Fiori app Manage Cash Position.',
    simplificationId: 'S4TWL-FI-CM-002',
    sNote: '2370498',
  },
  {
    id: 'SIMPL-FI-050',
    category: 'Finance - Cash Management',
    severity: 'high',
    title: 'Liquidity forecast FLQCFLOW replaces FLQITEM',
    description: 'Classic liquidity forecast items (FLQITEM) are replaced by the central cash flow table FLQCFLOW in S/4HANA Cash Management.',
    pattern: /\b(FLQCFLOW|FLQC_FLOW_GET|FF_5)\b/i,
    patternType: 'source',
    remediation: 'Use FLQCFLOW for liquidity analysis. Configure cash flow derivation rules via Fiori app Configure Cash Flow Derivation.',
    simplificationId: 'S4TWL-FI-CM-003',
    sNote: '2491498',
  },
  {
    id: 'SIMPL-FI-051',
    category: 'Finance - Cash Management',
    severity: 'medium',
    title: 'Bank Account Management replaces T012/T012K maintenance',
    description: 'Central bank account management (BAM) replaces direct maintenance of house bank configuration tables T012/T012K. Planning levels are replaced by cash flow categories.',
    pattern: /\b(FCHI|FCHI_BANK_STMT|FF63)\b/i,
    patternType: 'source',
    remediation: 'Migrate to Bank Account Management (BAM). Use Fiori apps Manage Bank Accounts and Monitor Bank Account Balances.',
    simplificationId: 'S4TWL-FI-CM-004',
  },
  {
    id: 'SIMPL-FI-052',
    category: 'Finance - Cash Management',
    severity: 'medium',
    title: 'Cash concentration and pooling changes',
    description: 'Classic cash concentration (transaction FF72) and notional pooling are replaced by new Cash Management cash pooling functions.',
    pattern: /\b(FF72|FF73|FI_CASH_CONCENTRATION)\b/i,
    patternType: 'source',
    remediation: 'Use S/4HANA Cash Management cash pooling. Configure via Fiori app Manage Cash Pools.',
    simplificationId: 'S4TWL-FI-CM-005',
  },

  // ── Credit Management ───────────────────────────────────────
  {
    id: 'SIMPL-FI-053',
    category: 'Finance - Credit Management',
    severity: 'critical',
    title: 'Classic FI-AR-CR credit management replaced by UKMBP_CMS',
    description: 'Classic credit management (FI-AR-CR) with tables KNKK and transactions FD32/FD33 is replaced by SAP Credit Management (UKMBP_CMS/UKM_MAIN). Business partner integration is mandatory.',
    pattern: /\b(KNKK|FD32|FD33|FD24)\b/i,
    patternType: 'source',
    remediation: 'Migrate to SAP Credit Management (UKM). Use transaction UKM_MAIN or Fiori app Manage Credit Accounts. Map KNKK data to UKM_ACCOUNT.',
    simplificationId: 'S4TWL-FI-CR-001',
    sNote: '2333281',
  },
  {
    id: 'SIMPL-FI-054',
    category: 'Finance - Credit Management',
    severity: 'high',
    title: 'Credit exposure tables KNKK/S066 replaced',
    description: 'Classic credit exposure (S066, S067) and credit master KNKK are replaced by UKM_ACCOUNT and real-time credit exposure calculation from ACDOCA.',
    pattern: /\b(S066|S067|KNKK_CREDIT)\b/i,
    patternType: 'source',
    remediation: 'Use UKM_ACCOUNT for credit master data and ACDOCA-based real-time exposure. Configure credit segments via UKM_CUSTOMIZING.',
    simplificationId: 'S4TWL-FI-CR-002',
    sNote: '2333282',
  },
  {
    id: 'SIMPL-FI-055',
    category: 'Finance - Credit Management',
    severity: 'high',
    title: 'Credit management function modules deprecated',
    description: 'Classic credit management FMs (CREDIT_UPDATE, FI_CREDIT_MANAGEMENT_CHECK) are replaced by UKM BAdIs and credit rule engine.',
    pattern: /\b(CREDIT_UPDATE|FI_CREDIT_MANAGEMENT_CHECK|SD_CREDIT_CHECK)\b/i,
    patternType: 'source',
    remediation: 'Implement UKM credit check BAdIs (UKM_BADI_CHECK, UKM_BADI_SCORING). Use BP-based credit segment approach.',
    simplificationId: 'S4TWL-FI-CR-003',
  },

  // ── Document Changes ────────────────────────────────────────
  {
    id: 'SIMPL-FI-056',
    category: 'Finance - Document Changes',
    severity: 'critical',
    title: 'FI document splitting mandatory in S/4HANA',
    description: 'Document splitting is mandatory in S/4HANA. All FI documents are split by profit center and segment. Custom document posting logic must support splitting.',
    pattern: /\b(FAGL_SPLIT_ACTIVE|FAGL_GET_SPLIT_ACTIVE|OB62)\b/i,
    patternType: 'source',
    remediation: 'Ensure document splitting is activated (transaction FAGL_ACTIVATION). Review all custom posting logic for splitting compatibility.',
    simplificationId: 'S4TWL-FI-DOC-001',
    sNote: '2269324',
  },
  {
    id: 'SIMPL-FI-057',
    category: 'Finance - Document Changes',
    severity: 'high',
    title: 'Profit center derivation mandatory for all line items',
    description: 'Every ACDOCA line item must have a profit center. Classic postings without profit center derivation will fail in S/4HANA.',
    pattern: /\b(FAGL_DERIVE_PROFIT_CENTER|CEPCT|CEPC\b)\b/i,
    patternType: 'source',
    remediation: 'Configure profit center derivation rules. Ensure all account assignments include profit center via substitution or derivation strategy.',
    simplificationId: 'S4TWL-FI-DOC-002',
    sNote: '2296620',
  },
  {
    id: 'SIMPL-FI-058',
    category: 'Finance - Document Changes',
    severity: 'high',
    title: 'Segment reporting mandatory via document splitting',
    description: 'Segment field is mandatory for balance sheet accounts when document splitting is active. Classic postings without segment will cause splitting errors.',
    pattern: /\b(SEGMENT|FAGL_SEGM_DERIVE|SEGM_DERIVE)\b/i,
    patternType: 'source',
    remediation: 'Configure segment derivation. Assign segments to profit centers and ensure all master data has proper segment assignment.',
    simplificationId: 'S4TWL-FI-DOC-003',
  },
  {
    id: 'SIMPL-FI-059',
    category: 'Finance - Document Changes',
    severity: 'medium',
    title: 'FI document change rules tightened',
    description: 'S/4HANA restricts changes to posted FI documents. Table BKPF/BSEG modification via direct UPDATE is blocked by framework controls.',
    pattern: /\b(UPDATE\s+BKPF|UPDATE\s+BSEG|FB02)\b/i,
    patternType: 'source',
    remediation: 'Use BAPI_ACC_DOCUMENT_REV_POST for reversals. Use FB02-equivalent Fiori app Change Document for permitted header changes.',
    simplificationId: 'S4TWL-FI-DOC-004',
  },

  // ── Travel Management ───────────────────────────────────────
  {
    id: 'SIMPL-FI-060',
    category: 'Finance - Travel Management',
    severity: 'critical',
    title: 'Travel Management (FI-TV) removed from S/4HANA',
    description: 'Classic Travel Management (FI-TV) including transactions PR01, PR02, PR03, PR05 is completely removed. SAP Concur is the strategic replacement.',
    pattern: /\b(PR01|PR02|PR03|PR05|TRIP\b)\b/i,
    patternType: 'source',
    remediation: 'Migrate to SAP Concur for travel and expense management. Use Concur APIs for integration with S/4HANA.',
    simplificationId: 'S4TWL-FI-TV-001',
    sNote: '2603700',
  },
  {
    id: 'SIMPL-FI-061',
    category: 'Finance - Travel Management',
    severity: 'critical',
    title: 'TRIP table and travel expense structures removed',
    description: 'Travel expense tables TRIP, PTRV_HEAD, PTRV_PERIO, PTRV_SCOS are removed in S/4HANA 2020+. All travel data must be managed externally.',
    pattern: /\b(PTRV_HEAD|PTRV_PERIO|PTRV_SCOS|PTRV_DOC)\b/i,
    patternType: 'source',
    remediation: 'Remove all direct TRIP/PTRV* table access. Migrate to SAP Concur and use integration middleware for expense posting to FI.',
    simplificationId: 'S4TWL-FI-TV-002',
    sNote: '2603700',
  },
  {
    id: 'SIMPL-FI-062',
    category: 'Finance - Travel Management',
    severity: 'high',
    title: 'Travel planning function modules deprecated',
    description: 'Function modules TRIP_CREATE, TRIP_SAVE, TRIP_DELETE and related HR_TRIP* modules are removed along with Travel Management.',
    pattern: /\b(TRIP_CREATE|TRIP_SAVE|TRIP_DELETE|HR_TRIP_)\b/i,
    patternType: 'source',
    remediation: 'Replace with SAP Concur API calls. Use Concur Expense API v4 for expense report creation and submission.',
    simplificationId: 'S4TWL-FI-TV-003',
  },

  // ── Special GL ──────────────────────────────────────────────
  {
    id: 'SIMPL-FI-063',
    category: 'Finance - Special GL',
    severity: 'high',
    title: 'Special GL indicators restructured in S/4HANA',
    description: 'Special GL transactions (UMSKZ field) behavior changed. Down payment requests, guarantees, and bills of exchange use new account determination logic via ACDOCA.',
    pattern: /\b(UMSKZ|T074|BSEG_SPECIAL)\b/i,
    patternType: 'source',
    remediation: 'Review special GL indicator configuration in T074. Test down payments, guarantees, and BoE processing with new ACDOCA-based posting.',
    simplificationId: 'S4TWL-FI-SGL-001',
    sNote: '2323097',
  },
  {
    id: 'SIMPL-FI-064',
    category: 'Finance - Special GL',
    severity: 'high',
    title: 'Down payment processing changes (F-29/F-39)',
    description: 'Down payment posting (F-29) and clearing (F-39) are restructured. Down payment requests use noted items in ACDOCA with special GL indicator logic changes.',
    pattern: /\b(F-29|F-39|F-48|F-58|BAPI_ACC_DOCUMENT_POST.*UMSKZ)\b/i,
    patternType: 'source',
    remediation: 'Use Manage Down Payments Fiori app or revised BAPI_ACC_DOCUMENT_POST with correct EXTENSION2 for down payment type handling.',
    simplificationId: 'S4TWL-FI-SGL-002',
    sNote: '2434560',
  },
  {
    id: 'SIMPL-FI-065',
    category: 'Finance - Special GL',
    severity: 'medium',
    title: 'Bills of exchange processing deprecated',
    description: 'Bills of exchange (BoE) posting via transactions FBW1, FBW2 and related BoE receivable/payable processing is simplified. BSEC table is removed.',
    pattern: /\b(FBW1|FBW2|FBW3|FBW4|BSEC)\b/i,
    patternType: 'source',
    remediation: 'Review bills of exchange usage. Migrate to standard payment processing. BoE data migrated to ACDOCA special GL fields.',
    simplificationId: 'S4TWL-FI-SGL-003',
  },

  // ── Accounts Payable (continued) ────────────────────────────
  {
    id: 'SIMPL-FI-066',
    category: 'Finance - AP',
    severity: 'high',
    title: 'Evaluated Receipts Settlement (ERS) changes',
    description: 'ERS processing (transaction MRRL) and underlying function modules are changed. ERS now posts directly to ACDOCA and requires updated vendor master configuration.',
    pattern: /\b(MRRL|MR_ERS_|BAPI_INCOMINGINVOICE_CREATE.*ERS)\b/i,
    patternType: 'source',
    remediation: 'Review ERS configuration and vendor master ERS flags. Use Fiori app Settle Evaluated Receipts or updated MRRL transaction.',
    simplificationId: 'S4TWL-FI-AP-004',
    sNote: '2267247',
  },
  {
    id: 'SIMPL-FI-067',
    category: 'Finance - AP',
    severity: 'high',
    title: 'Automatic Payment Program (F110) configuration changes',
    description: 'F110 payment program requires PMW (Payment Medium Workbench) for all payment methods. Classic payment medium programs are no longer supported.',
    pattern: /\b(F110|RFFOUS__|RFFOAVIS_FPAYM|SAPFPAYM)\b/i,
    patternType: 'source',
    remediation: 'Migrate all payment methods to PMW format. Configure OBPM for each payment method and country. Review F110 variants.',
    simplificationId: 'S4TWL-FI-AP-005',
    sNote: '2198573',
  },
  {
    id: 'SIMPL-FI-068',
    category: 'Finance - AP',
    severity: 'medium',
    title: 'Vendor master LFB1/LFA1 replaced by Business Partner',
    description: 'Direct access to vendor master tables LFA1, LFB1, LFBK is replaced by Business Partner (BP) tables BUT000, BUT020. Customer-vendor integration (CVI) is mandatory.',
    pattern: /\b(LFA1|LFB1|LFBK|LFB5)\b/i,
    patternType: 'source',
    remediation: 'Use Business Partner CDS views I_Supplier or I_BusinessPartner. Access via BAPI_BUPA_FS_CREATE_FROM_DATA2 or API_BUSINESS_PARTNER.',
    simplificationId: 'S4TWL-FI-AP-006',
    sNote: '2265093',
  },

  // ── Accounts Receivable (continued) ─────────────────────────
  {
    id: 'SIMPL-FI-069',
    category: 'Finance - AR',
    severity: 'high',
    title: 'Dunning program changes (F150/SAPF150)',
    description: 'Classic dunning program F150 (SAPF150) is replaced by S/4HANA dunning with ACDOCA-based open item determination. Dunning history tables restructured.',
    pattern: /\b(F150\b|SAPF150|MHNK|MHND)\b/i,
    patternType: 'source',
    remediation: 'Review dunning configuration. Use Fiori app Manage Dunning Runs. Migrate dunning history from MHNK/MHND to new dunning framework.',
    simplificationId: 'S4TWL-FI-AR-003',
    sNote: '2438805',
  },
  {
    id: 'SIMPL-FI-070',
    category: 'Finance - AR',
    severity: 'medium',
    title: 'Dispute management FSCM integration mandatory',
    description: 'Classic dispute case management (UDM_DISPUTE, FDM_CUST008) is replaced by FSCM-integrated dispute management with workflow and Fiori apps.',
    pattern: /\b(FDM_CUST008|FDM_CREATE|UDM_DISPUTE_CREATE)\b/i,
    patternType: 'source',
    remediation: 'Migrate to FSCM Dispute Management. Use Fiori app Manage Dispute Cases and API_DISPUTECASE_SRV OData service.',
    simplificationId: 'S4TWL-FI-AR-004',
  },
  {
    id: 'SIMPL-FI-071',
    category: 'Finance - AR',
    severity: 'medium',
    title: 'Payment terms table T052 changes',
    description: 'Payment terms (T052) and installment plan configuration (T052S) have structural changes. Day limit and baseline date calculation logic is updated.',
    pattern: /\b(T052\b|T052S|PAYMENT_TERMS_READ)\b/i,
    patternType: 'source',
    remediation: 'Review payment terms configuration. Use CDS view I_PaymentTerms for reading payment term master data.',
    simplificationId: 'S4TWL-FI-AR-005',
  },
  {
    id: 'SIMPL-FI-072',
    category: 'Finance - AR',
    severity: 'medium',
    title: 'Customer master KNA1/KNB1 replaced by Business Partner',
    description: 'Direct access to customer master tables KNA1, KNB1, KNBK is replaced by Business Partner tables BUT000, BUT020. CVI synchronization is mandatory.',
    pattern: /\b(KNA1|KNB1|KNBK|KNB5)\b/i,
    patternType: 'source',
    remediation: 'Use Business Partner CDS views I_Customer or I_BusinessPartner. Access via API_BUSINESS_PARTNER OData service.',
    simplificationId: 'S4TWL-FI-AR-006',
    sNote: '2265093',
  },

  // ── Financial Reporting (continued) ─────────────────────────
  {
    id: 'SIMPL-FI-073',
    category: 'Finance - Reporting',
    severity: 'high',
    title: 'Financial statement versions (FSV) reporting changes',
    description: 'Classic financial statement version reporting (transaction F.01, RFBILA00) is replaced by CDS-based analytical reporting from ACDOCA.',
    pattern: /\b(RFBILA00|F\.01\b|FAGL_ACCOUNT_BALANCE)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Display Financial Statement or CDS view I_FinancialStatementItem. Maintain FSV via OB58 with ACDOCA compatibility.',
    simplificationId: 'S4TWL-FI-RPT-003',
    sNote: '2521779',
  },
  {
    id: 'SIMPL-FI-074',
    category: 'Finance - Reporting',
    severity: 'high',
    title: 'Drilldown reports (FGI*/FGS*) replaced by CDS views',
    description: 'Classic FI-SL drilldown reports (FGI0, FGI4, FGS0) and Report Painter library 0FL are deprecated. Use CDS-based analytical queries.',
    pattern: /\b(FGI0|FGI4|FGS0|FGI3|0FL_REPORT)\b/i,
    patternType: 'source',
    remediation: 'Recreate drilldown reports as CDS analytical queries. Use I_JournalEntryItemCube or I_GLAccountBalanceCube as data source.',
    simplificationId: 'S4TWL-FI-RPT-004',
  },
  {
    id: 'SIMPL-FI-075',
    category: 'Finance - Reporting',
    severity: 'medium',
    title: 'Classic balance audit trail S_ALR_87012172 deprecated',
    description: 'Classic balance audit trail report S_ALR_87012172 and related ALR reports use compatibility views with degraded performance.',
    pattern: /\b(S_ALR_87012172|S_ALR_87012277|S_ALR_87012082)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori analytical apps for balance audit trail. Use CDS view I_JournalEntryItem with appropriate filters for audit trail reporting.',
    simplificationId: 'S4TWL-FI-RPT-005',
  },

  // ── Currency ────────────────────────────────────────────────
  {
    id: 'SIMPL-FI-076',
    category: 'Finance - Currency',
    severity: 'critical',
    title: 'Multiple currencies in ACDOCA (up to 10)',
    description: 'ACDOCA supports up to 10 currency amounts per line item (HSL, WSL, KSL through OSL). Classic currency translations relying on separate table reads are obsolete.',
    pattern: /\b(CURRENCY_CONVERTING_FACTOR|READ_EXCHANGE_RATE|FC_VALUATION)\b/i,
    patternType: 'source',
    remediation: 'Access currency amounts directly from ACDOCA fields (HSL, WSL, KSL, etc.). Use CDS views with currency conversion for reporting.',
    simplificationId: 'S4TWL-FI-CUR-001',
    sNote: '2340562',
  },
  {
    id: 'SIMPL-FI-077',
    category: 'Finance - Currency',
    severity: 'high',
    title: 'TCURR/TCURX exchange rate table access changes',
    description: 'Exchange rate tables TCURR and TCURX are still used but access patterns change. CDS views provide optimized currency conversion with built-in TCURR access.',
    pattern: /\bSELECT\s+.*\bFROM\s+(TCURR|TCURX)\b/i,
    patternType: 'source',
    remediation: 'Use CDS currency conversion functions (CURRENCY_CONVERSION) instead of direct TCURR reads. Use I_ExchangeRateRawData CDS view.',
    simplificationId: 'S4TWL-FI-CUR-002',
  },
  {
    id: 'SIMPL-FI-078',
    category: 'Finance - Currency',
    severity: 'high',
    title: 'Group currency and additional currencies in ACDOCA',
    description: 'Third (group) currency and additional local currencies are stored directly in ACDOCA. FM CONVERT_TO_LOCAL_CURRENCY results may differ from ACDOCA stored values.',
    pattern: /\b(CONVERT_TO_LOCAL_CURRENCY|CONVERT_TO_FOREIGN_CURRENCY)\b/i,
    patternType: 'source',
    remediation: 'Read currency amounts directly from ACDOCA (fields KSL, MSL, etc.) instead of re-converting. Use ACDOCA as single source of truth for all currencies.',
    simplificationId: 'S4TWL-FI-CUR-003',
  },
  {
    id: 'SIMPL-FI-079',
    category: 'Finance - Currency',
    severity: 'medium',
    title: 'Currency type configuration for parallel accounting',
    description: 'Currency types (10, 30, 40, etc.) must be properly assigned to ledgers in S/4HANA. Classic FINSC_CURTYPE configuration requires review for ACDOCA compatibility.',
    pattern: /\b(FINSC_CURTYPE|T001_CURTYPE|CURRENCY_TYPE)\b/i,
    patternType: 'source',
    remediation: 'Review currency type configuration in FINSC_CURTYPE. Ensure ledger-currency type assignments match ACDOCA storage requirements.',
    simplificationId: 'S4TWL-FI-CUR-004',
  },
  {
    id: 'SIMPL-FI-080',
    category: 'Finance - Currency',
    severity: 'medium',
    title: 'Hard-coded currency decimal handling for TCURX',
    description: 'Custom code using hard-coded decimal place logic for currencies (e.g., JPY, KWD) must use TCURX-based conversion. ACDOCA stores amounts with full precision.',
    pattern: /\b(TCURX|BAPI_CURRENCY_CONV_TO_INTERNAL|BAPI_CURRENCY_CONV_TO_EXTERNAL)\b/i,
    patternType: 'source',
    remediation: 'Use BAPI_CURRENCY_CONV_TO_INTERNAL/EXTERNAL consistently. Never hard-code decimal places. Review all currency amount handling for ACDOCA compatibility.',
    simplificationId: 'S4TWL-FI-CUR-005',
  },
];
