/**
 * Finance (FI) Simplification Rules
 *
 * Covers: New GL (ACDOCA), Asset Accounting, AP, AR, Bank Accounting,
 * Tax, Closing, and Financial Reporting changes in S/4HANA.
 */

module.exports = [
  // ── New GL / Universal Journal ──────────────────────────────
  {
    id: 'SIMPL-FI-001',
    category: 'Finance - New GL',
    severity: 'critical',
    title: 'BSEG direct access removed',
    description: 'Table BSEG is replaced by ACDOCA (Universal Journal) in S/4HANA. Direct SELECT on BSEG will fail or return incomplete data.',
    pattern: /\bBSEG\b/i,
    patternType: 'source',
    remediation: 'Replace BSEG access with ACDOCA or CDS views I_JournalEntry / I_JournalEntryItem.',
    simplificationId: 'S4TWL-FI-001',
  },
  {
    id: 'SIMPL-FI-002',
    category: 'Finance - New GL',
    severity: 'critical',
    title: 'Customer/Vendor line item tables removed',
    description: 'Tables BSID, BSIK, BSAD, BSAK (open/cleared items) are removed. Data consolidated in ACDOCA.',
    pattern: /\b(BSID|BSIK|BSAD|BSAK)\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with appropriate filters or CDS views I_OperationalAcctgDocItem.',
    simplificationId: 'S4TWL-FI-002',
  },
  {
    id: 'SIMPL-FI-003',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'GL line item tables removed',
    description: 'Tables BSIS, BSAS (GL open/cleared items) are removed in S/4HANA.',
    pattern: /\b(BSIS|BSAS)\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with GL account filters or CDS views.',
    simplificationId: 'S4TWL-FI-003',
  },
  {
    id: 'SIMPL-FI-004',
    category: 'Finance - New GL',
    severity: 'critical',
    title: 'BKPF header table restructured',
    description: 'BKPF is restructured in S/4HANA. Fields may be moved or removed. Direct access should use CDS views.',
    pattern: /\bSELECT\s+.*\bFROM\s+BKPF\b/i,
    patternType: 'source',
    remediation: 'Use CDS view I_JournalEntry for document headers.',
    simplificationId: 'S4TWL-FI-004',
  },
  {
    id: 'SIMPL-FI-005',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'GLT0 totals table removed',
    description: 'GLT0 (GL account balance) is removed. Totals are calculated from ACDOCA.',
    pattern: /\bGLT0\b/i,
    patternType: 'source',
    remediation: 'Use CDS view I_GLAccountBalance or calculate from ACDOCA.',
    simplificationId: 'S4TWL-FI-005',
  },
  {
    id: 'SIMPL-FI-006',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'FAGLFLEXA table removed',
    description: 'FAGLFLEXA (New GL line items) is replaced by ACDOCA.',
    pattern: /\bFAGLFLEXA\b/i,
    patternType: 'source',
    remediation: 'Replace with ACDOCA or CDS view I_JournalEntryItem.',
    simplificationId: 'S4TWL-FI-006',
  },
  {
    id: 'SIMPL-FI-007',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'FAGLFLEXT totals table removed',
    description: 'FAGLFLEXT (New GL totals) removed. Totals from ACDOCA aggregation.',
    pattern: /\bFAGLFLEXT\b/i,
    patternType: 'source',
    remediation: 'Use CDS view I_GLAccountLineItem or aggregate from ACDOCA.',
    simplificationId: 'S4TWL-FI-007',
  },
  {
    id: 'SIMPL-FI-008',
    category: 'Finance - New GL',
    severity: 'medium',
    title: 'Special ledger tables (GLT*) removed',
    description: 'Special ledger tables (GLT1, GLT2, etc.) are removed. Use ACDOCA ledger concept.',
    pattern: /\bGLT[1-9]\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with ledger field (RLDNR) for multi-ledger reporting.',
    simplificationId: 'S4TWL-FI-008',
  },
  {
    id: 'SIMPL-FI-009',
    category: 'Finance - New GL',
    severity: 'medium',
    title: 'Document splitting config changed',
    description: 'Document splitting rules are simplified. Classic splitting rules may not apply.',
    pattern: /\b(FAGL_SPLINFO|FAGL_SPLIT_|BSEG_ADD)\b/i,
    patternType: 'source',
    remediation: 'Review document splitting configuration. Use S/4HANA document splitting.',
    simplificationId: 'S4TWL-FI-009',
  },
  {
    id: 'SIMPL-FI-010',
    category: 'Finance - New GL',
    severity: 'medium',
    title: 'BAPI_ACC_DOCUMENT_POST changes',
    description: 'BAPI_ACC_DOCUMENT_POST has new mandatory fields in S/4HANA.',
    pattern: /\bBAPI_ACC_DOCUMENT_POST\b/i,
    patternType: 'source',
    remediation: 'Review BAPI parameters. Add EXTENSION1/EXTENSION2 structures for new fields.',
    simplificationId: 'S4TWL-FI-010',
  },

  // ── Asset Accounting ────────────────────────────────────────
  {
    id: 'SIMPL-FI-011',
    category: 'Finance - Asset Accounting',
    severity: 'critical',
    title: 'Classic asset tables ANLP/ANLC removed',
    description: 'ANLP (periodic values), ANLC (cumulated values) are removed. New AA uses ACDOCA.',
    pattern: /\b(ANLP|ANLC)\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA for asset values or CDS views I_FixedAssetBalance*.',
    simplificationId: 'S4TWL-FI-AA-001',
  },
  {
    id: 'SIMPL-FI-012',
    category: 'Finance - Asset Accounting',
    severity: 'high',
    title: 'ANLB depreciation areas changed',
    description: 'ANLB structure changed. Depreciation areas are now linked to ledgers.',
    pattern: /\bANLB\b/i,
    patternType: 'source',
    remediation: 'Review depreciation area to ledger mapping. Use CDS views.',
    simplificationId: 'S4TWL-FI-AA-002',
  },
  {
    id: 'SIMPL-FI-013',
    category: 'Finance - Asset Accounting',
    severity: 'high',
    title: 'Asset BAPIs deprecated',
    description: 'BAPI_ASSET_POSTCAP, BAPI_ASSET_RETIREMENT and others changed in new AA.',
    pattern: /\bBAPI_ASSET_(POSTCAP|RETIREMENT|ACQUISITION|TRANSFER)\b/i,
    patternType: 'source',
    remediation: 'Use API_FIXEDASSET or reviewed BAPI interfaces for new Asset Accounting.',
    simplificationId: 'S4TWL-FI-AA-003',
  },
  {
    id: 'SIMPL-FI-014',
    category: 'Finance - Asset Accounting',
    severity: 'medium',
    title: 'ANLA asset master changes',
    description: 'ANLA table structure has new fields for new Asset Accounting.',
    pattern: /\bANLA\b(?!.*CDS)/i,
    patternType: 'source',
    remediation: 'Review ANLA field usage. Consider CDS view I_FixedAsset.',
    simplificationId: 'S4TWL-FI-AA-004',
  },

  // ── Accounts Payable ───────────────────────────────────────
  {
    id: 'SIMPL-FI-015',
    category: 'Finance - AP',
    severity: 'high',
    title: 'Payment program RFFOUS_T changes',
    description: 'Classic payment program RFFOUS_T is replaced by payment medium workbench.',
    pattern: /\bRFFOUS_T\b/i,
    patternType: 'source',
    remediation: 'Migrate to Payment Medium Workbench (PMW) or Payment Factory.',
    simplificationId: 'S4TWL-FI-AP-001',
  },
  {
    id: 'SIMPL-FI-016',
    category: 'Finance - AP',
    severity: 'medium',
    title: 'REGUH/REGUP payment tables changed',
    description: 'Payment run tables REGUH (header) and REGUP (items) are restructured.',
    pattern: /\b(REGUH|REGUP)\b/i,
    patternType: 'source',
    remediation: 'Use CDS views for payment document access.',
    simplificationId: 'S4TWL-FI-AP-002',
  },
  {
    id: 'SIMPL-FI-017',
    category: 'Finance - AP',
    severity: 'medium',
    title: 'Vendor open items BSIK removed',
    description: 'BSIK (vendor open items) replaced by ACDOCA filtering.',
    pattern: /\bBSIK\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with vendor account type filter.',
    simplificationId: 'S4TWL-FI-AP-003',
  },

  // ── Accounts Receivable ────────────────────────────────────
  {
    id: 'SIMPL-FI-018',
    category: 'Finance - AR',
    severity: 'medium',
    title: 'Dispute management changes',
    description: 'Classic dispute management (UDM_DISPUTE) replaced by FSCM dispute management.',
    pattern: /\b(UDM_DISPUTE|FDM_CUST)\b/i,
    patternType: 'source',
    remediation: 'Migrate to FSCM Dispute Management.',
    simplificationId: 'S4TWL-FI-AR-001',
  },
  {
    id: 'SIMPL-FI-019',
    category: 'Finance - AR',
    severity: 'medium',
    title: 'Customer open items BSID removed',
    description: 'BSID (customer open items) replaced by ACDOCA filtering.',
    pattern: /\bBSID\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA with customer account type filter.',
    simplificationId: 'S4TWL-FI-AR-002',
  },

  // ── Bank Accounting ────────────────────────────────────────
  {
    id: 'SIMPL-FI-020',
    category: 'Finance - Bank',
    severity: 'medium',
    title: 'Electronic bank statement changes',
    description: 'FEBEP/FEBKO tables restructured. Advanced Payment Management replaces classic bank statements.',
    pattern: /\b(FEBEP|FEBKO|FEBA)\b/i,
    patternType: 'source',
    remediation: 'Review bank statement processing. Consider Advanced Payment Management.',
    simplificationId: 'S4TWL-FI-BANK-001',
  },

  // ── Tax ────────────────────────────────────────────────────
  {
    id: 'SIMPL-FI-021',
    category: 'Finance - Tax',
    severity: 'medium',
    title: 'Tax reporting changes',
    description: 'Tax reporting tables (e.g., BSET) are removed. Tax data in ACDOCA.',
    pattern: /\bBSET\b/i,
    patternType: 'source',
    remediation: 'Use ACDOCA tax fields or CDS views for tax reporting.',
    simplificationId: 'S4TWL-FI-TAX-001',
  },
  {
    id: 'SIMPL-FI-022',
    category: 'Finance - Tax',
    severity: 'low',
    title: 'Withholding tax table changes',
    description: 'WITH_ITEM table restructured in S/4HANA.',
    pattern: /\bWITH_ITEM\b/i,
    patternType: 'source',
    remediation: 'Review withholding tax access patterns.',
    simplificationId: 'S4TWL-FI-TAX-002',
  },

  // ── Closing ────────────────────────────────────────────────
  {
    id: 'SIMPL-FI-023',
    category: 'Finance - Closing',
    severity: 'medium',
    title: 'Foreign currency valuation changes',
    description: 'FAGL_FC_VALUATION replaces classic SAPF100. Valuation results in ACDOCA.',
    pattern: /\bSAPF100\b/i,
    patternType: 'source',
    remediation: 'Use FAGL_FC_VALUATION or Financial Closing cockpit.',
    simplificationId: 'S4TWL-FI-CLOSE-001',
  },
  {
    id: 'SIMPL-FI-024',
    category: 'Finance - Closing',
    severity: 'medium',
    title: 'GR/IR clearing changes',
    description: 'Automatic GR/IR clearing (F.19) changed. WRX table removed.',
    pattern: /\bWRX\b/i,
    patternType: 'source',
    remediation: 'Use S/4HANA GR/IR clearing or MR11 changes.',
    simplificationId: 'S4TWL-FI-CLOSE-002',
  },

  // ── Financial Reporting ────────────────────────────────────
  {
    id: 'SIMPL-FI-025',
    category: 'Finance - Reporting',
    severity: 'high',
    title: 'Classic FI reports deprecated',
    description: 'Reports like FBL1N, FBL3N, FBL5N use compatibility views. Performance may degrade.',
    pattern: /\b(FBL1N|FBL3N|FBL5N|FAGLL03)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori apps (e.g., Manage Journal Entries) or analytical CDS views.',
    simplificationId: 'S4TWL-FI-RPT-001',
  },
  {
    id: 'SIMPL-FI-026',
    category: 'Finance - Reporting',
    severity: 'medium',
    title: 'Report Writer/Painter compatibility',
    description: 'Report Writer/Painter reports using removed tables will fail.',
    pattern: /\b(GR55|GRR[1-9])\b/i,
    patternType: 'source',
    remediation: 'Recreate reports using CDS-based analytical queries or SAC.',
    simplificationId: 'S4TWL-FI-RPT-002',
  },

  // ── Cost Element merge ─────────────────────────────────────
  {
    id: 'SIMPL-FI-027',
    category: 'Finance - New GL',
    severity: 'high',
    title: 'Cost element tables CSKA/CSKB removed',
    description: 'Cost element master (CSKA, CSKB) removed. Cost elements merged into GL accounts.',
    pattern: /\b(CSKA|CSKB)\b/i,
    patternType: 'source',
    remediation: 'Use GL account master (SKA1/SKB1) or CDS view I_GLAccountInChartOfAccounts.',
    simplificationId: 'S4TWL-CO-001',
  },

  // ── Ledger Group changes ───────────────────────────────────
  {
    id: 'SIMPL-FI-028',
    category: 'Finance - New GL',
    severity: 'medium',
    title: 'Ledger group access changes',
    description: 'FINSC_LEDGER, FAGL_TLDGRP tables restructured for new ledger concept.',
    pattern: /\b(FINSC_LEDGER|FAGL_TLDGRP)\b/i,
    patternType: 'source',
    remediation: 'Use CDS views for ledger configuration access.',
    simplificationId: 'S4TWL-FI-LDG-001',
  },

  // ── Consolidation ──────────────────────────────────────────
  {
    id: 'SIMPL-FI-029',
    category: 'Finance - Consolidation',
    severity: 'high',
    title: 'Classic consolidation (EC-CS) removed',
    description: 'EC-CS consolidation tables (ECMCA, ECMCT) removed. Use Group Reporting.',
    pattern: /\b(ECMCA|ECMCT|EC_CS)\b/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Group Reporting or SAP Analytics Cloud.',
    simplificationId: 'S4TWL-FI-CONS-001',
  },

  // ── Cash Management ────────────────────────────────────────
  {
    id: 'SIMPL-FI-030',
    category: 'Finance - Cash Management',
    severity: 'high',
    title: 'Classic cash management replaced',
    description: 'Classic cash management (FDSR, liquidity forecast) replaced by S/4HANA Cash Management.',
    pattern: /\b(FDSR|FLQIT|FLQITEM)\b/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Cash Management based on Bank Account Management.',
    simplificationId: 'S4TWL-FI-CM-001',
  },
];
