/**
 * Human Resources (HR/HCM) Simplification Rules
 *
 * Covers: PA/OM infotype changes, payroll, time management,
 * SuccessFactors migration paths.
 */

module.exports = [
  {
    id: 'SIMPL-HR-001',
    category: 'HR - Personnel Administration',
    severity: 'high',
    title: 'PA infotype tables restructured',
    description: 'PA infotype tables (PA0001-PA9999) may have field changes in S/4HANA HCM.',
    pattern: /\bPA00[0-9]{2}\b/i,
    patternType: 'source',
    remediation: 'Review infotype usage. Consider SuccessFactors Employee Central for cloud HCM.',
    simplificationId: 'S4TWL-HR-PA-001',
  },
  {
    id: 'SIMPL-HR-002',
    category: 'HR - Organizational Management',
    severity: 'medium',
    title: 'OM object tables changed',
    description: 'HRP1000, HRP1001 (OM objects/relationships) have changes in S/4HANA.',
    pattern: /\b(HRP1000|HRP1001|HRP1002)\b/i,
    patternType: 'source',
    remediation: 'Review OM data model. Consider SuccessFactors for org management.',
    simplificationId: 'S4TWL-HR-OM-001',
  },
  {
    id: 'SIMPL-HR-003',
    category: 'HR - Payroll',
    severity: 'high',
    title: 'Payroll cluster tables',
    description: 'Payroll cluster tables (PCL1, PCL2) require special migration handling.',
    pattern: /\b(PCL1|PCL2|PC_PAYRESULT)\b/i,
    patternType: 'source',
    remediation: 'Plan payroll data migration carefully. Consider parallel payroll runs.',
    simplificationId: 'S4TWL-HR-PY-001',
  },
  {
    id: 'SIMPL-HR-004',
    category: 'HR - Payroll',
    severity: 'medium',
    title: 'Payroll function modules changes',
    description: 'Custom payroll schemas (PCR) and function modules may need adjustment.',
    pattern: /\b(RPCLST|HR_PAYROLL_|HRCM_)\w+/i,
    patternType: 'source',
    remediation: 'Review custom payroll schemas and calculations for compatibility.',
    simplificationId: 'S4TWL-HR-PY-002',
  },
  {
    id: 'SIMPL-HR-005',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Time evaluation changes',
    description: 'Time evaluation schemas (TM04) and TEVEN/CATSDB tables affected.',
    pattern: /\b(TEVEN|CATSDB|TM04)\b/i,
    patternType: 'source',
    remediation: 'Review time management. Consider SuccessFactors Time Tracking.',
    simplificationId: 'S4TWL-HR-TM-001',
  },
  {
    id: 'SIMPL-HR-006',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Attendance/absence types changed',
    description: 'PA2001/PA2002 (absences/attendances) have changes in S/4HANA.',
    pattern: /\b(PA2001|PA2002)\b/i,
    patternType: 'source',
    remediation: 'Review absence/attendance type configuration.',
    simplificationId: 'S4TWL-HR-TM-002',
  },
  {
    id: 'SIMPL-HR-007',
    category: 'HR - Benefits',
    severity: 'medium',
    title: 'Benefits administration changes',
    description: 'Benefits infotypes and tables restructured in S/4HANA.',
    pattern: /\b(PA0167|PA0168|HRBEN_)\w*/i,
    patternType: 'source',
    remediation: 'Review benefits setup. Consider SuccessFactors Benefits for cloud.',
    simplificationId: 'S4TWL-HR-BEN-001',
  },
  {
    id: 'SIMPL-HR-008',
    category: 'HR - Recruitment',
    severity: 'high',
    title: 'Classic recruitment replaced',
    description: 'SAP E-Recruiting (HCM) replaced by SuccessFactors Recruiting.',
    pattern: /\b(HRERC_|PB[0-9]{4})\b/i,
    patternType: 'source',
    remediation: 'Migrate to SuccessFactors Recruiting.',
    simplificationId: 'S4TWL-HR-REC-001',
  },
  {
    id: 'SIMPL-HR-009',
    category: 'HR - Talent Management',
    severity: 'high',
    title: 'Talent management to SuccessFactors',
    description: 'On-premise talent management replaced by SuccessFactors modules.',
    pattern: /\b(HRTMC_|LSO_)\w+/i,
    patternType: 'source',
    remediation: 'Migrate to SuccessFactors Learning/Performance/Succession.',
    simplificationId: 'S4TWL-HR-TM-003',
  },
  {
    id: 'SIMPL-HR-010',
    category: 'HR - Master Data',
    severity: 'medium',
    title: 'HR master data BAPIs changed',
    description: 'BAPI_EMPLOYEE_* and HR_INFOTYPE_OPERATION BAPIs have changes.',
    pattern: /\b(BAPI_EMPLOYEE_|HR_INFOTYPE_OPERATION)\b/i,
    patternType: 'source',
    remediation: 'Review HR BAPIs. Consider SuccessFactors APIs for cloud integration.',
    simplificationId: 'S4TWL-HR-MD-001',
  },
  {
    id: 'SIMPL-HR-011',
    category: 'HR - ESS/MSS',
    severity: 'high',
    title: 'ESS/MSS Web Dynpro replaced',
    description: 'Web Dynpro-based ESS/MSS replaced by Fiori apps or SuccessFactors.',
    pattern: /\b(HRESS_|HRMSS_)\w+/i,
    patternType: 'source',
    remediation: 'Migrate to Fiori ESS/MSS apps or SuccessFactors.',
    simplificationId: 'S4TWL-HR-ESS-001',
  },
  {
    id: 'SIMPL-HR-012',
    category: 'HR - Travel Management',
    severity: 'high',
    title: 'Travel Management replaced by Concur',
    description: 'Classic Travel Management (TRIP/PR05) replaced by SAP Concur.',
    pattern: /\b(PRAP|PRTE|TRIP)\b/i,
    patternType: 'source',
    remediation: 'Migrate to SAP Concur for travel and expense management.',
    simplificationId: 'S4TWL-HR-TRV-001',
  },
];
