/**
 * Copyright 2024-2026 SEN Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
/**
 * Human Resources (HR/HCM) Simplification Rules
 *
 * Covers: PA/OM infotype changes, payroll, time management,
 * SuccessFactors migration paths, personnel administration,
 * organizational management, benefits, compensation, talent management.
 */

module.exports = [
  // ── Existing rules (001–012) ──────────────────────────────────────────

  {
    id: 'SIMPL-HR-001',
    category: 'HR - Personnel Administration',
    severity: 'high',
    title: 'PA infotype tables restructured',
    description: 'PA infotype tables (PA0001-PA9999) may have field changes in S/4HANA HCM.',
    pattern: /\bPA00[0-9]{2}\b/i,
    patternType: 'source',
    remediation: 'Review infotype usage. Consider SuccessFactors Employee Central for cloud HCM.',
    simplificationId: 'S4TWL-HR-PA-001',
  },
  {
    id: 'SIMPL-HR-002',
    category: 'HR - Organizational Management',
    severity: 'medium',
    title: 'OM object tables changed',
    description: 'HRP1000, HRP1001 (OM objects/relationships) have changes in S/4HANA.',
    pattern: /\b(HRP1000|HRP1001|HRP1002)\b/i,
    patternType: 'source',
    remediation: 'Review OM data model. Consider SuccessFactors for org management.',
    simplificationId: 'S4TWL-HR-OM-001',
  },
  {
    id: 'SIMPL-HR-003',
    category: 'HR - Payroll',
    severity: 'high',
    title: 'Payroll cluster tables',
    description: 'Payroll cluster tables (PCL1, PCL2) require special migration handling.',
    pattern: /\b(PCL1|PCL2|PC_PAYRESULT)\b/i,
    patternType: 'source',
    remediation: 'Plan payroll data migration carefully. Consider parallel payroll runs.',
    simplificationId: 'S4TWL-HR-PY-001',
  },
  {
    id: 'SIMPL-HR-004',
    category: 'HR - Payroll',
    severity: 'medium',
    title: 'Payroll function modules changes',
    description: 'Custom payroll schemas (PCR) and function modules may need adjustment.',
    pattern: /\b(RPCLST|HR_PAYROLL_|HRCM_)\w+/i,
    patternType: 'source',
    remediation: 'Review custom payroll schemas and calculations for compatibility.',
    simplificationId: 'S4TWL-HR-PY-002',
  },
  {
    id: 'SIMPL-HR-005',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Time evaluation changes',
    description: 'Time evaluation schemas (TM04) and TEVEN/CATSDB tables affected.',
    pattern: /\b(TEVEN|CATSDB|TM04)\b/i,
    patternType: 'source',
    remediation: 'Review time management. Consider SuccessFactors Time Tracking.',
    simplificationId: 'S4TWL-HR-TM-001',
  },
  {
    id: 'SIMPL-HR-006',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Attendance/absence types changed',
    description: 'PA2001/PA2002 (absences/attendances) have changes in S/4HANA.',
    pattern: /\b(PA2001|PA2002)\b/i,
    patternType: 'source',
    remediation: 'Review absence/attendance type configuration.',
    simplificationId: 'S4TWL-HR-TM-002',
  },
  {
    id: 'SIMPL-HR-007',
    category: 'HR - Benefits',
    severity: 'medium',
    title: 'Benefits administration changes',
    description: 'Benefits infotypes and tables restructured in S/4HANA.',
    pattern: /\b(PA0167|PA0168|HRBEN_)\w*/i,
    patternType: 'source',
    remediation: 'Review benefits setup. Consider SuccessFactors Benefits for cloud.',
    simplificationId: 'S4TWL-HR-BEN-001',
  },
  {
    id: 'SIMPL-HR-008',
    category: 'HR - Recruitment',
    severity: 'high',
    title: 'Classic recruitment replaced',
    description: 'SAP E-Recruiting (HCM) replaced by SuccessFactors Recruiting.',
    pattern: /\b(HRERC_|PB[0-9]{4})\b/i,
    patternType: 'source',
    remediation: 'Migrate to SuccessFactors Recruiting.',
    simplificationId: 'S4TWL-HR-REC-001',
  },
  {
    id: 'SIMPL-HR-009',
    category: 'HR - Talent Management',
    severity: 'high',
    title: 'Talent management to SuccessFactors',
    description: 'On-premise talent management replaced by SuccessFactors modules.',
    pattern: /\b(HRTMC_|LSO_)\w+/i,
    patternType: 'source',
    remediation: 'Migrate to SuccessFactors Learning/Performance/Succession.',
    simplificationId: 'S4TWL-HR-TM-003',
  },
  {
    id: 'SIMPL-HR-010',
    category: 'HR - Master Data',
    severity: 'medium',
    title: 'HR master data BAPIs changed',
    description: 'BAPI_EMPLOYEE_* and HR_INFOTYPE_OPERATION BAPIs have changes.',
    pattern: /\b(BAPI_EMPLOYEE_|HR_INFOTYPE_OPERATION)\b/i,
    patternType: 'source',
    remediation: 'Review HR BAPIs. Consider SuccessFactors APIs for cloud integration.',
    simplificationId: 'S4TWL-HR-MD-001',
  },
  {
    id: 'SIMPL-HR-011',
    category: 'HR - ESS/MSS',
    severity: 'high',
    title: 'ESS/MSS Web Dynpro replaced',
    description: 'Web Dynpro-based ESS/MSS replaced by Fiori apps or SuccessFactors.',
    pattern: /\b(HRESS_|HRMSS_)\w+/i,
    patternType: 'source',
    remediation: 'Migrate to Fiori ESS/MSS apps or SuccessFactors.',
    simplificationId: 'S4TWL-HR-ESS-001',
  },
  {
    id: 'SIMPL-HR-012',
    category: 'HR - Travel Management',
    severity: 'high',
    title: 'Travel Management replaced by Concur',
    description: 'Classic Travel Management (TRIP/PR05) replaced by SAP Concur.',
    pattern: /\b(PRAP|PRTE|TRIP)\b/i,
    patternType: 'source',
    remediation: 'Migrate to SAP Concur for travel and expense management.',
    simplificationId: 'S4TWL-HR-TRV-001',
  },

  // ── Personnel Administration Extended (013–019) ───────────────────────

  {
    id: 'SIMPL-HR-013',
    category: 'HR - Personnel Administration',
    severity: 'medium',
    title: 'Personnel actions (PA40) changes',
    description: 'Personnel action types and infotype sequences may change in S/4HANA HCM.',
    pattern: /\b(PA40|PA42)\b|PERSONNEL_ACTION/i,
    patternType: 'source',
    remediation: 'Review personnel action configuration. Use Fiori app Maintain Employee Master Data.',
    simplificationId: 'S4TWL-HR-PA-002',
  },
  {
    id: 'SIMPL-HR-014',
    category: 'HR - Personnel Administration',
    severity: 'medium',
    title: 'Custom infotype handling',
    description: 'Custom infotypes (PA9000+) require migration review for S/4HANA compatibility.',
    pattern: /\bPA9[0-9]{3}\b/i,
    patternType: 'source',
    remediation: 'Review custom infotype structures. Validate screen enhancements for Fiori compatibility.',
    simplificationId: 'S4TWL-HR-PA-003',
  },
  {
    id: 'SIMPL-HR-015',
    category: 'HR - Personnel Administration',
    severity: 'medium',
    title: 'Personnel number range assignment',
    description: 'Personnel number ranges and assignment logic may need review for S/4HANA.',
    pattern: /\bRP_PROVIDE_FROM_LAST\b|PERNR_RANGE/i,
    patternType: 'source',
    remediation: 'Review personnel number range configuration and external number assignment.',
    simplificationId: 'S4TWL-HR-PA-004',
  },
  {
    id: 'SIMPL-HR-016',
    category: 'HR - Personnel Administration',
    severity: 'low',
    title: 'PA infotype screen enhancements',
    description: 'Infotype screen enhancements (PM01) may need adjustment for Fiori-based maintenance.',
    pattern: /\bPM01\b|INFOTYPE_SCREEN/i,
    patternType: 'source',
    remediation: 'Review infotype screen enhancements. Fiori apps may bypass classic dynpro screens.',
    simplificationId: 'S4TWL-HR-PA-005',
  },
  {
    id: 'SIMPL-HR-017',
    category: 'HR - Personnel Administration',
    severity: 'medium',
    title: 'PA data replication to Employee Central',
    description: 'Employee Central integration requires PA data mapping and replication setup.',
    pattern: /\bEC_\w+|EMPLOYEE_CENTRAL\b|SF_EC/i,
    patternType: 'source',
    remediation: 'Plan Employee Central data mapping. Use SAP Integration Suite for replication.',
    simplificationId: 'S4TWL-HR-PA-006',
  },
  {
    id: 'SIMPL-HR-018',
    category: 'HR - Personnel Administration',
    severity: 'low',
    title: 'Feature-based configuration (PE03)',
    description: 'HR features (PE03) for dynamic defaulting may need S/4HANA review.',
    pattern: /\b(PE03|PE04)\b|FEATURE_\w+/i,
    patternType: 'source',
    remediation: 'Review HR features. Ensure decision trees are compatible with S/4HANA data model.',
    simplificationId: 'S4TWL-HR-PA-007',
  },
  {
    id: 'SIMPL-HR-019',
    category: 'HR - Personnel Administration',
    severity: 'medium',
    title: 'Concurrent employment handling',
    description: 'Concurrent employment (PA0000 multiple assignments) has S/4HANA configuration changes.',
    pattern: /\bCONCURRENT_EMPL\b|MULTIPLE_ASSIGNMENT/i,
    patternType: 'source',
    remediation: 'Review concurrent employment setup. Validate personnel assignment handling.',
    simplificationId: 'S4TWL-HR-PA-008',
  },

  // ── Organizational Management Extended (020–024) ──────────────────────

  {
    id: 'SIMPL-HR-020',
    category: 'HR - Organizational Management',
    severity: 'medium',
    title: 'Organizational structure BAPIs',
    description: 'BAPI_ORGUNIT_* and RH_* function modules have changes in S/4HANA.',
    pattern: /\b(BAPI_ORGUNIT_\w+|RH_READ_\w+|RH_GET_\w+)/i,
    patternType: 'source',
    remediation: 'Review OM BAPIs. Consider SuccessFactors APIs for organizational management.',
    simplificationId: 'S4TWL-HR-OM-002',
  },
  {
    id: 'SIMPL-HR-021',
    category: 'HR - Organizational Management',
    severity: 'medium',
    title: 'Position management changes (PPOME)',
    description: 'Position management (PPOME) and position budgeting have S/4HANA updates.',
    pattern: /\b(PPOME|PPOM_OLD|PO13)\b/i,
    patternType: 'source',
    remediation: 'Review position management. Use Fiori app Maintain Positions or SuccessFactors.',
    simplificationId: 'S4TWL-HR-OM-003',
  },
  {
    id: 'SIMPL-HR-022',
    category: 'HR - Organizational Management',
    severity: 'medium',
    title: 'OM evaluation paths',
    description: 'Evaluation paths (PPST, T778A) for OM structure traversal may need review.',
    pattern: /\b(PPST|T778A)\b|EVAL_PATH/i,
    patternType: 'source',
    remediation: 'Review evaluation paths. Ensure custom paths work with S/4HANA OM structure.',
    simplificationId: 'S4TWL-HR-OM-004',
  },
  {
    id: 'SIMPL-HR-023',
    category: 'HR - Organizational Management',
    severity: 'medium',
    title: 'Integration model OM to PA (RHINTE)',
    description: 'OM-PA integration (RHINTE00/RHINTE10) may have changes in S/4HANA.',
    pattern: /\bRHINTE\w+/i,
    patternType: 'source',
    remediation: 'Review OM-PA integration configuration. Validate position-person assignment.',
    simplificationId: 'S4TWL-HR-OM-005',
  },
  {
    id: 'SIMPL-HR-024',
    category: 'HR - Organizational Management',
    severity: 'low',
    title: 'OM infotype enhancements (HRP1000+)',
    description: 'Custom OM infotypes and object types need S/4HANA compatibility review.',
    pattern: /\bHRP[0-9]{4}\b/i,
    patternType: 'source',
    remediation: 'Review custom OM infotypes and object type definitions for S/4HANA.',
    simplificationId: 'S4TWL-HR-OM-006',
  },

  // ── Payroll Extended (025–031) ────────────────────────────────────────

  {
    id: 'SIMPL-HR-025',
    category: 'HR - Payroll',
    severity: 'high',
    title: 'Payroll schema customizations (PE01)',
    description: 'Custom payroll schemas and PCRs (PE01/PE02) require thorough migration testing.',
    pattern: /\b(PE01|PE02)\b|PAYROLL_SCHEMA/i,
    patternType: 'source',
    remediation: 'Test all custom payroll schemas in S/4HANA. Validate calculation results with parallel run.',
    simplificationId: 'S4TWL-HR-PY-003',
  },
  {
    id: 'SIMPL-HR-026',
    category: 'HR - Payroll',
    severity: 'high',
    title: 'Wage type configuration changes',
    description: 'Wage type catalog (V_512W_D) and processing classes may need review.',
    pattern: /\bV_512W_D\b|WAGE_TYPE\b|T512W\b/i,
    patternType: 'source',
    remediation: 'Review wage type configuration. Validate processing classes and cumulation rules.',
    simplificationId: 'S4TWL-HR-PY-004',
  },
  {
    id: 'SIMPL-HR-027',
    category: 'HR - Payroll',
    severity: 'medium',
    title: 'Payroll driver country-specific changes',
    description: 'Country-specific payroll drivers (RPCALC*) may have S/4HANA updates.',
    pattern: /\bRPCALC\w+/i,
    patternType: 'source',
    remediation: 'Review country-specific payroll changes. Apply latest SAP notes for payroll drivers.',
    simplificationId: 'S4TWL-HR-PY-005',
  },
  {
    id: 'SIMPL-HR-028',
    category: 'HR - Payroll',
    severity: 'high',
    title: 'Payroll cluster data conversion',
    description: 'PCL2 cluster data must be converted when cluster tables become transparent in S/4HANA.',
    pattern: /\bPCL2\b|PAYROLL_RESULT/i,
    patternType: 'source',
    remediation: 'Plan PCL2 data conversion. Ensure payroll results are readable after migration.',
    simplificationId: 'S4TWL-HR-PY-006',
  },
  {
    id: 'SIMPL-HR-029',
    category: 'HR - Payroll',
    severity: 'medium',
    title: 'Payroll posting to Finance (RPCIPE)',
    description: 'Payroll posting to accounting (RPCIPE*) integrates with ACDOCA in S/4HANA.',
    pattern: /\bRPCIPE\w+|PC00_M\w+_CIPE/i,
    patternType: 'source',
    remediation: 'Review payroll posting configuration. Posting now targets ACDOCA Universal Journal.',
    simplificationId: 'S4TWL-HR-PY-007',
  },
  {
    id: 'SIMPL-HR-030',
    category: 'HR - Payroll',
    severity: 'medium',
    title: 'Retroactive payroll accounting',
    description: 'Retroactive payroll runs and earliest retro date handling in S/4HANA.',
    pattern: /\bRETRO_PAYROLL\b|EARLIEST_RETRO|RPCLSTR/i,
    patternType: 'source',
    remediation: 'Review retroactive payroll configuration. Validate retro calculation accuracy.',
    simplificationId: 'S4TWL-HR-PY-008',
  },
  {
    id: 'SIMPL-HR-031',
    category: 'HR - Payroll',
    severity: 'medium',
    title: 'Third-party remittance changes',
    description: 'Third-party remittance and garnishment processing have S/4HANA updates.',
    pattern: /\bRPCEDT\w+|GARNISHMENT\b|THIRD_PARTY_REMIT/i,
    patternType: 'source',
    remediation: 'Review third-party remittance configuration and payment processing.',
    simplificationId: 'S4TWL-HR-PY-009',
  },

  // ── Time Management Extended (032–037) ────────────────────────────────

  {
    id: 'SIMPL-HR-032',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Time recording integration (CATS)',
    description: 'Cross-Application Time Sheet (CATS) has S/4HANA enhancements and Fiori apps.',
    pattern: /\b(CATS|CAT2|CAT6)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app My Timesheet or Manage Working Times. Review CATS configuration.',
    simplificationId: 'S4TWL-HR-TM-004',
  },
  {
    id: 'SIMPL-HR-033',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Absence quota management',
    description: 'Absence quota generation (RPTQTA00) and leave management have S/4HANA changes.',
    pattern: /\bRPTQTA\w+|ABSENCE_QUOTA\b|PA2006\b/i,
    patternType: 'source',
    remediation: 'Review absence quota configuration. Use Fiori Leave Request apps.',
    simplificationId: 'S4TWL-HR-TM-005',
  },
  {
    id: 'SIMPL-HR-034',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Substitution type handling',
    description: 'Substitution infotype (PA2003) and delegation logic have S/4HANA updates.',
    pattern: /\bPA2003\b|SUBSTITUTION_TYPE/i,
    patternType: 'source',
    remediation: 'Review substitution configuration. Ensure compatibility with Fiori approval workflows.',
    simplificationId: 'S4TWL-HR-TM-006',
  },
  {
    id: 'SIMPL-HR-035',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Time evaluation schema changes',
    description: 'Time evaluation schemas (TM00/TM04) and custom PCRs need S/4HANA validation.',
    pattern: /\b(TM00|TM01|TM04)\b|TIME_EVAL_SCHEMA/i,
    patternType: 'source',
    remediation: 'Test time evaluation schemas thoroughly. Validate results with parallel run.',
    simplificationId: 'S4TWL-HR-TM-007',
  },
  {
    id: 'SIMPL-HR-036',
    category: 'HR - Time Management',
    severity: 'medium',
    title: 'Shift planning changes',
    description: 'Shift planning (PP61/PP62) and work schedule generation have S/4HANA changes.',
    pattern: /\b(PP61|PP62|PP63)\b|SHIFT_PLAN/i,
    patternType: 'source',
    remediation: 'Review shift planning. Consider SuccessFactors Time Tracking for advanced scheduling.',
    simplificationId: 'S4TWL-HR-TM-008',
  },
  {
    id: 'SIMPL-HR-037',
    category: 'HR - Time Management',
    severity: 'low',
    title: 'Work schedule rule configuration',
    description: 'Work schedule rules (PT01) and daily work schedules need S/4HANA review.',
    pattern: /\b(PT01|PT02|PT03)\b|WORK_SCHEDULE/i,
    patternType: 'source',
    remediation: 'Review work schedule rules and holiday calendar configuration.',
    simplificationId: 'S4TWL-HR-TM-009',
  },

  // ── SuccessFactors Integration (038–043) ──────────────────────────────

  {
    id: 'SIMPL-HR-038',
    category: 'HR - SuccessFactors',
    severity: 'high',
    title: 'Employee Central integration (EC)',
    description: 'SuccessFactors Employee Central requires data replication from on-premise PA/OM.',
    pattern: /\bEMPLOYEE_CENTRAL\b|SF_EC_\w+|SFSF_EC/i,
    patternType: 'source',
    remediation: 'Plan Employee Central integration. Use SAP Integration Suite for data replication.',
    simplificationId: 'S4TWL-HR-SF-001',
  },
  {
    id: 'SIMPL-HR-039',
    category: 'HR - SuccessFactors',
    severity: 'high',
    title: 'SuccessFactors Recruiting integration',
    description: 'On-premise recruitment to SuccessFactors Recruiting migration required.',
    pattern: /\bSF_RECRUITING\b|RCM_\w+/i,
    patternType: 'source',
    remediation: 'Migrate to SuccessFactors Recruiting. Map requisition and candidate data.',
    simplificationId: 'S4TWL-HR-SF-002',
  },
  {
    id: 'SIMPL-HR-040',
    category: 'HR - SuccessFactors',
    severity: 'medium',
    title: 'SuccessFactors Learning (LMS) migration',
    description: 'On-premise LSO (Learning Solution) replaced by SuccessFactors Learning.',
    pattern: /\bLSO_\w+|LEARNING_SOLUTION\b|SF_LMS/i,
    patternType: 'source',
    remediation: 'Migrate training catalogs and history to SuccessFactors Learning.',
    simplificationId: 'S4TWL-HR-SF-003',
  },
  {
    id: 'SIMPL-HR-041',
    category: 'HR - SuccessFactors',
    severity: 'medium',
    title: 'SuccessFactors Performance & Goals',
    description: 'On-premise appraisal system replaced by SuccessFactors Performance & Goals.',
    pattern: /\bHAP_\w+|APPRAISAL_\w+|SF_PERFORMANCE/i,
    patternType: 'source',
    remediation: 'Migrate appraisal templates and history to SuccessFactors Performance & Goals.',
    simplificationId: 'S4TWL-HR-SF-004',
  },
  {
    id: 'SIMPL-HR-042',
    category: 'HR - SuccessFactors',
    severity: 'medium',
    title: 'SuccessFactors Compensation integration',
    description: 'On-premise compensation management replaced by SuccessFactors Compensation.',
    pattern: /\bSF_COMPENSATION\b|COMPENSATION_MGMT/i,
    patternType: 'source',
    remediation: 'Migrate compensation plans and budgets to SuccessFactors Compensation.',
    simplificationId: 'S4TWL-HR-SF-005',
  },
  {
    id: 'SIMPL-HR-043',
    category: 'HR - SuccessFactors',
    severity: 'medium',
    title: 'SuccessFactors Succession & Development',
    description: 'On-premise succession planning replaced by SuccessFactors Succession & Development.',
    pattern: /\bSF_SUCCESSION\b|SUCCESSION_PLAN\b|TALENT_POOL/i,
    patternType: 'source',
    remediation: 'Migrate succession plans and talent pools to SuccessFactors Succession & Development.',
    simplificationId: 'S4TWL-HR-SF-006',
  },

  // ── Benefits Extended (044–047) ───────────────────────────────────────

  {
    id: 'SIMPL-HR-044',
    category: 'HR - Benefits',
    severity: 'medium',
    title: 'Benefits enrollment processing',
    description: 'Benefits enrollment (HRBEN0001/HRBEN0071) has S/4HANA changes.',
    pattern: /\bHRBEN00\w+/i,
    patternType: 'source',
    remediation: 'Review benefits enrollment programs. Consider SuccessFactors Benefits.',
    simplificationId: 'S4TWL-HR-BEN-002',
  },
  {
    id: 'SIMPL-HR-045',
    category: 'HR - Benefits',
    severity: 'medium',
    title: 'Benefits plan configuration',
    description: 'Benefits plan types and eligibility rules may need S/4HANA review.',
    pattern: /\bBENEFIT_PLAN\b|T74F\w+/i,
    patternType: 'source',
    remediation: 'Review benefits plan configuration. Validate eligibility and coverage rules.',
    simplificationId: 'S4TWL-HR-BEN-003',
  },
  {
    id: 'SIMPL-HR-046',
    category: 'HR - Benefits',
    severity: 'low',
    title: 'Health plan and insurance integration',
    description: 'Health plan and insurance carrier integration points have S/4HANA updates.',
    pattern: /\bHEALTH_PLAN\b|INSURANCE_CARRIER\b|COBRA_\w+/i,
    patternType: 'source',
    remediation: 'Review health plan and COBRA administration configuration.',
    simplificationId: 'S4TWL-HR-BEN-004',
  },
  {
    id: 'SIMPL-HR-047',
    category: 'HR - Benefits',
    severity: 'medium',
    title: 'Retirement and savings plan changes',
    description: 'Retirement plans (401k, pension) and savings plan configuration have S/4HANA updates.',
    pattern: /\bRETIREMENT_PLAN\b|SAVINGS_PLAN\b|401K\b|PENSION_\w+/i,
    patternType: 'source',
    remediation: 'Review retirement and savings plan configuration for S/4HANA compatibility.',
    simplificationId: 'S4TWL-HR-BEN-005',
  },

  // ── Compensation (048–050) ────────────────────────────────────────────

  {
    id: 'SIMPL-HR-048',
    category: 'HR - Compensation',
    severity: 'medium',
    title: 'Compensation management infotypes',
    description: 'Compensation infotypes (PA0008/PA0014/PA0015) have S/4HANA updates.',
    pattern: /\b(PA0008|PA0014|PA0015)\b/i,
    patternType: 'source',
    remediation: 'Review compensation infotype configuration. Validate pay scale and wage type mapping.',
    simplificationId: 'S4TWL-HR-COMP-001',
  },
  {
    id: 'SIMPL-HR-049',
    category: 'HR - Compensation',
    severity: 'medium',
    title: 'Pay scale restructuring',
    description: 'Pay scale structure (T510/T510A) and pay grade assignment have S/4HANA changes.',
    pattern: /\b(T510|T510A|T510N)\b|PAY_SCALE/i,
    patternType: 'source',
    remediation: 'Review pay scale configuration. Validate pay grade assignments after migration.',
    simplificationId: 'S4TWL-HR-COMP-002',
  },
  {
    id: 'SIMPL-HR-050',
    category: 'HR - Compensation',
    severity: 'medium',
    title: 'Compensation budget planning',
    description: 'Compensation review and budget planning integration have S/4HANA changes.',
    pattern: /\bCOMP_BUDGET\b|COMPENSATION_REVIEW\b|ECM_\w+/i,
    patternType: 'source',
    remediation: 'Review compensation budget process. Consider SuccessFactors Compensation for planning.',
    simplificationId: 'S4TWL-HR-COMP-003',
  },

  // ── HR Reporting / Analytics (051–053) ────────────────────────────────

  {
    id: 'SIMPL-HR-051',
    category: 'HR - Reporting',
    severity: 'medium',
    title: 'HR logical database (PNP/PNPCE) changes',
    description: 'Logical databases PNP/PNPCE for HR reporting may have S/4HANA behavior changes.',
    pattern: /\b(PNP|PNPCE)\b|LOGICAL_DATABASE.*HR/i,
    patternType: 'source',
    remediation: 'Review HR reports using PNP/PNPCE. Consider CDS analytical views.',
    simplificationId: 'S4TWL-HR-RPT-001',
  },
  {
    id: 'SIMPL-HR-052',
    category: 'HR - Reporting',
    severity: 'medium',
    title: 'HR InfoSet queries (SQ01/SQ02)',
    description: 'HR InfoSet queries and Ad Hoc Query (S_PH0_48000513) have Fiori alternatives.',
    pattern: /\b(SQ01|SQ02)\b.*HR|S_PH0_\w+/i,
    patternType: 'source',
    remediation: 'Review HR queries. Consider SAP Analytics Cloud or Fiori analytical apps.',
    simplificationId: 'S4TWL-HR-RPT-002',
  },
  {
    id: 'SIMPL-HR-053',
    category: 'HR - Reporting',
    severity: 'low',
    title: 'Headcount and FTE analytics',
    description: 'Headcount and FTE reporting has new CDS views and Fiori analytical apps in S/4HANA.',
    pattern: /\bHEADCOUNT\b|FTE_\w+|HR_ANALYTICS/i,
    patternType: 'source',
    remediation: 'Use S/4HANA Fiori analytical apps for headcount and workforce analytics.',
    simplificationId: 'S4TWL-HR-RPT-003',
  },
];
