/**
 * Copyright 2024-2026 SEN Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
/**
 * Interface & Integration Simplification Rules
 *
 * Covers: RFC destinations, IDoc flows, SOAP/REST/OData web services,
 * CPI (Cloud Platform Integration), batch jobs, EDI, partner communication,
 * file-based interfaces, and middleware migration.
 */

module.exports = [
  // ── RFC Destinations ───────────────────────────────────────────
  {
    id: 'SIMPL-INT-001',
    category: 'Interfaces - RFC',
    severity: 'high',
    title: 'RFC destination type T (TCP/IP) migration',
    description: 'Type T (TCP/IP) RFC destinations for file transfer should migrate to CPI SFTP adapter.',
    pattern: /\bRFCDES.*TYPE.*['"]T['"]/i,
    patternType: 'source',
    remediation: 'Replace TCP/IP RFC destinations with CPI SFTP or cloud storage adapters.',
    simplificationId: 'S4TWL-INT-RFC-001',
  },
  {
    id: 'SIMPL-INT-002',
    category: 'Interfaces - RFC',
    severity: 'high',
    title: 'RFC calls to removed satellite systems',
    description: 'RFC destinations to APO, CRM, SRM are obsolete in S/4HANA (embedded functionality).',
    pattern: /\b(ERP_TO_APO|ERP_TO_CRM|ERP_TO_SRM|CALL\s+FUNCTION\s+.*DESTINATION\s+['"](?:APO|CRM|SRM))/i,
    patternType: 'source',
    remediation: 'Use embedded S/4HANA functionality (embedded PP/DS, Customer Management, central procurement).',
    simplificationId: 'S4TWL-INT-RFC-002',
  },
  {
    id: 'SIMPL-INT-003',
    category: 'Interfaces - RFC',
    severity: 'medium',
    title: 'RFC destination to BW system',
    description: 'BW extractors and RFC destinations to BW may need reconfiguration for embedded analytics.',
    pattern: /\b(ERP_TO_BW|BW_RFC|RSA7|SBIW)\b/i,
    patternType: 'source',
    remediation: 'Review BW extractors; consider CDS-based extraction or embedded BW/4HANA.',
    simplificationId: 'S4TWL-INT-RFC-003',
  },
  {
    id: 'SIMPL-INT-004',
    category: 'Interfaces - RFC',
    severity: 'medium',
    title: 'RFC destination to Solution Manager',
    description: 'Solution Manager RFC connections should migrate to Cloud ALM.',
    pattern: /\b(ERP_TO_SOLMAN|SOLMAN_RFC|SM_RFC)\b/i,
    patternType: 'source',
    remediation: 'Migrate Solution Manager integration to SAP Cloud ALM.',
    simplificationId: 'S4TWL-INT-RFC-004',
  },
  {
    id: 'SIMPL-INT-005',
    category: 'Interfaces - RFC',
    severity: 'low',
    title: 'RFC destination security hardening',
    description: 'RFC destinations should use SNC or certificate-based auth in S/4HANA.',
    pattern: /\bRFCDES.*RFCSNC\b/i,
    patternType: 'source',
    remediation: 'Enable SNC encryption for all RFC destinations.',
    simplificationId: 'S4TWL-INT-RFC-005',
  },

  // ── IDoc Flows ─────────────────────────────────────────────────
  {
    id: 'SIMPL-INT-006',
    category: 'Interfaces - IDoc',
    severity: 'high',
    title: 'IDoc segment structure changes',
    description: 'Several IDoc types have new/changed segments in S/4HANA (ORDERS, INVOIC, DESADV).',
    pattern: /\b(ORDERS05|INVOIC02|DESADV01|DELVRY03)\b/i,
    patternType: 'source',
    remediation: 'Review IDoc segment mappings for S/4HANA field changes. Test with WE19.',
    simplificationId: 'S4TWL-INT-IDOC-001',
  },
  {
    id: 'SIMPL-INT-007',
    category: 'Interfaces - IDoc',
    severity: 'high',
    title: 'Material master IDoc changes (MATMAS)',
    description: 'MATMAS IDoc type changed due to material number length extension to 40 chars.',
    pattern: /\bMATMAS\d{2}\b/i,
    patternType: 'source',
    remediation: 'Update MATMAS mappings for 40-character material numbers and new segments.',
    simplificationId: 'S4TWL-INT-IDOC-002',
  },
  {
    id: 'SIMPL-INT-008',
    category: 'Interfaces - IDoc',
    severity: 'medium',
    title: 'Business partner IDoc replaces customer/vendor IDocs',
    description: 'DEBMAS/CREMAS IDocs replaced by BUMAS (Business Partner) in S/4HANA.',
    pattern: /\b(DEBMAS\d{2}|CREMAS\d{2})\b/i,
    patternType: 'source',
    remediation: 'Migrate to BUMAS IDoc type for business partner distribution.',
    simplificationId: 'S4TWL-INT-IDOC-003',
  },
  {
    id: 'SIMPL-INT-009',
    category: 'Interfaces - IDoc',
    severity: 'medium',
    title: 'WM IDocs replaced by EWM integration',
    description: 'WMMBID/WMTOCO IDocs for WM replaced by embedded EWM or decentralized EWM.',
    pattern: /\b(WMMBID|WMTOCO)\d{2}\b/i,
    patternType: 'source',
    remediation: 'Migrate WM IDoc flows to embedded EWM or decentralized EWM APIs.',
    simplificationId: 'S4TWL-INT-IDOC-004',
  },
  {
    id: 'SIMPL-INT-010',
    category: 'Interfaces - IDoc',
    severity: 'medium',
    title: 'IDoc partner profiles need review',
    description: 'Partner profiles (WE20) and port configuration may need update for S/4HANA.',
    pattern: /\b(WE20|WE21|WE41|WE42|WE46|BD64)\b/i,
    patternType: 'source',
    remediation: 'Review partner profiles and IDoc ports for S/4HANA compatibility.',
    simplificationId: 'S4TWL-INT-IDOC-005',
  },

  // ── Web Services ───────────────────────────────────────────────
  {
    id: 'SIMPL-INT-011',
    category: 'Interfaces - Web Services',
    severity: 'high',
    title: 'SOAP web services to REST/OData migration',
    description: 'Custom SOAP services (SOAMANAGER) should migrate to OData or REST APIs.',
    pattern: /\b(SOAMANAGER|LPCONFIG|CL_PROXY_|IF_PROXY_)\b/i,
    patternType: 'source',
    remediation: 'Replace SOAP proxies with OData services or RAP-based APIs.',
    simplificationId: 'S4TWL-INT-WS-001',
  },
  {
    id: 'SIMPL-INT-012',
    category: 'Interfaces - Web Services',
    severity: 'medium',
    title: 'Enterprise Services deprecated',
    description: 'SAP Enterprise Services (ES) Bundle replaced by S/4HANA APIs.',
    pattern: /\b(SOAPENV|WSDL_GENERATE|CL_WS_RUNTIME)\b/i,
    patternType: 'source',
    remediation: 'Use SAP API Business Hub for replacement S/4HANA APIs.',
    simplificationId: 'S4TWL-INT-WS-002',
  },
  {
    id: 'SIMPL-INT-013',
    category: 'Interfaces - Web Services',
    severity: 'medium',
    title: 'Custom OData services need RAP review',
    description: 'Custom OData v2 services (SEGW) should be reviewed for RAP migration.',
    pattern: /\b(SEGW|\/IWBEP\/|CL_SADL_)\b/i,
    patternType: 'source',
    remediation: 'Consider migrating custom OData services to RAP (ABAP RESTful Application Programming).',
    simplificationId: 'S4TWL-INT-WS-003',
  },

  // ── CPI / Middleware ───────────────────────────────────────────
  {
    id: 'SIMPL-INT-014',
    category: 'Interfaces - CPI',
    severity: 'high',
    title: 'PI/PO middleware migration to CPI',
    description: 'SAP PI/PO integration flows should migrate to SAP Integration Suite (CPI).',
    pattern: /\b(ERP_TO_PI|PI_RFC|SXMB_MONI|SXI_MONITOR|SXMB_ADM)\b/i,
    patternType: 'source',
    remediation: 'Migrate PI/PO iFlows to SAP Integration Suite using Migration Assessment tool.',
    simplificationId: 'S4TWL-INT-CPI-001',
  },
  {
    id: 'SIMPL-INT-015',
    category: 'Interfaces - CPI',
    severity: 'medium',
    title: 'XI protocol usage',
    description: 'XI (Exchange Infrastructure) protocol calls should use modern integration.',
    pattern: /\b(CL_XMS_|IF_XMS_|SXMS_|XI_ADAPTER)\b/i,
    patternType: 'source',
    remediation: 'Replace XI protocol with REST/OData through CPI or direct API calls.',
    simplificationId: 'S4TWL-INT-CPI-002',
  },

  // ── EDI / Partner Communication ────────────────────────────────
  {
    id: 'SIMPL-INT-016',
    category: 'Interfaces - EDI',
    severity: 'medium',
    title: 'EDI subsystem integration changes',
    description: 'EDI VAN provider connections may need reconfiguration through CPI.',
    pattern: /\b(EDI_PROVIDER|EDPAR|EDP13|NAST.*EDI)\b/i,
    patternType: 'source',
    remediation: 'Route EDI flows through CPI with B2B Trading Partner Management.',
    simplificationId: 'S4TWL-INT-EDI-001',
  },
  {
    id: 'SIMPL-INT-017',
    category: 'Interfaces - EDI',
    severity: 'low',
    title: 'Output management modernization',
    description: 'Classic output determination (NACE/NAST) replaced by BRF+ and Output Management.',
    pattern: /\b(NACE|NAST|RSNAST00)\b/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Output Management with BRF+ rules.',
    simplificationId: 'S4TWL-INT-EDI-002',
  },

  // ── File-based Interfaces ──────────────────────────────────────
  {
    id: 'SIMPL-INT-018',
    category: 'Interfaces - File',
    severity: 'medium',
    title: 'Bank file format migration (MT940 → camt.053)',
    description: 'MT940 bank statement format should migrate to ISO 20022 (camt.053).',
    pattern: /\b(MT940|FEBKO|FEBEP|FF_5|FF\.5)\b/i,
    patternType: 'source',
    remediation: 'Configure Advanced Payment Management with ISO 20022 camt.053 format.',
    simplificationId: 'S4TWL-INT-FILE-001',
  },
  {
    id: 'SIMPL-INT-019',
    category: 'Interfaces - File',
    severity: 'medium',
    title: 'Payment file format migration (MT101 → pain.001)',
    description: 'Payment file formats should migrate to ISO 20022 pain.001.',
    pattern: /\b(MT101|DMEE|OBPM4|PAIN_001)\b/i,
    patternType: 'source',
    remediation: 'Use SAP Payment Engine or Advanced Payment Management with pain.001.',
    simplificationId: 'S4TWL-INT-FILE-002',
  },

  // ── Batch Jobs ─────────────────────────────────────────────────
  {
    id: 'SIMPL-INT-020',
    category: 'Interfaces - Batch',
    severity: 'medium',
    title: 'Custom batch programs need review',
    description: 'Custom Z-programs in batch jobs may reference changed tables/BAPIs.',
    pattern: /\b(SM36|SM37|BTCTRNS|JOB_OPEN|JOB_CLOSE|JOB_SUBMIT)\b/i,
    patternType: 'source',
    remediation: 'Review batch job programs for S/4HANA compatibility; consider Application Jobs.',
    simplificationId: 'S4TWL-INT-BATCH-001',
  },
  {
    id: 'SIMPL-INT-021',
    category: 'Interfaces - Batch',
    severity: 'low',
    title: 'Application Jobs replace classic batch',
    description: 'S/4HANA Application Jobs (SM36 replacement) provide better monitoring.',
    pattern: /\bCL_APJ_|IF_APJ_/i,
    patternType: 'source',
    remediation: 'Consider migrating custom batch jobs to Application Job framework.',
    simplificationId: 'S4TWL-INT-BATCH-002',
  },

  // ── Cloud Integration ──────────────────────────────────────────
  {
    id: 'SIMPL-INT-022',
    category: 'Interfaces - Cloud',
    severity: 'high',
    title: 'SuccessFactors integration changes',
    description: 'HR master data replication to SuccessFactors should use CPI standard content.',
    pattern: /\b(SF_EC|SUCCESSFACTORS|HRMD_A\d{2})\b/i,
    patternType: 'source',
    remediation: 'Use CPI standard integration packages for SuccessFactors Employee Central.',
    simplificationId: 'S4TWL-INT-CLD-001',
  },
  {
    id: 'SIMPL-INT-023',
    category: 'Interfaces - Cloud',
    severity: 'medium',
    title: 'Ariba Network integration update',
    description: 'Ariba procurement integration should use standard CPI content packages.',
    pattern: /\b(ARIBA_NETWORK|ARIBA_RFC|PORDCR\d{2})\b/i,
    patternType: 'source',
    remediation: 'Use SAP Business Network integration via CPI with standard adapters.',
    simplificationId: 'S4TWL-INT-CLD-002',
  },
  {
    id: 'SIMPL-INT-024',
    category: 'Interfaces - Cloud',
    severity: 'medium',
    title: 'Concur integration modernization',
    description: 'Concur travel/expense integration should use CPI standard content.',
    pattern: /\b(CONCUR_API|CONCUR_RFC|TRVREQ\d{2})\b/i,
    patternType: 'source',
    remediation: 'Use CPI standard integration for Concur Travel & Expense.',
    simplificationId: 'S4TWL-INT-CLD-003',
  },
  {
    id: 'SIMPL-INT-025',
    category: 'Interfaces - Cloud',
    severity: 'low',
    title: 'Third-party API integration via CPI',
    description: 'Direct RFC/HTTP calls to external APIs should route through CPI.',
    pattern: /\b(SALESFORCE_API|PAYMENT_GW|TAX_ENGINE)\b/i,
    patternType: 'source',
    remediation: 'Route third-party integrations through CPI for monitoring and governance.',
    simplificationId: 'S4TWL-INT-CLD-004',
  },
];
