/**
 * Product Lifecycle Management (PLM) Rules
 *
 * Covers Engineering Change Management, Document Management,
 * Recipe Management, and integration with S/4HANA product model.
 * Key: 40-char MATNR impact on BOM/routing, ECM process changes.
 * Extended: multi-level BOM, routing mgmt, configuration profiles,
 * product compliance, substance mgmt, engineering records, PP/QM integration.
 */

module.exports = [
  // ── Engineering Change Management ────────────────────────────
  {
    id: 'SIMPL-PLM-001',
    title: 'Engineering Change Management (ECM) Updated',
    description: 'ECM transactions (CC01-CC03) continue but BOM/routing references impacted by extended material number.',
    severity: 'high',
    category: 'PLM – Engineering Change',
    sNote: '2270859',
    pattern: /\b(CC0[1-3]|AENR|CHANGE_NUMBER|ECMPROCESS)\b/i,
    patternType: 'source',
    remediation: 'Review engineering change records referencing material numbers. Validate BOM effectivity after migration.',
  },
  {
    id: 'SIMPL-PLM-002',
    title: 'BOM Extended Material Number',
    description: 'Bill of Materials impacted by 40-character material number. All BOM components need validation.',
    severity: 'critical',
    category: 'PLM – BOM',
    sNote: '2270859',
    pattern: /\b(CS0[1-3]|STKO|STPO|MAST|BOM_ITEM|CSAP_MAT_BOM)\b/i,
    patternType: 'source',
    remediation: 'Validate all BOM structures after material number extension. Check STPO-IDNRK field (40 chars).',
  },
  {
    id: 'SIMPL-PLM-003',
    title: 'Routing Extended Material Number',
    description: 'Routings/work plans impacted by 40-character material number in component assignment.',
    severity: 'high',
    category: 'PLM – Routing',
    sNote: '2270859',
    pattern: /\b(CA0[1-3]|PLKO|PLPO|MAPL|ROUTING|WORK_PLAN)\b/i,
    patternType: 'source',
    remediation: 'Validate routing component assignments. Check production version consistency.',
  },

  // ── Document Management ──────────────────────────────────────
  {
    id: 'SIMPL-PLM-004',
    title: 'Document Management System (DMS)',
    description: 'DMS (CV01-CV04) continues but document-info-record links to materials need validation.',
    severity: 'medium',
    category: 'PLM – Document Management',
    sNote: '2270859',
    pattern: /\b(CV0[1-4]N?|DRAW|DRAS|DRAT|DMS_DOC)\b/i,
    patternType: 'source',
    remediation: 'Validate DMS document links to materials, equipment, and BOM items.',
  },
  {
    id: 'SIMPL-PLM-005',
    title: 'Classification System Impact',
    description: 'Classification (CL01-CL04) characteristics and classes impacted by data model changes.',
    severity: 'medium',
    category: 'PLM – Classification',
    sNote: '2270859',
    pattern: /\b(CL0[1-4]|CT0[1-4]|CABN|CAWN|CLASSIFICATION)\b/i,
    patternType: 'source',
    remediation: 'Review classification hierarchies. Validate class assignments for migrated materials.',
  },

  // ── Recipe Management ────────────────────────────────────────
  {
    id: 'SIMPL-PLM-006',
    title: 'Recipe Management for Process Industries',
    description: 'Recipe management (C201-C203) impacted by routing and BOM changes in S/4HANA.',
    severity: 'high',
    category: 'PLM – Recipe',
    sNote: '2270859',
    pattern: /\b(C20[1-3]|MASTER_RECIPE|PLKO.*RECIPE)\b/i,
    patternType: 'source',
    remediation: 'Validate master recipes after BOM and routing migration. Check phase/operation assignments.',
  },

  // ── Product Structure ────────────────────────────────────────
  {
    id: 'SIMPL-PLM-007',
    title: 'Product Structure Browser Changed',
    description: 'Product structure browser (CS80/CC05) enhanced in S/4HANA. Custom exits need review.',
    severity: 'low',
    category: 'PLM – Product Structure',
    sNote: '2270859',
    pattern: /\b(CS80|CC05|PRODUCT_STRUCTURE|PSB_)\b/i,
    patternType: 'source',
    remediation: 'Review custom enhancements to product structure browser. Test navigation after migration.',
  },
  {
    id: 'SIMPL-PLM-008',
    title: 'Variant Configuration Integration',
    description: 'Variant configuration (CU41-CU44) dependencies and object characteristics need review.',
    severity: 'medium',
    category: 'PLM – Variant Config',
    sNote: '2270859',
    pattern: /\b(CU4[1-4]|VARIANT_CONFIG|VC_|CUOBJ|DEPENDENCY)\b/i,
    patternType: 'source',
    remediation: 'Validate variant configuration models and dependencies. Test configuration profiles end-to-end.',
  },

  // ── Multi-Level BOM Management ───────────────────────────────
  {
    id: 'SIMPL-PLM-009',
    title: 'Multi-Level BOM Explosion Validation',
    description: 'Multi-level BOM explosion (CS11/CS12/CS13) must be validated after migration. Recursive BOM traversal may be affected by 40-char material numbers and changed effectivity date handling in S/4HANA.',
    severity: 'high',
    category: 'PLM – BOM',
    sNote: '2270859',
    pattern: /\b(CS1[1-3]|MULTI_LEVEL_BOM|BOM_EXPLOSION|BOM_RECURSIVE)\b/i,
    patternType: 'source',
    remediation: 'Test multi-level BOM explosion reports. Validate all levels resolve correctly with 40-char material numbers.',
  },
  {
    id: 'SIMPL-PLM-010',
    title: 'Alternative BOM and BOM Usage Migration',
    description: 'Alternative BOMs (multiple BOMs per material with different usage types: production, engineering, costing) must be validated. BOM usage determination and alternative selection logic may reference changed fields.',
    severity: 'high',
    category: 'PLM – BOM',
    sNote: '2270859',
    pattern: /\b(ALT_BOM|BOM_USAGE|STKO_STLAN|BOM_SELECT|USAGE_TYPE)\b/i,
    patternType: 'source',
    remediation: 'Validate alternative BOM assignments and usage types. Test BOM selection logic in production orders and costing runs.',
  },
  {
    id: 'SIMPL-PLM-011',
    title: 'Phantom Assembly BOM Processing',
    description: 'Phantom assembly BOMs (items with special procurement key for phantom assembly) must be validated. Phantom item explosion in production orders and MRP depends on correct BOM item category configuration.',
    severity: 'medium',
    category: 'PLM – BOM',
    sNote: '2270859',
    pattern: /\b(PHANTOM_BOM|PHANTOM_ASSY|BOM_ITEM_CAT|SOBSL.*PHANTOM)\b/i,
    patternType: 'source',
    remediation: 'Validate phantom assembly BOM items. Test explosion behavior in production orders and MRP planning runs.',
  },
  {
    id: 'SIMPL-PLM-012',
    title: 'BOM Change History and Effectivity',
    description: 'BOM change history with engineering change number (ECN) effectivity must persist through migration. Date-effective and parameter-effective BOMs require validation of effectivity resolution.',
    severity: 'high',
    category: 'PLM – BOM',
    sNote: '2270859',
    pattern: /\b(BOM_HISTORY|BOM_EFFECTIV|ECN_EFFECTIV|PARAM_EFFECT)\b/i,
    patternType: 'source',
    remediation: 'Validate BOM change history migration. Test date and parameter effectivity resolution for historical and future changes.',
  },

  // ── Routing Management ───────────────────────────────────────
  {
    id: 'SIMPL-PLM-013',
    title: 'Reference Operation Sets Migration',
    description: 'Reference operation sets (CA11-CA13) providing reusable operation templates for routings must be validated. Referenced operations in task lists need material number field verification.',
    severity: 'medium',
    category: 'PLM – Routing',
    sNote: '2270859',
    pattern: /\b(CA1[1-3]|REF_OPER|REFERENCE_OPR|PLKO.*REF)\b/i,
    patternType: 'source',
    remediation: 'Validate reference operation sets. Ensure referenced operations resolve correctly in dependent routings.',
  },
  {
    id: 'SIMPL-PLM-014',
    title: 'Rate Routing and Repetitive Manufacturing',
    description: 'Rate routings for repetitive manufacturing (line-based production) must be validated. Rate routing assignments to production lines and planned cycle times need verification after migration.',
    severity: 'medium',
    category: 'PLM – Routing',
    sNote: '2270859',
    pattern: /\b(RATE_ROUTING|REPETITIVE_MFG|PROD_LINE|CYCLE_TIME)\b/i,
    patternType: 'source',
    remediation: 'Validate rate routing configurations. Test repetitive manufacturing run schedule headers and backflush processing.',
  },
  {
    id: 'SIMPL-PLM-015',
    title: 'Routing Production Version Assignment',
    description: 'Production versions linking BOM alternatives to routing groups must be validated. Selection logic for production version determination in production orders and MRP requires testing.',
    severity: 'high',
    category: 'PLM – Routing',
    sNote: '2270859',
    pattern: /\b(PROD_VERSION|MKAL|C223|VERSION_SELECT|ROUTING_GROUP)\b/i,
    patternType: 'source',
    remediation: 'Validate production version assignments. Test version selection in production order creation and MRP planning.',
  },
  {
    id: 'SIMPL-PLM-016',
    title: 'Work Center and Capacity Validation',
    description: 'Work centers (CR01-CR03) referenced in routings must be validated for capacity planning. Work center hierarchies, available capacity formulas, and cost center assignments may be impacted.',
    severity: 'medium',
    category: 'PLM – Routing',
    sNote: '2270859',
    pattern: /\b(CR0[1-3]|WORK_CENTER|CRHD|CAPACITY_PLAN|WC_HIERARCHY)\b/i,
    patternType: 'source',
    remediation: 'Validate work center master data and capacity formulas. Test capacity evaluation and scheduling after migration.',
  },

  // ── Configuration Profiles and Dependencies ──────────────────
  {
    id: 'SIMPL-PLM-017',
    title: 'Configuration Profile Validation',
    description: 'Configuration profiles defining allowed characteristic value combinations for configurable materials must be validated. Profile assignments to material, BOM, and routing need comprehensive testing.',
    severity: 'high',
    category: 'PLM – Variant Config',
    sNote: '2270859',
    pattern: /\b(CONFIG_PROFILE|CU41|CU42|PROFILE_ASSIGN|CHAR_VALUE)\b/i,
    patternType: 'source',
    remediation: 'Validate configuration profiles. Test characteristic value assignment and dependency resolution end-to-end.',
  },
  {
    id: 'SIMPL-PLM-018',
    title: 'Dependency Rules and Constraints',
    description: 'Variant configuration dependency rules (preconditions, selection conditions, procedures, constraints) must be validated. Complex dependency nets referencing table lookups or class hierarchies need testing.',
    severity: 'high',
    category: 'PLM – Variant Config',
    sNote: '2270859',
    pattern: /\b(DEPEND_RULE|PRECONDITION|SEL_CONDITION|CONSTRAINT_NET)\b/i,
    patternType: 'source',
    remediation: 'Test all dependency rules. Validate preconditions, selection conditions, and constraint nets for configurable products.',
  },
  {
    id: 'SIMPL-PLM-019',
    title: 'Super BOM and Super Routing for Configurable Products',
    description: 'Super BOM (maximum BOM with all variant components) and super routing (all variant operations) for configurable materials must be validated. Object dependency assignments to BOM items and routing operations need testing.',
    severity: 'high',
    category: 'PLM – Variant Config',
    sNote: '2270859',
    pattern: /\b(SUPER_BOM|SUPER_ROUTING|MAX_BOM|VARIANT_COMP|OBJ_DEPEND)\b/i,
    patternType: 'source',
    remediation: 'Validate super BOM and super routing structures. Test object dependency-driven component and operation selection.',
  },

  // ── Product Compliance and Substance Management ──────────────
  {
    id: 'SIMPL-PLM-020',
    title: 'Product Compliance Assessment',
    description: 'Product compliance assessments (REACH, RoHS, Prop 65, TSCA) must be validated with S/4HANA product master. Compliance status determination and regulatory list screening depend on correct material classification.',
    severity: 'high',
    category: 'PLM – Compliance',
    sNote: '2270859',
    pattern: /\b(PROD_COMPLIANCE|REACH_REG|ROHS_CHECK|PROP_65|TSCA_LIST)\b/i,
    patternType: 'source',
    remediation: 'Validate product compliance assessments. Ensure regulatory list screening works with 40-char material numbers.',
  },
  {
    id: 'SIMPL-PLM-021',
    title: 'Substance Volume Tracking and SVHC',
    description: 'Substance volume tracking (SVT) for REACH registration obligations and SVHC (Substances of Very High Concern) identification must be validated. BOM-based substance content calculation requires correct component data.',
    severity: 'medium',
    category: 'PLM – Compliance',
    sNote: '2270859',
    pattern: /\b(SUBSTANCE_VOL|SVHC|SVT_TRACK|REACH_REGISTER|SUBSTANCE_MGMT)\b/i,
    patternType: 'source',
    remediation: 'Validate substance volume tracking calculations. Test SVHC identification through BOM-based substance content analysis.',
  },
  {
    id: 'SIMPL-PLM-022',
    title: 'Safety Data Sheet (SDS) Generation',
    description: 'Safety data sheet generation and distribution linked to product/substance master data must be validated. SDS templates referencing material classification and hazard data need verification.',
    severity: 'medium',
    category: 'PLM – Compliance',
    sNote: '2270859',
    pattern: /\b(SAFETY_DATA|SDS_GEN|MSDS|HAZARD_CLASS|SDS_DISTRIB)\b/i,
    patternType: 'source',
    remediation: 'Validate SDS generation. Test hazard classification data and SDS template rendering after material migration.',
  },

  // ── Engineering Record and Change Workflow ───────────────────
  {
    id: 'SIMPL-PLM-023',
    title: 'Engineering Record Management',
    description: 'Engineering records (CC31/CC32/CC33) linking changes to affected objects (BOMs, routings, materials, documents) must be validated. Record-to-object references may be impacted by 40-char material numbers.',
    severity: 'medium',
    category: 'PLM – Engineering Change',
    sNote: '2270859',
    pattern: /\b(CC3[1-3]|ENG_RECORD|CHANGE_RECORD|AENR_RECORD)\b/i,
    patternType: 'source',
    remediation: 'Validate engineering record object references. Test change record navigation to affected BOMs, routings, and materials.',
  },
  {
    id: 'SIMPL-PLM-024',
    title: 'ECM Workflow and Approval Process',
    description: 'Engineering change management workflows (approval chains, digital signatures, release strategies) must be validated. SAP Business Workflow integration for ECM approval routing may need reconfiguration.',
    severity: 'medium',
    category: 'PLM – Engineering Change',
    sNote: '2270859',
    pattern: /\b(ECM_WORKFLOW|ECM_APPROVAL|ECM_RELEASE|CHANGE_WORKFLOW|DIGITAL_SIGN)\b/i,
    patternType: 'source',
    remediation: 'Validate ECM workflow configurations. Test approval chains and release strategies for engineering change orders.',
  },
  {
    id: 'SIMPL-PLM-025',
    title: 'Revision Level Management',
    description: 'Material revision levels tracking design iterations must be validated. Revision level assignments to BOMs and routings with effectivity control need verification after migration.',
    severity: 'medium',
    category: 'PLM – Engineering Change',
    sNote: '2270859',
    pattern: /\b(REVISION_LEVEL|REV_LEVEL|MARA_REVLV|DESIGN_ITER)\b/i,
    patternType: 'source',
    remediation: 'Validate revision level assignments. Test revision-based BOM and routing selection logic.',
  },

  // ── Integration with PP and QM ───────────────────────────────
  {
    id: 'SIMPL-PLM-026',
    title: 'PLM-PP Integration for Production Master Data',
    description: 'PLM integration with Production Planning for BOM, routing, and production version handoff must be validated. Changes in PLM (engineering BOM) flowing to PP (production BOM) require correct usage type mapping.',
    severity: 'high',
    category: 'PLM – PP Integration',
    sNote: '2270859',
    pattern: /\b(PLM_PP_INT|ENG_TO_PROD|BOM_TRANSFER|USAGE_MAP)\b/i,
    patternType: 'source',
    remediation: 'Validate PLM-to-PP data flow. Test engineering-to-production BOM transfer and production version activation.',
  },
  {
    id: 'SIMPL-PLM-027',
    title: 'PLM-QM Integration for Inspection Planning',
    description: 'PLM integration with Quality Management for inspection plan creation from routing operations must be validated. Inspection characteristics linked to BOM components and routing operations need verification.',
    severity: 'medium',
    category: 'PLM – QM Integration',
    sNote: '2270859',
    pattern: /\b(PLM_QM_INT|INSPECT_PLAN|QM_ROUTING|INSP_CHAR)\b/i,
    patternType: 'source',
    remediation: 'Validate PLM-QM integration. Test inspection plan generation from routing operations and characteristic assignment.',
  },
  {
    id: 'SIMPL-PLM-028',
    title: 'Where-Used List Validation',
    description: 'Where-used list reports (CS15) for materials, BOMs, and documents must be validated. Impact analysis for engineering changes relies on accurate where-used data across all BOM levels.',
    severity: 'medium',
    category: 'PLM – Product Structure',
    sNote: '2270859',
    pattern: /\b(CS15|WHERE_USED|IMPACT_ANAL|USAGE_LIST|CS_WHERE)\b/i,
    patternType: 'source',
    remediation: 'Validate where-used list reports. Test impact analysis accuracy for materials referenced across multi-level BOMs.',
  },
];
