/**
 * Plant Maintenance (PM) Simplification Rules
 *
 * Covers: Work order changes, notification types,
 * predictive maintenance hooks.
 */

module.exports = [
  {
    id: 'SIMPL-PM-001',
    category: 'PM - Work Orders',
    severity: 'medium',
    title: 'Maintenance order table changes',
    description: 'AUFK (order master) and AFIH (maintenance order header) have structural changes.',
    pattern: /\b(AUFK|AFIH|ILOA)\b/i,
    patternType: 'source',
    remediation: 'Review maintenance order field usage. Use CDS views or OData APIs.',
    simplificationId: 'S4TWL-PM-WO-001',
  },
  {
    id: 'SIMPL-PM-002',
    category: 'PM - Work Orders',
    severity: 'medium',
    title: 'Maintenance order BAPIs changed',
    description: 'BAPI_ALM_ORDER_* BAPIs have new parameters in S/4HANA.',
    pattern: /\bBAPI_ALM_ORDER_\w+/i,
    patternType: 'source',
    remediation: 'Review ALM BAPIs. Consider Maintenance Order OData APIs.',
    simplificationId: 'S4TWL-PM-WO-002',
  },
  {
    id: 'SIMPL-PM-003',
    category: 'PM - Notifications',
    severity: 'medium',
    title: 'Notification type changes',
    description: 'QMEL/QMIH (notification tables) have changes in S/4HANA.',
    pattern: /\b(QMEL|QMIH|QMFE|QMSM)\b/i,
    patternType: 'source',
    remediation: 'Review notification handling. Use CDS views for notification data.',
    simplificationId: 'S4TWL-PM-NOT-001',
  },
  {
    id: 'SIMPL-PM-004',
    category: 'PM - Equipment',
    severity: 'low',
    title: 'Equipment master changes',
    description: 'EQUI/EQKT (equipment master) have field changes.',
    pattern: /\b(EQUI|EQKT)\b/i,
    patternType: 'source',
    remediation: 'Review equipment master field usage.',
    simplificationId: 'S4TWL-PM-EQ-001',
  },
  {
    id: 'SIMPL-PM-005',
    category: 'PM - Functional Location',
    severity: 'low',
    title: 'Functional location changes',
    description: 'IFLOS/IFLOT (functional location) have structural changes.',
    pattern: /\b(IFLOS|IFLOT)\b/i,
    patternType: 'source',
    remediation: 'Review functional location structure.',
    simplificationId: 'S4TWL-PM-FL-001',
  },
  {
    id: 'SIMPL-PM-006',
    category: 'PM - Predictive Maintenance',
    severity: 'low',
    title: 'Predictive Maintenance integration',
    description: 'S/4HANA integrates with SAP Predictive Maintenance and Service.',
    pattern: /\bPDMS_|PREDICTIVE\b/i,
    patternType: 'source',
    remediation: 'Evaluate SAP Predictive Maintenance and Service integration.',
    simplificationId: 'S4TWL-PM-PDM-001',
  },
  {
    id: 'SIMPL-PM-007',
    category: 'PM - Maintenance Plans',
    severity: 'medium',
    title: 'Maintenance plan changes',
    description: 'MPLA/MPOS (maintenance plan/items) affected by S/4HANA changes.',
    pattern: /\b(MPLA|MPOS|MHIS)\b/i,
    patternType: 'source',
    remediation: 'Review maintenance planning configuration.',
    simplificationId: 'S4TWL-PM-MP-001',
  },
  {
    id: 'SIMPL-PM-008',
    category: 'PM - Task Lists',
    severity: 'low',
    title: 'Task list integration changes',
    description: 'Maintenance task lists (IA01/IA02) have integration changes.',
    pattern: /\b(IA01|IA02|IA03)\b/i,
    patternType: 'source',
    remediation: 'Review maintenance task list configuration.',
    simplificationId: 'S4TWL-PM-TL-001',
  },
];
