/**
 * Copyright 2024-2026 SEN Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
/**
 * Plant Maintenance (PM) Simplification Rules
 *
 * Covers: Work order changes, notification types,
 * predictive maintenance hooks, equipment, functional locations,
 * maintenance plans, maintenance orders, notifications, task lists,
 * measuring points, EAM integration, mobile maintenance.
 */

module.exports = [
  // ── Existing rules (001–008) ──────────────────────────────────────────

  {
    id: 'SIMPL-PM-001',
    category: 'PM - Work Orders',
    severity: 'medium',
    title: 'Maintenance order table changes',
    description: 'AUFK (order master) and AFIH (maintenance order header) have structural changes.',
    pattern: /\b(AUFK|AFIH|ILOA)\b/i,
    patternType: 'source',
    remediation: 'Review maintenance order field usage. Use CDS views or OData APIs.',
    simplificationId: 'S4TWL-PM-WO-001',
  },
  {
    id: 'SIMPL-PM-002',
    category: 'PM - Work Orders',
    severity: 'medium',
    title: 'Maintenance order BAPIs changed',
    description: 'BAPI_ALM_ORDER_* BAPIs have new parameters in S/4HANA.',
    pattern: /\bBAPI_ALM_ORDER_\w+/i,
    patternType: 'source',
    remediation: 'Review ALM BAPIs. Consider Maintenance Order OData APIs.',
    simplificationId: 'S4TWL-PM-WO-002',
  },
  {
    id: 'SIMPL-PM-003',
    category: 'PM - Notifications',
    severity: 'medium',
    title: 'Notification type changes',
    description: 'QMEL/QMIH (notification tables) have changes in S/4HANA.',
    pattern: /\b(QMEL|QMIH|QMFE|QMSM)\b/i,
    patternType: 'source',
    remediation: 'Review notification handling. Use CDS views for notification data.',
    simplificationId: 'S4TWL-PM-NOT-001',
  },
  {
    id: 'SIMPL-PM-004',
    category: 'PM - Equipment',
    severity: 'low',
    title: 'Equipment master changes',
    description: 'EQUI/EQKT (equipment master) have field changes.',
    pattern: /\b(EQUI|EQKT)\b/i,
    patternType: 'source',
    remediation: 'Review equipment master field usage.',
    simplificationId: 'S4TWL-PM-EQ-001',
  },
  {
    id: 'SIMPL-PM-005',
    category: 'PM - Functional Location',
    severity: 'low',
    title: 'Functional location changes',
    description: 'IFLOS/IFLOT (functional location) have structural changes.',
    pattern: /\b(IFLOS|IFLOT)\b/i,
    patternType: 'source',
    remediation: 'Review functional location structure.',
    simplificationId: 'S4TWL-PM-FL-001',
  },
  {
    id: 'SIMPL-PM-006',
    category: 'PM - Predictive Maintenance',
    severity: 'low',
    title: 'Predictive Maintenance integration',
    description: 'S/4HANA integrates with SAP Predictive Maintenance and Service.',
    pattern: /\bPDMS_|PREDICTIVE\b/i,
    patternType: 'source',
    remediation: 'Evaluate SAP Predictive Maintenance and Service integration.',
    simplificationId: 'S4TWL-PM-PDM-001',
  },
  {
    id: 'SIMPL-PM-007',
    category: 'PM - Maintenance Plans',
    severity: 'medium',
    title: 'Maintenance plan changes',
    description: 'MPLA/MPOS (maintenance plan/items) affected by S/4HANA changes.',
    pattern: /\b(MPLA|MPOS|MHIS)\b/i,
    patternType: 'source',
    remediation: 'Review maintenance planning configuration.',
    simplificationId: 'S4TWL-PM-MP-001',
  },
  {
    id: 'SIMPL-PM-008',
    category: 'PM - Task Lists',
    severity: 'low',
    title: 'Task list integration changes',
    description: 'Maintenance task lists (IA01/IA02) have integration changes.',
    pattern: /\b(IA01|IA02|IA03)\b/i,
    patternType: 'source',
    remediation: 'Review maintenance task list configuration.',
    simplificationId: 'S4TWL-PM-TL-001',
  },

  // ── Equipment / Functional Locations Extended (009–014) ───────────────

  {
    id: 'SIMPL-PM-009',
    category: 'PM - Equipment',
    severity: 'medium',
    title: 'Equipment BAPIs changed',
    description: 'BAPI_EQUI_CREATE/CHANGE have new parameters and structure changes in S/4HANA.',
    pattern: /\bBAPI_EQUI_\w+/i,
    patternType: 'source',
    remediation: 'Review equipment BAPIs. Consider API_EQUIPMENT_SRV OData service.',
    simplificationId: 'S4TWL-PM-EQ-002',
  },
  {
    id: 'SIMPL-PM-010',
    category: 'PM - Equipment',
    severity: 'medium',
    title: 'Equipment hierarchy changes (IE01/IE02)',
    description: 'Equipment hierarchy and installation (IE01/IE02) have S/4HANA Fiori replacements.',
    pattern: /\b(IE01|IE02|IE03)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Manage Equipment or Technical Object OData API.',
    simplificationId: 'S4TWL-PM-EQ-003',
  },
  {
    id: 'SIMPL-PM-011',
    category: 'PM - Equipment',
    severity: 'low',
    title: 'Equipment classification data',
    description: 'Equipment classification (CL20N/CL02) integrates with new classification APIs.',
    pattern: /\b(CL20N|CL02|AUSP|CABN)\b.*EQU/i,
    patternType: 'source',
    remediation: 'Review classification access for equipment. Use classification CDS views.',
    simplificationId: 'S4TWL-PM-EQ-004',
  },
  {
    id: 'SIMPL-PM-012',
    category: 'PM - Functional Location',
    severity: 'medium',
    title: 'Functional location BAPIs changed',
    description: 'BAPI_FUNCLOC_CREATE/CHANGE have parameter changes in S/4HANA.',
    pattern: /\bBAPI_FUNCLOC_\w+/i,
    patternType: 'source',
    remediation: 'Review functional location BAPIs. Consider API_FUNCTIONALLOCATION_SRV.',
    simplificationId: 'S4TWL-PM-FL-002',
  },
  {
    id: 'SIMPL-PM-013',
    category: 'PM - Functional Location',
    severity: 'medium',
    title: 'Functional location hierarchy (IL01/IL02)',
    description: 'Functional location hierarchy management (IL01/IL02) has Fiori replacements.',
    pattern: /\b(IL01|IL02|IL03)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Manage Functional Locations for hierarchy management.',
    simplificationId: 'S4TWL-PM-FL-003',
  },
  {
    id: 'SIMPL-PM-014',
    category: 'PM - Functional Location',
    severity: 'low',
    title: 'Linear asset management',
    description: 'Linear asset management for functional locations has S/4HANA enhancements.',
    pattern: /\bILINEAR\b|LINEAR_ASSET/i,
    patternType: 'source',
    remediation: 'Evaluate linear asset management features in S/4HANA for infrastructure assets.',
    simplificationId: 'S4TWL-PM-FL-004',
  },

  // ── Maintenance Plans Extended (015–019) ──────────────────────────────

  {
    id: 'SIMPL-PM-015',
    category: 'PM - Maintenance Plans',
    severity: 'medium',
    title: 'Maintenance plan scheduling (IP10/IP30)',
    description: 'Maintenance plan scheduling (IP10/IP30) has performance improvements in S/4HANA.',
    pattern: /\b(IP10|IP30|IP19)\b/i,
    patternType: 'source',
    remediation: 'Review scheduling parameters. IP30 supports parallel processing in S/4HANA.',
    simplificationId: 'S4TWL-PM-MP-002',
  },
  {
    id: 'SIMPL-PM-016',
    category: 'PM - Maintenance Plans',
    severity: 'medium',
    title: 'Maintenance strategy changes',
    description: 'Maintenance strategies and packages may need review for S/4HANA compatibility.',
    pattern: /\b(IP11|IP12)\b|STRATEGY_PLAN/i,
    patternType: 'source',
    remediation: 'Review maintenance strategies. Ensure scheduling indicators are correctly configured.',
    simplificationId: 'S4TWL-PM-MP-003',
  },
  {
    id: 'SIMPL-PM-017',
    category: 'PM - Maintenance Plans',
    severity: 'low',
    title: 'Multiple counter plan support',
    description: 'Multiple counter-based maintenance plans have enhanced support in S/4HANA.',
    pattern: /\bMULTI_COUNTER\b|MULTI.*COUNTER.*PLAN/i,
    patternType: 'source',
    remediation: 'Evaluate multiple counter plan feature for condition-based maintenance.',
    simplificationId: 'S4TWL-PM-MP-004',
  },
  {
    id: 'SIMPL-PM-018',
    category: 'PM - Maintenance Plans',
    severity: 'medium',
    title: 'Maintenance plan call objects',
    description: 'Maintenance plan call objects (maintenance orders, service entries) have S/4HANA changes.',
    pattern: /\bMPOS\b.*\bCALL_OBJ\b|MAINTENANCE_CALL/i,
    patternType: 'source',
    remediation: 'Review maintenance plan call object generation and assignment.',
    simplificationId: 'S4TWL-PM-MP-005',
  },
  {
    id: 'SIMPL-PM-019',
    category: 'PM - Maintenance Plans',
    severity: 'medium',
    title: 'Maintenance plan Fiori apps',
    description: 'S/4HANA provides Fiori apps for maintenance plan management replacing IP01/IP02.',
    pattern: /\b(IP01|IP02|IP03)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Manage Maintenance Plans for plan creation and management.',
    simplificationId: 'S4TWL-PM-MP-006',
  },

  // ── Maintenance Orders Extended (020–024) ─────────────────────────────

  {
    id: 'SIMPL-PM-020',
    category: 'PM - Work Orders',
    severity: 'medium',
    title: 'Maintenance order operations (IW32/IW33)',
    description: 'Maintenance order operation management has new Fiori apps in S/4HANA.',
    pattern: /\b(IW32|IW33|IW31)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Maintain Maintenance Order for order processing.',
    simplificationId: 'S4TWL-PM-WO-003',
  },
  {
    id: 'SIMPL-PM-021',
    category: 'PM - Work Orders',
    severity: 'medium',
    title: 'Maintenance order confirmation (IW42/IW45)',
    description: 'Time and activity confirmations for maintenance orders have S/4HANA changes.',
    pattern: /\b(IW42|IW45|IW41)\b/i,
    patternType: 'source',
    remediation: 'Review confirmation process. Use Fiori app Confirm Maintenance Order.',
    simplificationId: 'S4TWL-PM-WO-004',
  },
  {
    id: 'SIMPL-PM-022',
    category: 'PM - Work Orders',
    severity: 'medium',
    title: 'Maintenance order settlement (KO88)',
    description: 'Maintenance order settlement integrates with Universal Journal (ACDOCA) in S/4HANA.',
    pattern: /\bKO88\b.*PM|IW88\b/i,
    patternType: 'source',
    remediation: 'Review settlement rules. Costs post to ACDOCA in S/4HANA.',
    simplificationId: 'S4TWL-PM-WO-005',
  },
  {
    id: 'SIMPL-PM-023',
    category: 'PM - Work Orders',
    severity: 'low',
    title: 'Maintenance order spare parts',
    description: 'Spare part planning and reservation in maintenance orders has S/4HANA enhancements.',
    pattern: /\bSPARE_PART\b|RESB\b.*PM/i,
    patternType: 'source',
    remediation: 'Review spare parts integration. Material reservations link to new material doc tables.',
    simplificationId: 'S4TWL-PM-WO-006',
  },
  {
    id: 'SIMPL-PM-024',
    category: 'PM - Work Orders',
    severity: 'medium',
    title: 'Maintenance order list (IW38/IW39)',
    description: 'Maintenance order list reports (IW38/IW39) have Fiori app replacements.',
    pattern: /\b(IW38|IW39|IW29)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Monitor Maintenance Orders for order list and analytics.',
    simplificationId: 'S4TWL-PM-WO-007',
  },

  // ── Notifications Extended (025–028) ──────────────────────────────────

  {
    id: 'SIMPL-PM-025',
    category: 'PM - Notifications',
    severity: 'medium',
    title: 'Notification creation BAPIs',
    description: 'BAPI_ALM_NOTIF_CREATE/DATA_ADD have parameter changes in S/4HANA.',
    pattern: /\bBAPI_ALM_NOTIF_\w+/i,
    patternType: 'source',
    remediation: 'Review notification BAPIs. Consider API_MAINTNOTIFICATION OData service.',
    simplificationId: 'S4TWL-PM-NOT-002',
  },
  {
    id: 'SIMPL-PM-026',
    category: 'PM - Notifications',
    severity: 'medium',
    title: 'Notification catalog management',
    description: 'Damage/cause/activity catalogs (QS41) have S/4HANA configuration changes.',
    pattern: /\b(QS41|QPCT|QPCD|QPGR)\b/i,
    patternType: 'source',
    remediation: 'Review notification catalogs. Ensure code groups and codes are S/4HANA compatible.',
    simplificationId: 'S4TWL-PM-NOT-003',
  },
  {
    id: 'SIMPL-PM-027',
    category: 'PM - Notifications',
    severity: 'medium',
    title: 'Notification processing Fiori apps (IW21/IW22)',
    description: 'Notification creation and processing (IW21/IW22/IW23) have Fiori replacements.',
    pattern: /\b(IW21|IW22|IW23)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Create Maintenance Notification or My Maintenance Notifications.',
    simplificationId: 'S4TWL-PM-NOT-004',
  },
  {
    id: 'SIMPL-PM-028',
    category: 'PM - Notifications',
    severity: 'low',
    title: 'Notification list and reporting (IW28/IW29)',
    description: 'Notification list reports (IW28/IW29) have Fiori analytical app replacements.',
    pattern: /\b(IW28|IW29)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Monitor Maintenance Notifications for listing and analytics.',
    simplificationId: 'S4TWL-PM-NOT-005',
  },

  // ── Task Lists / Measuring Points (029–032) ──────────────────────────

  {
    id: 'SIMPL-PM-029',
    category: 'PM - Task Lists',
    severity: 'medium',
    title: 'Task list operation changes',
    description: 'Maintenance task list operations and sub-operations have S/4HANA updates.',
    pattern: /\b(IA05|IA06|IA07|PLPO)\b.*PM/i,
    patternType: 'source',
    remediation: 'Review maintenance task list operations. Validate operation detail assignments.',
    simplificationId: 'S4TWL-PM-TL-002',
  },
  {
    id: 'SIMPL-PM-030',
    category: 'PM - Measuring Points',
    severity: 'medium',
    title: 'Measuring point and counter management',
    description: 'Measuring points and counters (IK01/IK11) have S/4HANA enhancements.',
    pattern: /\b(IK01|IK11|IK07|IMPTT|IMRG)\b/i,
    patternType: 'source',
    remediation: 'Review measuring point configuration. Use Fiori app for measurement documents.',
    simplificationId: 'S4TWL-PM-MP-007',
  },
  {
    id: 'SIMPL-PM-031',
    category: 'PM - Measuring Points',
    severity: 'medium',
    title: 'Measurement document BAPIs',
    description: 'BAPI_MEASUREDOC_CREATE and measurement reading BAPIs have S/4HANA changes.',
    pattern: /\bBAPI_MEASUREDOC_\w+/i,
    patternType: 'source',
    remediation: 'Review measurement BAPIs. Consider measurement OData APIs for Fiori integration.',
    simplificationId: 'S4TWL-PM-MP-008',
  },
  {
    id: 'SIMPL-PM-032',
    category: 'PM - Measuring Points',
    severity: 'low',
    title: 'Counter-based maintenance triggers',
    description: 'Counter-based maintenance scheduling from measurement readings has S/4HANA enhancements.',
    pattern: /\bCOUNTER_BASED\b|COUNTER.*MAINTENANCE/i,
    patternType: 'source',
    remediation: 'Review counter-based maintenance plan integration with measuring points.',
    simplificationId: 'S4TWL-PM-MP-009',
  },

  // ── EAM Integration (033–035) ─────────────────────────────────────────

  {
    id: 'SIMPL-PM-033',
    category: 'PM - EAM',
    severity: 'high',
    title: 'Enterprise Asset Management (EAM) integration',
    description: 'S/4HANA EAM extends classic PM with asset health, risk assessment, and analytics.',
    pattern: /\bEAM_\w+|ASSET_HEALTH\b/i,
    patternType: 'source',
    remediation: 'Evaluate S/4HANA EAM capabilities: asset health monitoring, risk-based maintenance.',
    simplificationId: 'S4TWL-PM-EAM-001',
  },
  {
    id: 'SIMPL-PM-034',
    category: 'PM - EAM',
    severity: 'medium',
    title: 'Warranty management in EAM',
    description: 'Warranty management for equipment has new features in S/4HANA EAM.',
    pattern: /\bWARRANTY\b|BGMK\b|WARRANTY_CLAIM/i,
    patternType: 'source',
    remediation: 'Review warranty claim processing. S/4HANA provides integrated warranty management.',
    simplificationId: 'S4TWL-PM-EAM-002',
  },
  {
    id: 'SIMPL-PM-035',
    category: 'PM - EAM',
    severity: 'medium',
    title: 'Permit and safety integration',
    description: 'Work permits and safety management integrated with maintenance orders in S/4HANA.',
    pattern: /\bWORK_PERMIT\b|SAFETY_CERT\b|LOCK_TAG/i,
    patternType: 'source',
    remediation: 'Evaluate work permit integration for maintenance order safety management.',
    simplificationId: 'S4TWL-PM-EAM-003',
  },

  // ── Mobile Maintenance (036–038) ──────────────────────────────────────

  {
    id: 'SIMPL-PM-036',
    category: 'PM - Mobile Maintenance',
    severity: 'medium',
    title: 'Mobile maintenance apps (SAP Asset Manager)',
    description: 'SAP Asset Manager replaces SAP Work Manager for offline mobile maintenance.',
    pattern: /\bWORK_MANAGER\b|SAP_ASSET_MANAGER\b|MOBILE_PM/i,
    patternType: 'source',
    remediation: 'Migrate from SAP Work Manager to SAP Asset Manager for mobile maintenance.',
    simplificationId: 'S4TWL-PM-MOB-001',
  },
  {
    id: 'SIMPL-PM-037',
    category: 'PM - Mobile Maintenance',
    severity: 'low',
    title: 'Fiori mobile maintenance apps',
    description: 'S/4HANA provides Fiori apps for mobile maintenance order and notification processing.',
    pattern: /\bFIORI\b.*\b(MAINTENANCE|PM)\b|MY_MAINTENANCE/i,
    patternType: 'source',
    remediation: 'Deploy Fiori apps: My Maintenance Notifications, My Maintenance Orders for mobile use.',
    simplificationId: 'S4TWL-PM-MOB-002',
  },
  {
    id: 'SIMPL-PM-038',
    category: 'PM - Mobile Maintenance',
    severity: 'low',
    title: 'Barcode/RFID integration for equipment',
    description: 'Equipment identification via barcode/RFID has enhanced integration in S/4HANA.',
    pattern: /\bBARCODE\b.*EQUI|RFID.*EQUI/i,
    patternType: 'source',
    remediation: 'Leverage barcode/RFID scanning in SAP Asset Manager for equipment identification.',
    simplificationId: 'S4TWL-PM-MOB-003',
  },

  // ── Predictive Maintenance Extended (039–040) ─────────────────────────

  {
    id: 'SIMPL-PM-039',
    category: 'PM - Predictive Maintenance',
    severity: 'medium',
    title: 'IoT sensor data integration',
    description: 'SAP IoT integration enables sensor-based maintenance triggers in S/4HANA.',
    pattern: /\bIOT_\w+|SENSOR_DATA\b|SAP_IOT/i,
    patternType: 'source',
    remediation: 'Evaluate SAP IoT services for condition-based and predictive maintenance scenarios.',
    simplificationId: 'S4TWL-PM-PDM-002',
  },
  {
    id: 'SIMPL-PM-040',
    category: 'PM - Predictive Maintenance',
    severity: 'medium',
    title: 'Machine learning anomaly detection',
    description: 'S/4HANA integrates with SAP AI for anomaly detection on equipment sensor data.',
    pattern: /\bANOMALY_DETECT\b|ML_MAINTENANCE\b|PREDICTIVE_SCORE/i,
    patternType: 'source',
    remediation: 'Evaluate SAP AI/ML capabilities for predictive maintenance scoring and alerting.',
    simplificationId: 'S4TWL-PM-PDM-003',
  },
];
