/**
 * Production Planning (PP) Simplification Rules
 *
 * Covers: Production order changes, MRP Live, demand-driven MRP,
 * capacity planning.
 */

module.exports = [
  {
    id: 'SIMPL-PP-001',
    category: 'PP - Production Orders',
    severity: 'medium',
    title: 'Production order table changes',
    description: 'AFKO/AFPO (production order header/items) have structural changes.',
    pattern: /\b(AFKO|AFPO|AFVC|AFFL)\b/i,
    patternType: 'source',
    remediation: 'Review production order field usage. Use CDS views or OData APIs.',
    simplificationId: 'S4TWL-PP-PO-001',
  },
  {
    id: 'SIMPL-PP-002',
    category: 'PP - Production Orders',
    severity: 'medium',
    title: 'Production order BAPI changes',
    description: 'BAPI_PRODORD_CREATE has changed parameters in S/4HANA.',
    pattern: /\bBAPI_PRODORD_\w+/i,
    patternType: 'source',
    remediation: 'Review production order BAPIs. Consider API_PRODUCTION_ORDER_2_SRV.',
    simplificationId: 'S4TWL-PP-PO-002',
  },
  {
    id: 'SIMPL-PP-003',
    category: 'PP - MRP',
    severity: 'high',
    title: 'MRP Live replaces classic MRP',
    description: 'MD01/MD02 classic MRP replaced by MRP Live for improved performance.',
    pattern: /\b(MD01|MD02)\b(?!N)/i,
    patternType: 'source',
    remediation: 'Migrate to MRP Live (MD01N). Review MRP exits and enhancements.',
    simplificationId: 'S4TWL-PP-MRP-001',
  },
  {
    id: 'SIMPL-PP-004',
    category: 'PP - MRP',
    severity: 'medium',
    title: 'Demand-driven MRP available',
    description: 'DDMRP for buffer-based decoupled planning available in S/4HANA.',
    pattern: /\bMD04|MDPSX\b/i,
    patternType: 'source',
    remediation: 'Evaluate DDMRP for eligible materials with high demand variability.',
    simplificationId: 'S4TWL-PP-MRP-002',
  },
  {
    id: 'SIMPL-PP-005',
    category: 'PP - Capacity Planning',
    severity: 'medium',
    title: 'Capacity planning changes',
    description: 'CM01/CM21 capacity planning has changes in S/4HANA.',
    pattern: /\b(CM01|CM21|CM25|CRHD|KAKO)\b/i,
    patternType: 'source',
    remediation: 'Review capacity planning. Consider Production Planning and Detailed Scheduling (PP/DS).',
    simplificationId: 'S4TWL-PP-CAP-001',
  },
  {
    id: 'SIMPL-PP-006',
    category: 'PP - BOM',
    severity: 'medium',
    title: 'Bill of Material changes',
    description: 'STKO/STPO (BOM header/items) have structural changes.',
    pattern: /\b(STKO|STPO|STAS)\b/i,
    patternType: 'source',
    remediation: 'Review BOM access patterns. Use CDS views or API_BILL_OF_MATERIAL_SRV.',
    simplificationId: 'S4TWL-PP-BOM-001',
  },
  {
    id: 'SIMPL-PP-007',
    category: 'PP - Routing',
    severity: 'medium',
    title: 'Routing/recipe changes',
    description: 'PLKO/PLPO (routing header/operations) affected by S/4HANA changes.',
    pattern: /\b(PLKO|PLPO|PLAS)\b/i,
    patternType: 'source',
    remediation: 'Review routing access. Use CDS views for production routing data.',
    simplificationId: 'S4TWL-PP-RTG-001',
  },
  {
    id: 'SIMPL-PP-008',
    category: 'PP - Shop Floor',
    severity: 'medium',
    title: 'Confirmation changes',
    description: 'Production order confirmations (CO11N) have new integration points.',
    pattern: /\b(CO11N|AFRU)\b/i,
    patternType: 'source',
    remediation: 'Review confirmation processes and integration points.',
    simplificationId: 'S4TWL-PP-SF-001',
  },
  {
    id: 'SIMPL-PP-009',
    category: 'PP - Process Orders',
    severity: 'medium',
    title: 'Process order changes',
    description: 'Process industry orders (COR1/COR2) have changes in S/4HANA.',
    pattern: /\b(COR1|COR2|COR3)\b/i,
    patternType: 'source',
    remediation: 'Review process order handling for S/4HANA compatibility.',
    simplificationId: 'S4TWL-PP-PI-001',
  },
];
