/**
 * Copyright 2024-2026 SEN Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
/**
 * Production Planning (PP) Simplification Rules
 *
 * Covers: Production order changes, MRP Live, demand-driven MRP,
 * capacity planning, shop floor, product costing, demand management,
 * repetitive manufacturing, process manufacturing, discrete manufacturing.
 */

module.exports = [
  // ── Existing rules (001–009) ──────────────────────────────────────────

  {
    id: 'SIMPL-PP-001',
    category: 'PP - Production Orders',
    severity: 'medium',
    title: 'Production order table changes',
    description: 'AFKO/AFPO (production order header/items) have structural changes.',
    pattern: /\b(AFKO|AFPO|AFVC|AFFL)\b/i,
    patternType: 'source',
    remediation: 'Review production order field usage. Use CDS views or OData APIs.',
    simplificationId: 'S4TWL-PP-PO-001',
  },
  {
    id: 'SIMPL-PP-002',
    category: 'PP - Production Orders',
    severity: 'medium',
    title: 'Production order BAPI changes',
    description: 'BAPI_PRODORD_CREATE has changed parameters in S/4HANA.',
    pattern: /\bBAPI_PRODORD_\w+/i,
    patternType: 'source',
    remediation: 'Review production order BAPIs. Consider API_PRODUCTION_ORDER_2_SRV.',
    simplificationId: 'S4TWL-PP-PO-002',
  },
  {
    id: 'SIMPL-PP-003',
    category: 'PP - MRP',
    severity: 'high',
    title: 'MRP Live replaces classic MRP',
    description: 'MD01/MD02 classic MRP replaced by MRP Live for improved performance.',
    pattern: /\b(MD01|MD02)\b(?!N)/i,
    patternType: 'source',
    remediation: 'Migrate to MRP Live (MD01N). Review MRP exits and enhancements.',
    simplificationId: 'S4TWL-PP-MRP-001',
  },
  {
    id: 'SIMPL-PP-004',
    category: 'PP - MRP',
    severity: 'medium',
    title: 'Demand-driven MRP available',
    description: 'DDMRP for buffer-based decoupled planning available in S/4HANA.',
    pattern: /\bMD04|MDPSX\b/i,
    patternType: 'source',
    remediation: 'Evaluate DDMRP for eligible materials with high demand variability.',
    simplificationId: 'S4TWL-PP-MRP-002',
  },
  {
    id: 'SIMPL-PP-005',
    category: 'PP - Capacity Planning',
    severity: 'medium',
    title: 'Capacity planning changes',
    description: 'CM01/CM21 capacity planning has changes in S/4HANA.',
    pattern: /\b(CM01|CM21|CM25|CRHD|KAKO)\b/i,
    patternType: 'source',
    remediation: 'Review capacity planning. Consider Production Planning and Detailed Scheduling (PP/DS).',
    simplificationId: 'S4TWL-PP-CAP-001',
  },
  {
    id: 'SIMPL-PP-006',
    category: 'PP - BOM',
    severity: 'medium',
    title: 'Bill of Material changes',
    description: 'STKO/STPO (BOM header/items) have structural changes.',
    pattern: /\b(STKO|STPO|STAS)\b/i,
    patternType: 'source',
    remediation: 'Review BOM access patterns. Use CDS views or API_BILL_OF_MATERIAL_SRV.',
    simplificationId: 'S4TWL-PP-BOM-001',
  },
  {
    id: 'SIMPL-PP-007',
    category: 'PP - Routing',
    severity: 'medium',
    title: 'Routing/recipe changes',
    description: 'PLKO/PLPO (routing header/operations) affected by S/4HANA changes.',
    pattern: /\b(PLKO|PLPO|PLAS)\b/i,
    patternType: 'source',
    remediation: 'Review routing access. Use CDS views for production routing data.',
    simplificationId: 'S4TWL-PP-RTG-001',
  },
  {
    id: 'SIMPL-PP-008',
    category: 'PP - Shop Floor',
    severity: 'medium',
    title: 'Confirmation changes',
    description: 'Production order confirmations (CO11N) have new integration points.',
    pattern: /\b(CO11N|AFRU)\b/i,
    patternType: 'source',
    remediation: 'Review confirmation processes and integration points.',
    simplificationId: 'S4TWL-PP-SF-001',
  },
  {
    id: 'SIMPL-PP-009',
    category: 'PP - Process Orders',
    severity: 'medium',
    title: 'Process order changes',
    description: 'Process industry orders (COR1/COR2) have changes in S/4HANA.',
    pattern: /\b(COR1|COR2|COR3)\b/i,
    patternType: 'source',
    remediation: 'Review process order handling for S/4HANA compatibility.',
    simplificationId: 'S4TWL-PP-PI-001',
  },

  // ── MRP / Planned Orders (010–015) ────────────────────────────────────

  {
    id: 'SIMPL-PP-010',
    category: 'PP - MRP',
    severity: 'high',
    title: 'MRP tables restructured (MDTB/MDKP/MDIP)',
    description: 'MRP tables MDTB, MDKP, MDIP have been restructured in S/4HANA for HANA optimization.',
    pattern: /\b(MDTB|MDKP|MDIP|MDFD)\b/i,
    patternType: 'source',
    remediation: 'Review MRP data access. Use MRP CDS views (I_MRPElement, I_PlannedOrder) instead.',
    simplificationId: 'S4TWL-PP-MRP-003',
  },
  {
    id: 'SIMPL-PP-011',
    category: 'PP - MRP',
    severity: 'medium',
    title: 'Planned order conversion changes',
    description: 'Planned order conversion to production/purchase orders has new APIs in S/4HANA.',
    pattern: /\bBAPI_PLANNEDORDER_\w+|MD_PLANNED_ORDER_\w+/i,
    patternType: 'source',
    remediation: 'Use API_PLANNED_ORDER_SRV or BAPI_PLANNEDORDER_CREATE/CHANGE with updated parameters.',
    simplificationId: 'S4TWL-PP-MRP-004',
  },
  {
    id: 'SIMPL-PP-012',
    category: 'PP - MRP',
    severity: 'medium',
    title: 'MRP area configuration changes',
    description: 'MRP areas (storage location MRP, subcontracting) have changes in S/4HANA.',
    pattern: /\b(T460A|MDLV|MDLL)\b/i,
    patternType: 'source',
    remediation: 'Review MRP area setup. Ensure storage location MRP is configured correctly.',
    simplificationId: 'S4TWL-PP-MRP-005',
  },
  {
    id: 'SIMPL-PP-013',
    category: 'PP - MRP',
    severity: 'high',
    title: 'MRP Live BAdI replaces MRP user exits',
    description: 'Classic MRP user exits (EXIT_SAPLM61X) are not called by MRP Live. Use BAdIs.',
    pattern: /\bEXIT_SAPLM61X\b|EXIT_SAPM61R\b/i,
    patternType: 'source',
    remediation: 'Migrate MRP user exits to MRP Live BAdIs (BADI_MRP_LIVE_*).',
    simplificationId: 'S4TWL-PP-MRP-006',
  },
  {
    id: 'SIMPL-PP-014',
    category: 'PP - MRP',
    severity: 'medium',
    title: 'MRP controller assignment review',
    description: 'MRP controller (DISPO) settings and exception message handling changed in MRP Live.',
    pattern: /\b(MDPS|MD05|MD06)\b/i,
    patternType: 'source',
    remediation: 'Review MRP controller settings. MD05/MD06 exception analysis uses new Fiori apps.',
    simplificationId: 'S4TWL-PP-MRP-007',
  },
  {
    id: 'SIMPL-PP-015',
    category: 'PP - MRP',
    severity: 'medium',
    title: 'Stock/requirements list changes (MD04)',
    description: 'Stock/requirements list (MD04) has a Fiori replacement: Manage Material Coverage app.',
    pattern: /\bMD04\b|MDPSX\b/i,
    patternType: 'source',
    remediation: 'Plan transition from MD04 to Fiori app F2672 (Manage Material Coverage).',
    simplificationId: 'S4TWL-PP-MRP-008',
  },

  // ── Production Orders Extended (016–020) ──────────────────────────────

  {
    id: 'SIMPL-PP-016',
    category: 'PP - Production Orders',
    severity: 'medium',
    title: 'Production order status management',
    description: 'Production order status handling (JEST/JSTO) unchanged but new statuses added.',
    pattern: /\b(JEST|JSTO|BSVX)\b/i,
    patternType: 'source',
    remediation: 'Review custom status profiles. New S/4HANA statuses may affect status logic.',
    simplificationId: 'S4TWL-PP-PO-003',
  },
  {
    id: 'SIMPL-PP-017',
    category: 'PP - Production Orders',
    severity: 'medium',
    title: 'Production order goods receipt (MIGO integration)',
    description: 'Goods receipt for production orders via MIGO has Fiori replacement.',
    pattern: /\bMIGO\b.*\b(101|102)\b|\bMB31\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Post Goods Receipt for Production Order (F1817).',
    simplificationId: 'S4TWL-PP-PO-004',
  },
  {
    id: 'SIMPL-PP-018',
    category: 'PP - Production Orders',
    severity: 'high',
    title: 'Production order settlement changes',
    description: 'Production order settlement (CO88/KO88) integrates with Universal Journal (ACDOCA).',
    pattern: /\b(CO88|KO88)\b/i,
    patternType: 'source',
    remediation: 'Review settlement rules. Settlement now posts to ACDOCA in S/4HANA.',
    simplificationId: 'S4TWL-PP-PO-005',
  },
  {
    id: 'SIMPL-PP-019',
    category: 'PP - Production Orders',
    severity: 'medium',
    title: 'Production order OData API',
    description: 'API_PRODUCTION_ORDER_2_SRV provides RESTful access to production orders.',
    pattern: /\bAPI_PRODUCTION_ORDER\b/i,
    patternType: 'source',
    remediation: 'Use API_PRODUCTION_ORDER_2_SRV for programmatic access to production orders.',
    simplificationId: 'S4TWL-PP-PO-006',
  },
  {
    id: 'SIMPL-PP-020',
    category: 'PP - Production Orders',
    severity: 'medium',
    title: 'Production order print/output changes',
    description: 'Production order output (shop papers) uses Output Management in S/4HANA.',
    pattern: /\b(NACE|TNAPR)\b.*PP|CO04N/i,
    patternType: 'source',
    remediation: 'Migrate to S/4HANA Output Management or Adobe Forms for shop floor documents.',
    simplificationId: 'S4TWL-PP-PO-007',
  },

  // ── Shop Floor (021–026) ──────────────────────────────────────────────

  {
    id: 'SIMPL-PP-021',
    category: 'PP - Shop Floor',
    severity: 'medium',
    title: 'Goods movement for production (261/262)',
    description: 'Goods issue to production orders (mvt 261/262) has new Fiori apps.',
    pattern: /\b(MB1A|MIGO)\b.*\b(261|262)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Post Goods Issue for Production Order for material staging.',
    simplificationId: 'S4TWL-PP-SF-002',
  },
  {
    id: 'SIMPL-PP-022',
    category: 'PP - Shop Floor',
    severity: 'medium',
    title: 'Backflushing configuration changes',
    description: 'Backflushing for production order components may behave differently with new material document architecture.',
    pattern: /\bBACKFLUSH\b|BACKFL\b|CO11N.*BACKFL/i,
    patternType: 'source',
    remediation: 'Review backflushing setup. MATDOC replaces MKPF/MSEG for material documents.',
    simplificationId: 'S4TWL-PP-SF-003',
  },
  {
    id: 'SIMPL-PP-023',
    category: 'PP - Shop Floor',
    severity: 'medium',
    title: 'Production confirmation BAPI changes',
    description: 'BAPI_PRODORDCONF_CREATE_TT has parameter changes in S/4HANA.',
    pattern: /\bBAPI_PRODORDCONF_\w+/i,
    patternType: 'source',
    remediation: 'Review confirmation BAPIs. Consider API_PRODORDCONF_2_SRV OData service.',
    simplificationId: 'S4TWL-PP-SF-004',
  },
  {
    id: 'SIMPL-PP-024',
    category: 'PP - Shop Floor',
    severity: 'medium',
    title: 'Shop floor control with MES integration',
    description: 'SAP Manufacturing Execution (ME/MII/DMC) integration points changed in S/4HANA.',
    pattern: /\bME_\w+|MII_\w+|PP_PDC_\w+/i,
    patternType: 'source',
    remediation: 'Review MES integration. SAP Digital Manufacturing Cloud replaces legacy MES.',
    simplificationId: 'S4TWL-PP-SF-005',
  },
  {
    id: 'SIMPL-PP-025',
    category: 'PP - Shop Floor',
    severity: 'low',
    title: 'Kanban control cycle changes',
    description: 'Kanban (PK01/PK13N) control cycles have new Fiori apps in S/4HANA.',
    pattern: /\b(PK01|PK13N|PKMC)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Manage Kanban for control cycle management and signal processing.',
    simplificationId: 'S4TWL-PP-SF-006',
  },
  {
    id: 'SIMPL-PP-026',
    category: 'PP - Shop Floor',
    severity: 'medium',
    title: 'Material document table changes (MATDOC)',
    description: 'MKPF/MSEG replaced by MATDOC as the single material document table in S/4HANA.',
    pattern: /\b(MKPF|MSEG)\b/i,
    patternType: 'source',
    remediation: 'Access material documents via MATDOC or CDS view I_MaterialDocumentItem.',
    simplificationId: 'S4TWL-PP-SF-007',
  },

  // ── Product Costing (027–031) ─────────────────────────────────────────

  {
    id: 'SIMPL-PP-027',
    category: 'PP - Product Costing',
    severity: 'high',
    title: 'Cost estimate changes (CK11N/CK40N)',
    description: 'Standard cost estimates (CK11N/CK40N) integrate with Universal Journal in S/4HANA.',
    pattern: /\b(CK11N|CK40N|CK24)\b/i,
    patternType: 'source',
    remediation: 'Review cost estimate configuration. ACDOCA integration changes costing document flow.',
    simplificationId: 'S4TWL-PP-CO-001',
  },
  {
    id: 'SIMPL-PP-028',
    category: 'PP - Product Costing',
    severity: 'high',
    title: 'WIP calculation changes (KKAO/KKA2)',
    description: 'Work-in-Process calculation posts to ACDOCA in S/4HANA.',
    pattern: /\b(KKAO|KKA2|KKAX)\b/i,
    patternType: 'source',
    remediation: 'Review WIP calculation. Results post to Universal Journal instead of COEP/COBK.',
    simplificationId: 'S4TWL-PP-CO-002',
  },
  {
    id: 'SIMPL-PP-029',
    category: 'PP - Product Costing',
    severity: 'high',
    title: 'Variance calculation changes (KKS1/KKS2)',
    description: 'Production variance calculation (KKS1/KKS2) integrates with ACDOCA.',
    pattern: /\b(KKS1|KKS2|KKS5)\b/i,
    patternType: 'source',
    remediation: 'Review variance categories and settlement. Use Fiori analytical apps for variance analysis.',
    simplificationId: 'S4TWL-PP-CO-003',
  },
  {
    id: 'SIMPL-PP-030',
    category: 'PP - Product Costing',
    severity: 'medium',
    title: 'Activity price calculation changes',
    description: 'Activity price calculation (KP26/KSPI) data flow changed with ACDOCA.',
    pattern: /\b(KP26|KSPI|KSS2)\b/i,
    patternType: 'source',
    remediation: 'Review activity type and price calculation in context of Universal Journal.',
    simplificationId: 'S4TWL-PP-CO-004',
  },
  {
    id: 'SIMPL-PP-031',
    category: 'PP - Product Costing',
    severity: 'medium',
    title: 'Material ledger / actual costing mandatory',
    description: 'Material Ledger is mandatory in S/4HANA. Actual costing activation recommended.',
    pattern: /\b(CKM3|CKMLCP|CKMLRUNPERIOD)\b/i,
    patternType: 'source',
    remediation: 'Ensure Material Ledger is activated. Plan actual costing configuration.',
    simplificationId: 'S4TWL-PP-CO-005',
  },

  // ── Demand Management (032–035) ───────────────────────────────────────

  {
    id: 'SIMPL-PP-032',
    category: 'PP - Demand Management',
    severity: 'medium',
    title: 'Planned Independent Requirements (PIR) changes',
    description: 'PIR management (MD61/MD62) has new Fiori apps and CDS views.',
    pattern: /\b(MD61|MD62|MD63|PBIM|PBED)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori app Manage Planned Independent Requirements or CDS views for PIR data.',
    simplificationId: 'S4TWL-PP-DM-001',
  },
  {
    id: 'SIMPL-PP-033',
    category: 'PP - Demand Management',
    severity: 'high',
    title: 'SOP replaced by IBP',
    description: 'Sales and Operations Planning (SOP/MC87) replaced by SAP IBP in S/4HANA.',
    pattern: /\b(MC87|MC88|MC8A|MC75)\b/i,
    patternType: 'source',
    remediation: 'Migrate from classic SOP to SAP Integrated Business Planning (IBP).',
    simplificationId: 'S4TWL-PP-DM-002',
  },
  {
    id: 'SIMPL-PP-034',
    category: 'PP - Demand Management',
    severity: 'medium',
    title: 'Demand planning integration changes',
    description: 'Classic APO Demand Planning (DP) replaced by SAP IBP for Demand.',
    pattern: /\b(APO_DP|DP_\w+|\/SAPAPO\/)\b/i,
    patternType: 'source',
    remediation: 'Migrate from APO DP to SAP IBP for Demand for advanced demand planning.',
    simplificationId: 'S4TWL-PP-DM-003',
  },
  {
    id: 'SIMPL-PP-035',
    category: 'PP - Demand Management',
    severity: 'medium',
    title: 'Forecast-based planning changes',
    description: 'Material forecast (MP30/MP38) has enhancements in S/4HANA.',
    pattern: /\b(MP30|MP38|MP39)\b/i,
    patternType: 'source',
    remediation: 'Review forecast parameters. S/4HANA provides enhanced forecasting with ML capabilities.',
    simplificationId: 'S4TWL-PP-DM-004',
  },

  // ── Capacity Planning Extended (036–038) ──────────────────────────────

  {
    id: 'SIMPL-PP-036',
    category: 'PP - Capacity Planning',
    severity: 'medium',
    title: 'Capacity leveling changes (CM21/CM22)',
    description: 'Capacity leveling (CM21/CM22) has Fiori-based scheduling board replacement.',
    pattern: /\b(CM21|CM22|CM50)\b/i,
    patternType: 'source',
    remediation: 'Evaluate Fiori scheduling board for capacity leveling and dispatching.',
    simplificationId: 'S4TWL-PP-CAP-002',
  },
  {
    id: 'SIMPL-PP-037',
    category: 'PP - Capacity Planning',
    severity: 'medium',
    title: 'Work center table changes (CRHD/CRCO)',
    description: 'Work center tables (CRHD/CRCO/KAKO) have field additions in S/4HANA.',
    pattern: /\b(CRHD|CRCO|KAKO|CR01|CR02)\b/i,
    patternType: 'source',
    remediation: 'Review work center data access. Use CDS views for work center information.',
    simplificationId: 'S4TWL-PP-CAP-003',
  },
  {
    id: 'SIMPL-PP-038',
    category: 'PP - Capacity Planning',
    severity: 'high',
    title: 'PP/DS in Embedded APO',
    description: 'PP/DS (Production Planning/Detailed Scheduling) available as embedded APO in S/4HANA.',
    pattern: /\b(\/SAPAPO\/CDPS\w+|PP_DS_|PPDS)\b/i,
    patternType: 'source',
    remediation: 'Evaluate embedded PP/DS for detailed scheduling. Replaces standalone APO PP/DS.',
    simplificationId: 'S4TWL-PP-CAP-004',
  },

  // ── Repetitive Manufacturing (039–041) ────────────────────────────────

  {
    id: 'SIMPL-PP-039',
    category: 'PP - Repetitive Manufacturing',
    severity: 'medium',
    title: 'Repetitive manufacturing planning table',
    description: 'Planning table (MF50) and run schedule headers have S/4HANA enhancements.',
    pattern: /\b(MF50|MF42|MF47|SAFK)\b/i,
    patternType: 'source',
    remediation: 'Review repetitive manufacturing setup. Use Fiori apps for planning table.',
    simplificationId: 'S4TWL-PP-RM-001',
  },
  {
    id: 'SIMPL-PP-040',
    category: 'PP - Repetitive Manufacturing',
    severity: 'medium',
    title: 'Backflush in repetitive manufacturing',
    description: 'Repetitive manufacturing backflush (MFBF) has integration with MATDOC.',
    pattern: /\bMFBF\b|MF60\b/i,
    patternType: 'source',
    remediation: 'Review backflushing for repetitive manufacturing. MATDOC replaces MKPF/MSEG.',
    simplificationId: 'S4TWL-PP-RM-002',
  },
  {
    id: 'SIMPL-PP-041',
    category: 'PP - Repetitive Manufacturing',
    severity: 'low',
    title: 'Line design and takt-based planning',
    description: 'S/4HANA supports takt-based production and line design for repetitive manufacturing.',
    pattern: /\bTAKT\b|LINE_DESIGN\b|PROD_LINE/i,
    patternType: 'source',
    remediation: 'Evaluate takt-based production planning for high-volume repetitive lines.',
    simplificationId: 'S4TWL-PP-RM-003',
  },

  // ── Process Manufacturing (042–044) ───────────────────────────────────

  {
    id: 'SIMPL-PP-042',
    category: 'PP - Process Manufacturing',
    severity: 'medium',
    title: 'Master recipe changes (C201/C202)',
    description: 'Master recipes (C201/C202) and process instructions have S/4HANA updates.',
    pattern: /\b(C201|C202|C203)\b/i,
    patternType: 'source',
    remediation: 'Review master recipe configuration. Validate process instructions for compatibility.',
    simplificationId: 'S4TWL-PP-PI-002',
  },
  {
    id: 'SIMPL-PP-043',
    category: 'PP - Process Manufacturing',
    severity: 'medium',
    title: 'Batch management changes',
    description: 'Batch management (MSC1N/MSC2N) and batch determination have S/4HANA enhancements.',
    pattern: /\b(MSC1N|MSC2N|MSC3N|MCH1|MCHA)\b/i,
    patternType: 'source',
    remediation: 'Review batch management. Use CDS views and Fiori apps for batch operations.',
    simplificationId: 'S4TWL-PP-PI-003',
  },
  {
    id: 'SIMPL-PP-044',
    category: 'PP - Process Manufacturing',
    severity: 'medium',
    title: 'Process message handling changes',
    description: 'Process messages and control recipes in process orders have S/4HANA updates.',
    pattern: /\bPROCESS_MESSAGE\b|CONTROL_RECIPE/i,
    patternType: 'source',
    remediation: 'Review process message categories and control recipe configuration.',
    simplificationId: 'S4TWL-PP-PI-004',
  },

  // ── Discrete Manufacturing Extended (045–047) ─────────────────────────

  {
    id: 'SIMPL-PP-045',
    category: 'PP - Discrete Manufacturing',
    severity: 'medium',
    title: 'Production version management',
    description: 'Production versions (C223) link BOM and routing. S/4HANA has new validations.',
    pattern: /\b(C223|C201)\b|MKAL\b/i,
    patternType: 'source',
    remediation: 'Review production version setup. Validate BOM/routing assignments.',
    simplificationId: 'S4TWL-PP-DM-005',
  },
  {
    id: 'SIMPL-PP-046',
    category: 'PP - Discrete Manufacturing',
    severity: 'low',
    title: 'Engineering change management integration',
    description: 'ECM (CC01/CC02) integration with production planning has S/4HANA changes.',
    pattern: /\b(CC01|CC02|CC03|AENR)\b/i,
    patternType: 'source',
    remediation: 'Review engineering change management integration with PP orders and BOMs.',
    simplificationId: 'S4TWL-PP-DM-006',
  },
  {
    id: 'SIMPL-PP-047',
    category: 'PP - Discrete Manufacturing',
    severity: 'medium',
    title: 'Make-to-order production changes',
    description: 'Make-to-order (MTO) production with sales order integration has S/4HANA updates.',
    pattern: /\bMTO\b|MAKE.TO.ORDER|INDIVIDUAL_PO\b/i,
    patternType: 'source',
    remediation: 'Review MTO scenarios. Sales order stock management simplified in S/4HANA.',
    simplificationId: 'S4TWL-PP-DM-007',
  },
];
