/**
 * Removed/Replaced Functionality Rules
 *
 * Covers: WM -> EWM, classic credit -> FSCM, NAST -> BRF+,
 * SAPscript -> Adobe Forms, classic MRP -> MRP Live, classic ATP -> aATP,
 * removed transactions (complete list by module), removed function modules,
 * removed programs, removed/replaced transaction codes, obsolete
 * customizing transactions, removed report painters/writers,
 * deprecated BAPIs, and more.
 */

module.exports = [
  {
    id: 'SIMPL-REM-001',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'Warehouse Management (WM) replaced by EWM',
    description: 'Classic WM (LE-WM, LAGP/LQUA tables) is removed. EWM is the replacement.',
    pattern: /\b(LAGP|LQUA|LTAP|LTBP|L_TO_CREATE)\b/i,
    patternType: 'source',
    remediation: 'Migrate to Embedded EWM or Decentralized EWM.',
    simplificationId: 'S4TWL-REM-001',
  },
  {
    id: 'SIMPL-REM-002',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'Classic credit management removed',
    description: 'FD32 and UKM tables replaced by FSCM credit management.',
    pattern: /\b(UKM_|FD32|UKMBP_CMS)\b/i,
    patternType: 'source',
    remediation: 'Migrate to SAP Credit Management (FSCM).',
    simplificationId: 'S4TWL-REM-002',
  },
  {
    id: 'SIMPL-REM-003',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'NAST output management replaced by BRF+',
    description: 'Classic output determination via NAST/condition technique replaced by BRF+.',
    pattern: /\b(NAST|TNAPR|NACH)\b/i,
    patternType: 'source',
    remediation: 'Migrate to BRF+ based output management.',
    simplificationId: 'S4TWL-REM-003',
  },
  {
    id: 'SIMPL-REM-004',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'SAPscript forms deprecated',
    description: 'SAPscript forms (OPEN_FORM/CLOSE_FORM) replaced by Adobe Forms.',
    pattern: /\b(OPEN_FORM|CLOSE_FORM|WRITE_FORM)\b/i,
    patternType: 'source',
    remediation: 'Migrate to Adobe Forms or SAP Forms Service.',
    simplificationId: 'S4TWL-REM-004',
  },
  {
    id: 'SIMPL-REM-005',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic MRP replaced by MRP Live',
    description: 'MD01/MD02 classic MRP run replaced by MRP Live for performance.',
    pattern: /\b(MD01|MD02)\b(?!N)/i,
    patternType: 'source',
    remediation: 'Migrate to MRP Live (MD01N). Review custom MRP exits.',
    simplificationId: 'S4TWL-REM-005',
  },
  {
    id: 'SIMPL-REM-006',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic ATP replaced by aATP',
    description: 'Classic ATP (availability check) replaced by advanced ATP.',
    pattern: /\bBADI_ATP_|BAPI_MATERIAL_AVAILABILITY\b/i,
    patternType: 'source',
    remediation: 'Evaluate advanced ATP (aATP) for availability checks.',
    simplificationId: 'S4TWL-REM-006',
  },
  {
    id: 'SIMPL-REM-007',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'Classic GL removed (FAGL)',
    description: 'Classic General Ledger completely replaced by S/4HANA New GL.',
    pattern: /\bFAGL_[A-Z]{2,}/i,
    patternType: 'source',
    remediation: 'All GL operations now go through ACDOCA. Review all GL access patterns.',
    simplificationId: 'S4TWL-REM-007',
  },
  {
    id: 'SIMPL-REM-008',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Travel Management replaced by Concur',
    description: 'SAP Travel Management (FI-TV) replaced by SAP Concur.',
    pattern: /\b(PTRV_|PR05|TRIP)\b/i,
    patternType: 'source',
    remediation: 'Migrate to SAP Concur for travel and expense management.',
    simplificationId: 'S4TWL-REM-008',
  },
  {
    id: 'SIMPL-REM-009',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Web Dynpro ABAP applications',
    description: 'Web Dynpro ABAP-based applications replaced by Fiori/UI5.',
    pattern: /\bWDR_|IF_WD_|CL_WD_\w+/i,
    patternType: 'source',
    remediation: 'Migrate Web Dynpro applications to Fiori/SAPUI5.',
    simplificationId: 'S4TWL-REM-009',
  },
  {
    id: 'SIMPL-REM-010',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'BSP applications deprecated',
    description: 'Business Server Pages (BSP) technology replaced by Fiori/UI5.',
    pattern: /\bCL_BSP_|BSP_|IF_BSP_\w+/i,
    patternType: 'source',
    remediation: 'Migrate BSP applications to Fiori/SAPUI5.',
    simplificationId: 'S4TWL-REM-010',
  },
  {
    id: 'SIMPL-REM-011',
    category: 'Removed Functionality',
    severity: 'medium',
    title: 'Classic BW extractors deprecated',
    description: 'Classic BW extractors replaced by CDS-based extraction.',
    pattern: /\b(RSA[0-9]|ROOSOURCE|MC_)\w+/i,
    patternType: 'source',
    remediation: 'Migrate BW extractors to CDS-based extraction (analytical annotations).',
    simplificationId: 'S4TWL-REM-011',
  },
  {
    id: 'SIMPL-REM-012',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'ITS (Internet Transaction Server) removed',
    description: 'Classic ITS-based web transactions removed.',
    pattern: /\bITS_|SAPMSSY0|~WEBGUI\b/i,
    patternType: 'source',
    remediation: 'Migrate ITS applications to Fiori or API-based solutions.',
    simplificationId: 'S4TWL-REM-012',
  },
  // ── Rules 013–045: expanded coverage ──
  {
    id: 'SIMPL-REM-013',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'FI customer transactions removed (FD01/FD02/FD03)',
    description: 'FI customer master transactions FD01 (create), FD02 (change), FD03 (display) are removed. Business Partner transaction BP is the replacement.',
    pattern: /\b(FD01|FD02|FD03|FD04|FD05|FD06|FD08|FD09)\b/i,
    patternType: 'source',
    remediation: 'Use BP transaction or Fiori app "Manage Business Partner" (F0850). Use API_BUSINESS_PARTNER for programmatic access.',
    simplificationId: 'S4TWL-REM-013',
  },
  {
    id: 'SIMPL-REM-014',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'FI vendor transactions removed (FK01/FK02/FK03)',
    description: 'FI vendor master transactions FK01 (create), FK02 (change), FK03 (display) are removed. Business Partner transaction BP is the replacement.',
    pattern: /\b(FK01|FK02|FK03|FK04|FK05|FK06|FK08|FK09)\b/i,
    patternType: 'source',
    remediation: 'Use BP transaction or Fiori app "Manage Business Partner" (F0850). Use API_BUSINESS_PARTNER for programmatic access.',
    simplificationId: 'S4TWL-REM-014',
  },
  {
    id: 'SIMPL-REM-015',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'SD customer transactions removed (VD01/VD02/VD03)',
    description: 'SD customer master transactions VD01 (create), VD02 (change), VD03 (display) and XD01/XD02/XD03 are removed.',
    pattern: /\b(VD01|VD02|VD03|VD04|VD05|VD06|XD01|XD02|XD03|XD04|XD05|XD06|XD07)\b/i,
    patternType: 'source',
    remediation: 'Use BP transaction. Customer data is maintained through BP roles. Use Fiori app "Manage Business Partner".',
    simplificationId: 'S4TWL-REM-015',
  },
  {
    id: 'SIMPL-REM-016',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'MM vendor transactions removed (MK01/MK02/MK03)',
    description: 'MM vendor master transactions MK01 (create), MK02 (change), MK03 (display) and XK01/XK02/XK03 are removed.',
    pattern: /\b(MK01|MK02|MK03|MK04|MK05|MK06|XK01|XK02|XK03|XK04|XK05|XK06|XK07)\b/i,
    patternType: 'source',
    remediation: 'Use BP transaction. Vendor/supplier data is maintained through BP roles. Use Fiori app "Manage Business Partner".',
    simplificationId: 'S4TWL-REM-016',
  },
  {
    id: 'SIMPL-REM-017',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic credit management transactions removed',
    description: 'FD32 (credit management change), FD33 (display), S_ALR_87012218 (credit overview) removed. FSCM credit management replaces them.',
    pattern: /\b(FD32|FD33|FD31|S_ALR_87012218|F\.28|F\.31)\b/i,
    patternType: 'source',
    remediation: 'Use UKM_MP (Manage Credit Segments) and FSCM credit management Fiori apps. Use transaction UDM_BP for credit master.',
    simplificationId: 'S4TWL-REM-017',
  },
  {
    id: 'SIMPL-REM-018',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic WM transactions removed',
    description: 'Warehouse management transactions (LT01-LT0A, LS01-LS26, LI01-LI21, LB01-LB10) are all removed. EWM transactions replace them.',
    pattern: /\b(LT0[1-9A]|LS[0-2][0-9]|LI[0-2][0-9]|LB[0-1][0-9]|LX[0-3][0-9])\b/i,
    patternType: 'source',
    remediation: 'Migrate to Embedded EWM transactions (/SCWM/*) or EWM Fiori apps.',
    simplificationId: 'S4TWL-REM-018',
  },
  {
    id: 'SIMPL-REM-019',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic asset accounting transactions changed',
    description: 'Asset accounting transactions (AS01/AS02/AS03) are available but underlying data model changed to ACDOCA. OAOA, AO90 customizing changed.',
    pattern: /\b(OAOA|AO90|OAYR|OAYO|ABLDT)\b/i,
    patternType: 'source',
    remediation: 'Review asset accounting customizing. Depreciation areas are now posted in real-time to ACDOCA. Use Fiori apps for asset management.',
    simplificationId: 'S4TWL-REM-019',
  },
  {
    id: 'SIMPL-REM-020',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'CO-PA customizing transactions changed',
    description: 'CO-PA customizing transactions (KE4I, KE1A, KE21, KEPM) are replaced or significantly changed. Account-based CO-PA is default.',
    pattern: /\b(KE4I|KE1A|KE21|KE21N|KE23|KE24|KE27|KE28|KEPM)\b/i,
    patternType: 'source',
    remediation: 'Use account-based CO-PA (default in S/4HANA). Costing-based CO-PA is optional. Review all CO-PA reports and planning layouts.',
    simplificationId: 'S4TWL-REM-020',
  },
  {
    id: 'SIMPL-REM-021',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'Removed FI function modules',
    description: 'Key FI function modules are removed or deprecated: BAPI_ACC_GL_POSTING_POST, BAPI_ACC_DOCUMENT_POST parameter changes, FI_DOCUMENT_CHANGE restrictions.',
    pattern: /\b(BAPI_ACC_GL_POSTING_POST|BAPI_ACC_ACT_POSTING_POST|AC_DOCUMENT_RECORD|FI_DOCUMENT_CHANGE|POSTING_INTERFACE_START)\b/i,
    patternType: 'source',
    remediation: 'Use BAPI_ACC_DOCUMENT_POST (still available but with parameter changes) or new Fiori-based posting APIs.',
    simplificationId: 'S4TWL-REM-021',
  },
  {
    id: 'SIMPL-REM-022',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed SD function modules',
    description: 'Key SD function modules are deprecated: SD_SALESDOCUMENT_CREATE, SD_CUSTOMER_MAINTAIN_ALL, BAPI_SALESORDER_CREATEFROMDAT1.',
    pattern: /\b(SD_SALESDOCUMENT_CREATE|SD_CUSTOMER_MAINTAIN_ALL|BAPI_SALESORDER_CREATEFROMDAT1|SD_SALESDOCUMENT_CHANGE|RV_INVOICE_CREATE)\b/i,
    patternType: 'source',
    remediation: 'Use API_SALES_ORDER_SRV, API_BILLING_DOCUMENT_SRV, or BAPI_SALESORDER_CREATEFROMDAT2.',
    simplificationId: 'S4TWL-REM-022',
  },
  {
    id: 'SIMPL-REM-023',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed MM function modules',
    description: 'Key MM function modules are deprecated: BAPI_PO_CREATE, ME_DIRECT_INPUT_*, BAPI_GOODSMVT_CREATE parameter changes.',
    pattern: /\b(BAPI_PO_CREATE[^1]|ME_DIRECT_INPUT_\w+|BAPI_REQUISITION_CREATE|MB_CREATE_GOODS_MOVEMENT)\b/i,
    patternType: 'source',
    remediation: 'Use BAPI_PO_CREATE1, API_PURCHASEORDER_PROCESS_SRV, BAPI_GOODSMVT_CREATE (with updated parameters).',
    simplificationId: 'S4TWL-REM-023',
  },
  {
    id: 'SIMPL-REM-024',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Report Painter/Writer reports on removed tables',
    description: 'Report Painter reports (GR55, GRR1-GRR3) that use libraries based on removed tables (BSEG, GLT0, COEP, COSS, COSP) will not function correctly.',
    pattern: /\b(GR55|GRR[1-3]|GR3[1-3]|GR5[5-8]|REPORT_PAINTER|REPORT_WRITER)\b/i,
    patternType: 'source',
    remediation: 'Rebuild Report Painter reports using ACDOCA-based libraries or migrate to CDS analytical queries and Fiori analytical apps.',
    simplificationId: 'S4TWL-REM-024',
  },
  {
    id: 'SIMPL-REM-025',
    category: 'Removed Functionality',
    severity: 'medium',
    title: 'Report Painter library 1VK (cost centers) changed',
    description: 'Report Painter library 1VK (cost center actual/plan) is based on COSS/COSP which are compatibility views. Reports may have performance issues.',
    pattern: /\b(1VK|6O1|8A2)\b/i,
    patternType: 'source',
    remediation: 'Migrate Report Painter cost center reports to CDS analytical views or Fiori app "Cost Centers - Plan/Actual" (F0842A).',
    simplificationId: 'S4TWL-REM-025',
  },
  {
    id: 'SIMPL-REM-026',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'Removed classic GL programs',
    description: 'Classic GL programs (RFBILA00, RFSALDO, RFSKPL00, RFUMSV00) are removed or replaced. New programs use ACDOCA.',
    pattern: /\b(RFBILA00|RFSALDO|RFSKPL00|RFUMSV00|RFSEPA01|RFDOPR10)\b/i,
    patternType: 'source',
    remediation: 'Use new financial reports based on ACDOCA. Use Fiori analytical apps for trial balance, balance sheet, P&L.',
    simplificationId: 'S4TWL-REM-026',
  },
  {
    id: 'SIMPL-REM-027',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed classic AP/AR programs',
    description: 'Classic AP/AR reporting programs (RFDOPR10, RFHABU00, RFDEBI01, RFKREDI01, RFDABL00) are removed or replaced.',
    pattern: /\b(RFDOPR10|RFHABU00|RFDEBI01|RFKREDI01|RFDABL00|RFKORD10|RFDUZI00)\b/i,
    patternType: 'source',
    remediation: 'Use new S/4HANA AP/AR programs and Fiori apps. Use CDS views I_JournalEntryItem for custom reports.',
    simplificationId: 'S4TWL-REM-027',
  },
  {
    id: 'SIMPL-REM-028',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed CO reporting transactions',
    description: 'Classic CO reporting transactions (S_ALR_87013611, S_ALR_87013620, KSB1, KOB1) may use compatibility views with poor performance.',
    pattern: /\b(S_ALR_8701361[0-9]|S_ALR_8701362[0-9]|KSB1|KOB1|KOB2|KOB3)\b/i,
    patternType: 'source',
    remediation: 'Use Fiori apps for CO reporting. Use CDS views I_CostCenterActualData, I_InternalOrderActualData.',
    simplificationId: 'S4TWL-REM-028',
  },
  {
    id: 'SIMPL-REM-029',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed/replaced customer BAPIs',
    description: 'BAPI_CUSTOMER_CREATEFROMDATA, BAPI_CUSTOMER_CHANGEFROMDATA, BAPI_CUSTOMER_GETDETAIL are deprecated.',
    pattern: /\b(BAPI_CUSTOMER_CREATEFROMDATA[12]?|BAPI_CUSTOMER_CHANGEFROMDATA[12]?|BAPI_CUSTOMER_GETDETAIL[12]?|BAPI_CUSTOMER_GETLIST)\b/i,
    patternType: 'source',
    remediation: 'Use API_BUSINESS_PARTNER OData service. For batch processing use BP IDoc (BUMAS) or staging tables.',
    simplificationId: 'S4TWL-REM-029',
  },
  {
    id: 'SIMPL-REM-030',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed/replaced vendor BAPIs',
    description: 'BAPI_VENDOR_CREATE, BAPI_VENDOR_CHANGE, BAPI_VENDOR_GETDETAIL are deprecated.',
    pattern: /\b(BAPI_VENDOR_CREATE|BAPI_VENDOR_CHANGE|BAPI_VENDOR_GETDETAIL|BAPI_VENDOR_GETLIST|BAPI_VENDOR_EXISTENCECHECK)\b/i,
    patternType: 'source',
    remediation: 'Use API_BUSINESS_PARTNER OData service. For batch processing use BP IDoc (BUMAS) or staging tables.',
    simplificationId: 'S4TWL-REM-030',
  },
  {
    id: 'SIMPL-REM-031',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed/replaced GL accounting BAPIs',
    description: 'BAPI_ACC_GL_POSTING_POST, BAPI_GL_GETGLACCBALANCE, BAPI_GL_GETGLACCCURRENTBALANCE are deprecated or have changed parameters.',
    pattern: /\b(BAPI_ACC_GL_POSTING_POST|BAPI_GL_GETGLACCBALANCE|BAPI_GL_GETGLACCCURRENTBALANCE|BAPI_GL_GETGLACCPERIODBALANCE)\b/i,
    patternType: 'source',
    remediation: 'Use BAPI_ACC_DOCUMENT_POST for GL postings. Use CDS views I_GLAccountBalance for balance queries.',
    simplificationId: 'S4TWL-REM-031',
  },
  {
    id: 'SIMPL-REM-032',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Obsolete FI customizing transactions',
    description: 'FI customizing transactions for classic GL (OB52, FBKP, OBB8 classic variants) and special purpose ledger (GCAC) are obsolete or changed.',
    pattern: /\b(GCAC|GCBA|GCL2|GCL3|GCAA|GCAT)\b/i,
    patternType: 'source',
    remediation: 'Use new FI customizing for universal journal. Special purpose ledger is replaced by extension ledgers in ACDOCA.',
    simplificationId: 'S4TWL-REM-032',
  },
  {
    id: 'SIMPL-REM-033',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'SmartForms deprecated in favor of Adobe Forms',
    description: 'SmartForms (SMARTFORMS transaction) are deprecated. Adobe Forms or SAP Forms by Adobe is the replacement.',
    pattern: /\b(SMARTFORMS|SSF_FUNCTION_MODULE_NAME|SSF_OPEN|SSF_CLOSE)\b/i,
    patternType: 'source',
    remediation: 'Migrate SmartForms to Adobe Forms (SFP transaction). For cloud scenarios use SAP Forms Service by Adobe.',
    simplificationId: 'S4TWL-REM-033',
  },
  {
    id: 'SIMPL-REM-034',
    category: 'Removed Functionality',
    severity: 'medium',
    title: 'Classic batch management changes',
    description: 'Batch management (MSC1N/MSC2N/MSC3N) has structural changes. Batch where-used list affected by ACDOCA.',
    pattern: /\b(MSC1N|MSC2N|MSC3N|VCH1|VCH2|VCH3|BATCH_INPUT_)\w*/i,
    patternType: 'source',
    remediation: 'Review batch management customizing. Use API_BATCH_SRV for programmatic batch management.',
    simplificationId: 'S4TWL-REM-034',
  },
  {
    id: 'SIMPL-REM-035',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic profit center accounting removed',
    description: 'Classic profit center accounting (EC-PCA, tables GLPCA/GLPCC/GLPCP) is removed. Profit center accounting is integrated into ACDOCA.',
    pattern: /\b(GLPCA|GLPCC|GLPCP|KE5[A-Z]|1KE[A-Z]|3KE[A-Z])\b/i,
    patternType: 'source',
    remediation: 'Profit center data is in ACDOCA. Use CDS views I_ProfitCenterActualData. Migrate EC-PCA reports to ACDOCA-based reports.',
    simplificationId: 'S4TWL-REM-035',
  },
  {
    id: 'SIMPL-REM-036',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic special purpose ledger removed',
    description: 'Special purpose ledger (FI-SL, tables GLT0, GRPT) is removed. Extension ledgers in ACDOCA are the replacement.',
    pattern: /\b(FI_SL_|GRPT|GLFUNCT|GCL[0-9]|GCAC)\b/i,
    patternType: 'source',
    remediation: 'Use extension ledgers in ACDOCA (RLDNR field). Configure additional ledgers via FINSC_LEDGER.',
    simplificationId: 'S4TWL-REM-036',
  },
  {
    id: 'SIMPL-REM-037',
    category: 'Removed Functionality',
    severity: 'medium',
    title: 'Classic dunning program replaced',
    description: 'Classic dunning program RFMAHN00/F150 has structural changes. Some parameters and exit points changed.',
    pattern: /\b(RFMAHN00|F150|RFMAHN_F150)\b/i,
    patternType: 'source',
    remediation: 'Review dunning program configuration. Use Fiori app "Schedule Dunning Runs" and new dunning APIs.',
    simplificationId: 'S4TWL-REM-037',
  },
  {
    id: 'SIMPL-REM-038',
    category: 'Removed Functionality',
    severity: 'medium',
    title: 'Classic payment program changes',
    description: 'Classic payment program RFFOUS_T/F110 has structural changes. Payment medium format exits may be affected.',
    pattern: /\b(RFFOUS_T|RFFOD_T|RFFOEDI1|RFFOBR_U|F110)\b/i,
    patternType: 'source',
    remediation: 'Review payment program configuration. Consider migration to Payment Factory or Advanced Payment Management.',
    simplificationId: 'S4TWL-REM-038',
  },
  {
    id: 'SIMPL-REM-039',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed WM function modules',
    description: 'Classic WM function modules (L_TO_CREATE_SINGLE, L_TO_CREATE_MOVE_SU, L_TO_CONFIRM) are removed with WM.',
    pattern: /\b(L_TO_CREATE_SINGLE|L_TO_CREATE_MOVE_SU|L_TO_CONFIRM|L_TO_CREATE_DN|L_TO_CREATE_TR)\b/i,
    patternType: 'source',
    remediation: 'Migrate to EWM APIs (/SCWM/ function modules and services). Use API_WAREHOUSE_TASK for warehouse operations.',
    simplificationId: 'S4TWL-REM-039',
  },
  {
    id: 'SIMPL-REM-040',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed inventory management transactions',
    description: 'Some inventory management transactions (MB01, MB02, MB03, MB11, MB1A, MB1B, MB1C) are replaced by new MIGO-based or Fiori transactions.',
    pattern: /\b(MB01|MB02|MB03|MB11|MB1A|MB1B|MB1C|MB31|MB51|MB52)\b/i,
    patternType: 'source',
    remediation: 'Use MIGO for goods movements. Use Fiori apps "Post Goods Receipt" (F0842), "Post Goods Issue" (F1654). Some MB* tcodes redirect to MIGO.',
    simplificationId: 'S4TWL-REM-040',
  },
  {
    id: 'SIMPL-REM-041',
    category: 'Removed Functionality',
    severity: 'medium',
    title: 'Classic costing run transactions changed',
    description: 'Classic costing transactions (CK40N, CK11N, CK24) have changes related to mandatory Material Ledger.',
    pattern: /\b(CK40N|CK11N|CK24|CK44|CKMLRUNPERIOD)\b/i,
    patternType: 'source',
    remediation: 'Material Ledger is mandatory. Review actual costing configuration. Use Fiori apps for material price analysis.',
    simplificationId: 'S4TWL-REM-041',
  },
  {
    id: 'SIMPL-REM-042',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed/replaced scheduling agreement BAPIs',
    description: 'BAPI_SAG_CREATE, BAPI_SAG_CHANGE are deprecated. Scheduling agreements use new APIs in S/4HANA.',
    pattern: /\b(BAPI_SAG_CREATE|BAPI_SAG_CHANGE|BAPI_SAG_GETDETAIL|BAPI_CONTRACT_CREATE|BAPI_CONTRACT_CHANGE)\b/i,
    patternType: 'source',
    remediation: 'Use API_SALES_SCHEDULING_AGREEMENT or API_SALES_CONTRACT_SRV for scheduling agreements and contracts.',
    simplificationId: 'S4TWL-REM-042',
  },
  {
    id: 'SIMPL-REM-043',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic material master BAPIs deprecated',
    description: 'BAPI_MATERIAL_SAVEDATA, BAPI_MATERIAL_GET_ALL have parameter changes and deprecation warnings.',
    pattern: /\b(BAPI_MATERIAL_SAVEDATA|BAPI_MATERIAL_GET_ALL|BAPI_MATERIAL_GETLIST|BAPI_MATERIAL_GETDETAIL)\b/i,
    patternType: 'source',
    remediation: 'Use API_PRODUCT_SRV OData service or CDS views I_Product, I_ProductPlant for material master access.',
    simplificationId: 'S4TWL-REM-043',
  },
  {
    id: 'SIMPL-REM-044',
    category: 'Removed Functionality',
    severity: 'medium',
    title: 'Removed HR/HCM integration points',
    description: 'HR master data transactions (PA20, PA30) remain but integration with SuccessFactors is the strategic direction. Some PA infotype function modules deprecated.',
    pattern: /\b(HR_INFOTYPE_OPERATION|HR_READ_INFOTYPE|RP_READ_INFOTYPE|BAPI_EMPLOYEE_)\w*/i,
    patternType: 'source',
    remediation: 'Review HR integration points. For cloud scenarios migrate to SuccessFactors APIs. On-premise HR FMs still available but review parameter changes.',
    simplificationId: 'S4TWL-REM-044',
  },
  {
    id: 'SIMPL-REM-045',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Removed ALV report variants using deprecated tables',
    description: 'Standard ALV reports (FBL1N, FBL3N, FBL5N) have been replaced with new versions that use ACDOCA. Custom variants and layouts may need adjustment.',
    pattern: /\b(FBL1N|FBL3N|FBL5N|FAGLL03|FAGLL03H)\b/i,
    patternType: 'source',
    remediation: 'Use new FI line item browsers based on ACDOCA. Use Fiori apps "Display Line Items in General Ledger" and equivalents.',
    simplificationId: 'S4TWL-REM-045',
  },
];
