/**
 * Removed/Replaced Functionality Rules
 *
 * Covers: WM → EWM, classic credit → FSCM, NAST → BRF+,
 * SAPscript → Adobe Forms, classic MRP → MRP Live, classic ATP → aATP.
 */

module.exports = [
  {
    id: 'SIMPL-REM-001',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'Warehouse Management (WM) replaced by EWM',
    description: 'Classic WM (LE-WM, LAGP/LQUA tables) is removed. EWM is the replacement.',
    pattern: /\b(LAGP|LQUA|LTAP|LTBP|L_TO_CREATE)\b/i,
    patternType: 'source',
    remediation: 'Migrate to Embedded EWM or Decentralized EWM.',
    simplificationId: 'S4TWL-REM-001',
  },
  {
    id: 'SIMPL-REM-002',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'Classic credit management removed',
    description: 'FD32 and UKM tables replaced by FSCM credit management.',
    pattern: /\b(UKM_|FD32|UKMBP_CMS)\b/i,
    patternType: 'source',
    remediation: 'Migrate to SAP Credit Management (FSCM).',
    simplificationId: 'S4TWL-REM-002',
  },
  {
    id: 'SIMPL-REM-003',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'NAST output management replaced by BRF+',
    description: 'Classic output determination via NAST/condition technique replaced by BRF+.',
    pattern: /\b(NAST|TNAPR|NACH)\b/i,
    patternType: 'source',
    remediation: 'Migrate to BRF+ based output management.',
    simplificationId: 'S4TWL-REM-003',
  },
  {
    id: 'SIMPL-REM-004',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'SAPscript forms deprecated',
    description: 'SAPscript forms (OPEN_FORM/CLOSE_FORM) replaced by Adobe Forms.',
    pattern: /\b(OPEN_FORM|CLOSE_FORM|WRITE_FORM)\b/i,
    patternType: 'source',
    remediation: 'Migrate to Adobe Forms or SAP Forms Service.',
    simplificationId: 'S4TWL-REM-004',
  },
  {
    id: 'SIMPL-REM-005',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic MRP replaced by MRP Live',
    description: 'MD01/MD02 classic MRP run replaced by MRP Live for performance.',
    pattern: /\b(MD01|MD02)\b(?!N)/i,
    patternType: 'source',
    remediation: 'Migrate to MRP Live (MD01N). Review custom MRP exits.',
    simplificationId: 'S4TWL-REM-005',
  },
  {
    id: 'SIMPL-REM-006',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Classic ATP replaced by aATP',
    description: 'Classic ATP (availability check) replaced by advanced ATP.',
    pattern: /\bBADI_ATP_|BAPI_MATERIAL_AVAILABILITY\b/i,
    patternType: 'source',
    remediation: 'Evaluate advanced ATP (aATP) for availability checks.',
    simplificationId: 'S4TWL-REM-006',
  },
  {
    id: 'SIMPL-REM-007',
    category: 'Removed Functionality',
    severity: 'critical',
    title: 'Classic GL removed (FAGL)',
    description: 'Classic General Ledger completely replaced by S/4HANA New GL.',
    pattern: /\bFAGL_[A-Z]{2,}/i,
    patternType: 'source',
    remediation: 'All GL operations now go through ACDOCA. Review all GL access patterns.',
    simplificationId: 'S4TWL-REM-007',
  },
  {
    id: 'SIMPL-REM-008',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Travel Management replaced by Concur',
    description: 'SAP Travel Management (FI-TV) replaced by SAP Concur.',
    pattern: /\b(PTRV_|PR05|TRIP)\b/i,
    patternType: 'source',
    remediation: 'Migrate to SAP Concur for travel and expense management.',
    simplificationId: 'S4TWL-REM-008',
  },
  {
    id: 'SIMPL-REM-009',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'Web Dynpro ABAP applications',
    description: 'Web Dynpro ABAP-based applications replaced by Fiori/UI5.',
    pattern: /\bWDR_|IF_WD_|CL_WD_\w+/i,
    patternType: 'source',
    remediation: 'Migrate Web Dynpro applications to Fiori/SAPUI5.',
    simplificationId: 'S4TWL-REM-009',
  },
  {
    id: 'SIMPL-REM-010',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'BSP applications deprecated',
    description: 'Business Server Pages (BSP) technology replaced by Fiori/UI5.',
    pattern: /\bCL_BSP_|BSP_|IF_BSP_\w+/i,
    patternType: 'source',
    remediation: 'Migrate BSP applications to Fiori/SAPUI5.',
    simplificationId: 'S4TWL-REM-010',
  },
  {
    id: 'SIMPL-REM-011',
    category: 'Removed Functionality',
    severity: 'medium',
    title: 'Classic BW extractors deprecated',
    description: 'Classic BW extractors replaced by CDS-based extraction.',
    pattern: /\b(RSA[0-9]|ROOSOURCE|MC_)\w+/i,
    patternType: 'source',
    remediation: 'Migrate BW extractors to CDS-based extraction (analytical annotations).',
    simplificationId: 'S4TWL-REM-011',
  },
  {
    id: 'SIMPL-REM-012',
    category: 'Removed Functionality',
    severity: 'high',
    title: 'ITS (Internet Transaction Server) removed',
    description: 'Classic ITS-based web transactions removed.',
    pattern: /\bITS_|SAPMSSY0|~WEBGUI\b/i,
    patternType: 'source',
    remediation: 'Migrate ITS applications to Fiori or API-based solutions.',
    simplificationId: 'S4TWL-REM-012',
  },
];
