/**
 * Transportation Management (TM) Rules
 *
 * Covers transition from legacy LE-TRA transportation to
 * embedded TM in S/4HANA. Key: shipment documents replaced,
 * freight order/booking model, carrier selection changes.
 * Extended: freight order mgmt, carrier tendering, freight units,
 * tracking, subcontracting, intermodal, cost settlement, EWM/SD/MM integration.
 */

module.exports = [
  // ── Shipment Processing ──────────────────────────────────────
  {
    id: 'SIMPL-TM-001',
    title: 'Legacy Shipment Processing (VT01-VT03)',
    description: 'Legacy shipment transactions VT01N/VT02N/VT03N replaced by TM freight order processing.',
    severity: 'critical',
    category: 'TM – Shipment Processing',
    sNote: '2462480',
    pattern: /\b(VT0[1-3]N?|VTTK|VTTP|VTTS)\b/i,
    patternType: 'source',
    remediation: 'Replace VT01-VT03 with TM freight order management (/SCMTMS/FO_CREATE).',
  },
  {
    id: 'SIMPL-TM-002',
    title: 'Shipment Cost Settlement Changed',
    description: 'Shipment cost documents (VI01-VI03) replaced by TM freight settlement.',
    severity: 'high',
    category: 'TM – Shipment Processing',
    sNote: '2462480',
    pattern: /\b(VI0[1-3]|VFSI|SHIPMENT_COST)\b/i,
    patternType: 'source',
    remediation: 'Migrate shipment cost settlement to TM freight settlement. Configure charge calculation schemas.',
  },
  {
    id: 'SIMPL-TM-003',
    title: 'Transportation Planning Point Replaced',
    description: 'Transportation planning points replaced by TM organizational units (business partner, org unit).',
    severity: 'high',
    category: 'TM – Shipment Processing',
    sNote: '2462480',
    pattern: /\b(VSTEL|TRANS_PLAN_POINT|T000V)\b/i,
    patternType: 'source',
    remediation: 'Map transportation planning points to TM organizational model.',
  },

  // ── Route & Carrier ──────────────────────────────────────────
  {
    id: 'SIMPL-TM-004',
    title: 'Route Determination Changed',
    description: 'Legacy route determination (OVTC) replaced by TM transportation lane model.',
    severity: 'high',
    category: 'TM – Route & Carrier',
    sNote: '2462480',
    pattern: /\b(OVTC|TVRO|ROUTE_DET|T_ROUTE)\b/i,
    patternType: 'source',
    remediation: 'Configure transportation lanes in TM to replace legacy route determination.',
  },
  {
    id: 'SIMPL-TM-005',
    title: 'Carrier Selection Replaced',
    description: 'Carrier selection moves from LE-TRA carrier master to TM carrier profiles with capacity and rate management.',
    severity: 'medium',
    category: 'TM – Route & Carrier',
    sNote: '2462480',
    pattern: /\b(CARRIER_SELECTION|TDLNR|FORWARDING_AGENT)\b/i,
    patternType: 'source',
    remediation: 'Set up TM carrier profiles and integrate with SAP Business Network for freight collaboration.',
  },

  // ── Integration ──────────────────────────────────────────────
  {
    id: 'SIMPL-TM-006',
    title: 'Delivery-to-Shipment Integration',
    description: 'Delivery-to-shipment assignment model replaced by TM freight unit builder.',
    severity: 'high',
    category: 'TM – Integration',
    sNote: '2462480',
    pattern: /\b(VLSP|DELIVERY_SHIPMENT|VL32N)\b/i,
    patternType: 'source',
    remediation: 'Configure freight unit builder in TM for automatic delivery-to-freight unit assignment.',
  },
  {
    id: 'SIMPL-TM-007',
    title: 'Dangerous Goods Processing Changed',
    description: 'Dangerous goods processing in transportation changes to TM-based DG checks.',
    severity: 'medium',
    category: 'TM – Integration',
    sNote: '2462480',
    pattern: /\b(DG_CHECK|DANGEROUS_GOODS|VGK[1-3])\b/i,
    patternType: 'source',
    remediation: 'Configure dangerous goods processing in TM. Review DG master data migration.',
  },
  {
    id: 'SIMPL-TM-008',
    title: 'Freight Cost Calculation Schema',
    description: 'TM introduces charge calculation schemas replacing legacy shipment cost conditions.',
    severity: 'medium',
    category: 'TM – Integration',
    sNote: '2462480',
    pattern: /\b(FREIGHT_COST|KOFL|SHIPMENT_CONDITION)\b/i,
    patternType: 'source',
    remediation: 'Migrate freight cost conditions to TM charge calculation schemas.',
  },

  // ── Freight Order Management ─────────────────────────────────
  {
    id: 'SIMPL-TM-009',
    title: 'Freight Order Planning and Optimization',
    description: 'TM freight order planning uses optimizer-based algorithms for shipment consolidation, load building, and route optimization. Replaces manual shipment planning in VT01N/VT04.',
    severity: 'high',
    category: 'TM – Freight Order',
    sNote: '2462480',
    pattern: /\b(FO_PLANNING|FO_OPTIM|LOAD_BUILD|VT04)\b|\/SCMTMS\/FO_PLAN/i,
    patternType: 'source',
    remediation: 'Configure TM freight order planning profiles. Set up optimization strategies for consolidation and routing.',
  },
  {
    id: 'SIMPL-TM-010',
    title: 'Freight Order Execution Monitoring',
    description: 'TM freight order execution replaces legacy shipment status management. Provides stage-based execution with event-driven status changes, check-in/check-out, and proof of delivery integration.',
    severity: 'high',
    category: 'TM – Freight Order',
    sNote: '2462480',
    pattern: /\b(FO_EXECUTION|FO_STATUS|SHIPMENT_STATUS|FO_STAGE)\b|\/SCMTMS\/FO_EXEC/i,
    patternType: 'source',
    remediation: 'Configure TM freight order execution profiles. Define execution stages and event-based status management.',
  },
  {
    id: 'SIMPL-TM-011',
    title: 'Freight Order Settlement and Invoicing',
    description: 'TM freight settlement provides charge management, freight invoice verification, and automatic accrual posting. Replaces shipment cost documents (VI01-VI03) with structured settlement processes.',
    severity: 'high',
    category: 'TM – Freight Order',
    sNote: '2462480',
    pattern: /\b(FO_SETTLE|FREIGHT_SETTLE|FREIGHT_INVOICE|ACCRUAL_POST)\b|\/SCMTMS\/SETTLE/i,
    patternType: 'source',
    remediation: 'Configure TM settlement profiles and charge calculation schemas. Set up freight invoice verification workflow.',
  },

  // ── Carrier Management and Tendering ─────────────────────────
  {
    id: 'SIMPL-TM-012',
    title: 'Carrier Agreement and Rate Management',
    description: 'TM carrier agreements define contract rates, surcharges, accessorial charges, and validity periods. Replaces legacy freight condition records in shipment cost calculation.',
    severity: 'high',
    category: 'TM – Carrier Management',
    sNote: '2462480',
    pattern: /\b(CARRIER_AGREE|FREIGHT_RATE|RATE_TABLE|TARIFF_MGMT)\b|\/SCMTMS\/CA_/i,
    patternType: 'source',
    remediation: 'Maintain carrier agreements in TM. Define rate tables, surcharge schemas, and validity dates for carrier contracts.',
  },
  {
    id: 'SIMPL-TM-013',
    title: 'Freight Tendering and Bid Management',
    description: 'TM freight tendering enables carrier selection through spot bidding, contract tendering, and waterfall tendering. Integrates with SAP Business Network for carrier collaboration. No equivalent in LE-TRA.',
    severity: 'medium',
    category: 'TM – Carrier Management',
    sNote: '2462480',
    pattern: /\b(FREIGHT_TENDER|SPOT_BID|CARRIER_BID|WATERFALL_TENDER)\b|\/SCMTMS\/TEND/i,
    patternType: 'source',
    remediation: 'Configure TM tendering profiles. Set up carrier collaboration via SAP Business Network for freight.',
  },

  // ── Freight Unit Management ──────────────────────────────────
  {
    id: 'SIMPL-TM-014',
    title: 'Freight Unit Building Rules',
    description: 'TM freight units aggregate delivery items into transportation-relevant units based on building rules (compatibility groups, weight/volume limits, packaging). Replaces delivery-to-shipment grouping logic.',
    severity: 'high',
    category: 'TM – Freight Units',
    sNote: '2462480',
    pattern: /\b(FREIGHT_UNIT|FU_BUILD|FU_RULE|DELIVERY_GROUP)\b|\/SCMTMS\/FU_/i,
    patternType: 'source',
    remediation: 'Configure freight unit building rules in TM. Define compatibility groups and capacity constraints for unit aggregation.',
  },
  {
    id: 'SIMPL-TM-015',
    title: 'Freight Unit Packaging and Loading',
    description: 'TM freight units support multi-level packaging hierarchies and loading instructions. Package building integrates with EWM ship-HU creation for automated packing proposals.',
    severity: 'medium',
    category: 'TM – Freight Units',
    sNote: '2462480',
    pattern: /\b(FU_PACKAGE|FU_LOADING|LOAD_INSTRUCT|PACKAGE_BUILD)\b/i,
    patternType: 'source',
    remediation: 'Configure freight unit packaging profiles. Integrate with EWM for ship-HU and loading optimization.',
  },

  // ── Tracking and Tracing ─────────────────────────────────────
  {
    id: 'SIMPL-TM-016',
    title: 'Shipment Tracking and Visibility',
    description: 'TM provides event-based shipment tracking with GPS integration, milestone monitoring, and exception alerting. Replaces custom tracking solutions built on legacy shipment status fields.',
    severity: 'medium',
    category: 'TM – Tracking',
    sNote: '2462480',
    pattern: /\b(TRACK_TRACE|SHIPMENT_TRACK|GPS_TRACK|MILESTONE_MON)\b|\/SCMTMS\/TRACK/i,
    patternType: 'source',
    remediation: 'Configure TM event management for shipment tracking. Integrate with SAP Business Network for Global Track and Trace.',
  },
  {
    id: 'SIMPL-TM-017',
    title: 'ETA Calculation and Exception Management',
    description: 'TM calculates estimated time of arrival (ETA) based on transportation lane schedules, carrier performance, and real-time events. Exceptions trigger alerts for delayed or disrupted shipments.',
    severity: 'medium',
    category: 'TM – Tracking',
    sNote: '2462480',
    pattern: /\b(ETA_CALC|DELAY_ALERT|EXCEPT_MGMT|DISRUPT_MON)\b/i,
    patternType: 'source',
    remediation: 'Configure ETA calculation rules and exception thresholds. Set up alert profiles for shipment monitoring.',
  },

  // ── Subcontracting and Intermodal ────────────────────────────
  {
    id: 'SIMPL-TM-018',
    title: 'Transportation Subcontracting',
    description: 'TM supports subcontracting scenarios where a freight order leg is assigned to a subcontractor carrier. Enables multi-leg planning with carrier-to-carrier handoffs and consolidated settlement.',
    severity: 'medium',
    category: 'TM – Subcontracting',
    sNote: '2462480',
    pattern: /\b(TM_SUBCONTRACT|CARRIER_SUBCON|MULTI_LEG|HANDOFF)\b/i,
    patternType: 'source',
    remediation: 'Configure subcontracting profiles in TM. Define multi-leg planning rules and inter-carrier settlement.',
  },
  {
    id: 'SIMPL-TM-019',
    title: 'Intermodal Transport Planning',
    description: 'TM intermodal planning supports multimodal transportation (road, rail, ocean, air) with mode-specific constraints, transit times, and intermodal transfer points. Replaces custom multi-leg shipment processing.',
    severity: 'medium',
    category: 'TM – Intermodal',
    sNote: '2462480',
    pattern: /\b(INTERMODAL|MULTIMODAL|MODE_CHANGE|RAIL_OCEAN|AIR_FREIGHT)\b/i,
    patternType: 'source',
    remediation: 'Configure intermodal planning rules. Define transportation modes, transfer points, and mode-specific constraints.',
  },

  // ── Freight Cost Calculation and Settlement ──────────────────
  {
    id: 'SIMPL-TM-020',
    title: 'Charge Calculation Schema Configuration',
    description: 'TM charge calculation schemas define how freight costs are computed using rate tables, weight breaks, distance tables, and surcharge formulas. Replaces legacy pricing condition technique for shipment costs.',
    severity: 'high',
    category: 'TM – Cost Calculation',
    sNote: '2462480',
    pattern: /\b(CHARGE_CALC|RATE_SCHEMA|WEIGHT_BREAK|DIST_TABLE)\b|\/SCMTMS\/CALC/i,
    patternType: 'source',
    remediation: 'Configure charge calculation schemas in TM. Map legacy freight pricing conditions to TM rate structures.',
  },
  {
    id: 'SIMPL-TM-021',
    title: 'Freight Cost Distribution to Sales Orders',
    description: 'TM distributes calculated freight costs back to source documents (sales orders, purchase orders, deliveries) for profitability analysis and customer freight billing.',
    severity: 'medium',
    category: 'TM – Cost Calculation',
    sNote: '2462480',
    pattern: /\b(COST_DISTRIB|FREIGHT_ALLOC|FREIGHT_BILL|COST_APPORTION)\b/i,
    patternType: 'source',
    remediation: 'Configure cost distribution rules in TM. Define allocation methods for freight cost posting to source documents.',
  },

  // ── Integration with EWM, SD, MM ────────────────────────────
  {
    id: 'SIMPL-TM-022',
    title: 'TM-EWM Integration for Loading and Shipping',
    description: 'TM integrates with embedded EWM for dock appointment scheduling, loading execution, and ship-HU confirmation. Replaces manual shipment-to-delivery linkage in LE-TRA/LE-WM.',
    severity: 'high',
    category: 'TM – EWM Integration',
    sNote: '2462480',
    pattern: /\b(TM_EWM_INT|DOCK_APPT|LOAD_EXEC|SHIP_CONFIRM)\b/i,
    patternType: 'source',
    remediation: 'Configure TM-EWM integration. Set up dock scheduling, loading step determination, and shipping confirmation flow.',
  },
  {
    id: 'SIMPL-TM-023',
    title: 'TM-SD Integration for Order Fulfillment',
    description: 'TM integrates with SD for transportation-relevant sales order processing, delivery scheduling with transit time calculation, and freight cost pass-through to billing documents.',
    severity: 'high',
    category: 'TM – SD Integration',
    sNote: '2462480',
    pattern: /\b(TM_SD_INT|TRANSIT_TIME|SD_FREIGHT|ORDER_FULFILL)\b/i,
    patternType: 'source',
    remediation: 'Configure TM-SD integration for transit time determination and freight cost transfer to billing.',
  },
  {
    id: 'SIMPL-TM-024',
    title: 'TM-MM Integration for Inbound Logistics',
    description: 'TM integrates with MM for inbound freight management including purchase order-driven freight orders, inbound delivery scheduling, and supplier freight cost settlement.',
    severity: 'medium',
    category: 'TM – MM Integration',
    sNote: '2462480',
    pattern: /\b(TM_MM_INT|INBOUND_FREIGHT|PO_FREIGHT|SUPPLIER_FREIGHT)\b/i,
    patternType: 'source',
    remediation: 'Configure TM-MM integration for inbound logistics. Define purchase order freight relevance and supplier freight settlement.',
  },
];
