#!/usr/bin/env node

/**
 * S/4HANA Cutover Planning CLI
 *
 * Usage:
 *   npm run cutover                              # Mock mode
 *   npm run cutover -- --format md               # Markdown output
 *   npm run cutover -- --go-live 2025-06-01      # Set go-live date
 */

const SapGateway = require('../agent/sap-gateway');
const CutoverPlan = require('./cutover-plan');

function parseArgs(argv) {
  const args = {
    format: 'terminal',
    clientName: 'SAP Client',
    goLiveDate: null,
  };

  for (let i = 2; i < argv.length; i++) {
    switch (argv[i]) {
      case '--format':
      case '-f':
        args.format = argv[++i];
        break;
      case '--client':
      case '-c':
        args.clientName = argv[++i];
        break;
      case '--go-live':
        args.goLiveDate = argv[++i];
        break;
      case '--sap-system':
      case '-s':
        args.sapSystem = argv[++i];
        break;
      case '--vsp-path':
      case '-P':
        args.vspPath = argv[++i];
        break;
      case '--vsp-system':
      case '-S':
        args.vspSystem = argv[++i];
        break;
      case '--verbose':
      case '-v':
        args.verbose = true;
        break;
      case '--help':
      case '-h':
        printHelp();
        process.exit(0);
        break;
      default:
        if (argv[i].startsWith('-')) {
          console.error(`Unknown flag: ${argv[i]}`);
          printHelp();
          process.exit(1);
        }
        break;
    }
  }

  return args;
}

function printHelp() {
  console.log(`
S/4HANA Cutover Planning
==========================

Generates a detailed cutover plan with sequenced tasks, dependencies,
milestones, and risk register for the S/4HANA go-live.

Runs in mock mode by default.

Usage:
  npm run cutover [options]

Options:
  -f, --format <fmt>       Output format: terminal (default) or md
  -c, --client <name>      Client name for the report header
  --go-live <date>         Target go-live date (YYYY-MM-DD)
  -s, --sap-system <url>   SAP system URL
  -P, --vsp-path <path>    Path to vsp binary
  -S, --vsp-system <name>  vsp system profile
  -v, --verbose            Show detailed logs
  -h, --help               Show this help

Examples:
  npm run cutover
  npm run cutover -- --format md --client "Acme Corp"
  npm run cutover -- --go-live 2025-06-01
  `);
}

function formatTerminal(plan, clientName) {
  const lines = [];
  const w = 70;

  lines.push('');
  lines.push('='.repeat(w));
  lines.push('  S/4HANA Cutover Plan');
  lines.push('='.repeat(w));
  lines.push(`  Client:        ${clientName}`);
  lines.push(`  Go-Live Date:  ${plan.stats.goLiveDate}`);
  lines.push(`  Date:          ${new Date().toISOString().split('T')[0]}`);
  lines.push('='.repeat(w));
  lines.push('');

  // Summary
  lines.push('-'.repeat(w));
  lines.push('  CUTOVER SUMMARY');
  lines.push('-'.repeat(w));
  lines.push('');
  lines.push(`  Total Phases:       ${plan.stats.totalPhases}`);
  lines.push(`  Total Tasks:        ${plan.stats.totalTasks}`);
  lines.push(`  Total Effort:       ${plan.stats.totalHours} hours (~${plan.stats.totalDays} days)`);
  lines.push(`  Cutover Window:     ${plan.stats.cutoverWindowHours} hours`);
  lines.push('');

  // Milestones
  lines.push('-'.repeat(w));
  lines.push('  MILESTONES');
  lines.push('-'.repeat(w));
  lines.push('');
  for (const m of plan.milestones) {
    lines.push(`  ${m.id.padEnd(4)} ${m.date}  ${m.name}`);
  }
  lines.push('');

  // Phases & Tasks
  for (const phase of plan.phases) {
    lines.push('-'.repeat(w));
    lines.push(`  ${phase.id}: ${phase.name}`);
    lines.push(`  Timing: ${phase.timing}`);
    lines.push('-'.repeat(w));
    lines.push('');
    for (const task of phase.tasks) {
      const deps = task.depends.length > 0 ? ` (after: ${task.depends.join(', ')})` : '';
      lines.push(`  ${task.id.padEnd(12)} ${task.name}`);
      lines.push(`               Owner: ${task.owner.padEnd(20)} Duration: ${task.durationHours}h${deps}`);
    }
    lines.push('');
  }

  // Risks
  lines.push('-'.repeat(w));
  lines.push('  RISK REGISTER');
  lines.push('-'.repeat(w));
  lines.push('');
  for (const r of plan.risks) {
    const tag = r.impact === 'Critical' ? '[!!]' : r.impact === 'High' ? '[! ]' : '[~ ]';
    lines.push(`  ${tag} ${r.id}: ${r.risk}`);
    lines.push(`      Prob: ${r.probability.padEnd(8)} Impact: ${r.impact.padEnd(10)} Owner: ${r.owner}`);
    lines.push(`      Mitigation: ${r.mitigation}`);
    lines.push('');
  }

  lines.push('='.repeat(w));
  lines.push('  Cutover plan generated by SEN Migration Tool');
  lines.push('='.repeat(w));

  return lines.join('\n');
}

function formatMarkdown(plan, clientName) {
  const lines = [];

  lines.push('# S/4HANA Cutover Plan');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('| --- | --- |');
  lines.push(`| Client | ${clientName} |`);
  lines.push(`| Go-Live Date | **${plan.stats.goLiveDate}** |`);
  lines.push(`| Date | ${new Date().toISOString().split('T')[0]} |`);
  lines.push(`| Total Phases | ${plan.stats.totalPhases} |`);
  lines.push(`| Total Tasks | ${plan.stats.totalTasks} |`);
  lines.push(`| Total Effort | ${plan.stats.totalHours} hours (~${plan.stats.totalDays} days) |`);
  lines.push(`| Cutover Window | ${plan.stats.cutoverWindowHours} hours |`);
  lines.push('');

  // Milestones
  lines.push('## Milestones');
  lines.push('');
  lines.push('| ID | Date | Milestone |');
  lines.push('| --- | --- | --- |');
  for (const m of plan.milestones) {
    lines.push(`| ${m.id} | ${m.date} | ${m.name} |`);
  }
  lines.push('');

  // Phases
  for (const phase of plan.phases) {
    lines.push(`## ${phase.id}: ${phase.name}`);
    lines.push('');
    lines.push(`**Timing:** ${phase.timing}`);
    lines.push('');
    lines.push('| Task | Description | Owner | Hours | Dependencies |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const task of phase.tasks) {
      const deps = task.depends.length > 0 ? task.depends.join(', ') : '-';
      lines.push(`| ${task.id} | ${task.name} | ${task.owner} | ${task.durationHours} | ${deps} |`);
    }
    lines.push('');
  }

  // Risks
  lines.push('## Risk Register');
  lines.push('');
  lines.push('| ID | Risk | Probability | Impact | Mitigation | Owner |');
  lines.push('| --- | --- | --- | --- | --- | --- |');
  for (const r of plan.risks) {
    lines.push(`| ${r.id} | ${r.risk} | ${r.probability} | ${r.impact} | ${r.mitigation} | ${r.owner} |`);
  }
  lines.push('');

  lines.push('---');
  lines.push('*Cutover plan generated by SEN Migration Tool*');

  return lines.join('\n');
}

async function main() {
  const args = parseArgs(process.argv);

  const gateway = new SapGateway({
    system: args.sapSystem,
    vspPath: args.vspPath,
    vspSystem: args.vspSystem,
    verbose: args.verbose,
  });

  console.log('');
  console.log(`  Mode: ${gateway.mode.toUpperCase()}`);
  console.log('  Generating cutover plan...');
  console.log('');

  try {
    const planner = new CutoverPlan({
      verbose: args.verbose,
      goLiveDate: args.goLiveDate,
      clientName: args.clientName,
    });
    const plan = planner.generate();

    console.log(`  Generated ${plan.stats.totalTasks} tasks across ${plan.stats.totalPhases} phases`);
    console.log(`  Go-Live: ${plan.stats.goLiveDate}`);
    console.log('');

    const isMarkdown = args.format === 'md' || args.format === 'markdown';
    if (isMarkdown) {
      console.log(formatMarkdown(plan, args.clientName));
    } else {
      console.log(formatTerminal(plan, args.clientName));
    }
  } catch (err) {
    console.error(`Cutover planning failed: ${err.message}`);
    if (args.verbose) {
      console.error(err.stack);
    }
    process.exit(1);
  }
}

main();
