/**
 * Copyright 2024-2026 SEN Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
const Logger = require('../lib/logger');

/**
 * BTP Service Provisioner
 *
 * Generates Terraform config for BTP subaccount/services.
 * Tracks provisioning status. Mock mode simulates provisioning.
 */
class Provisioner {
  constructor(gateway, options = {}) {
    this.gateway = gateway;
    this.verbose = options.verbose || false;
    this.landscape = options.landscape || 'cf-us10';
    this.tier = options.tier || 'standard';
    this.logger = new Logger('provisioner', { level: options.logLevel || 'info' });
  }

  _log(msg) {
    this.logger.info(msg);
  }

  /**
   * Provision BTP services for S/4HANA migration
   * @returns {object} { services[], terraform, stats }
   */
  async provision() {
    this._log('Starting BTP provisioning plan...');

    const services = this._defineServices();
    const terraform = this._generateTerraform(services);
    const provisioningPlan = this._simulateProvisioning(services);

    return {
      services: provisioningPlan,
      terraform,
      stats: {
        totalServices: services.length,
        provisioned: provisioningPlan.filter((s) => s.status === 'provisioned').length,
        pending: provisioningPlan.filter((s) => s.status === 'pending').length,
        errors: provisioningPlan.filter((s) => s.status === 'error').length,
        landscape: this.landscape,
        tier: this.tier,
        estimatedMonthlyCost: this._estimateCost(services),
      },
    };
  }

  _defineServices() {
    return [
      {
        name: 'S/4HANA Cloud',
        technicalName: 's4-hana-cloud',
        plan: this.tier,
        category: 'Core',
        required: true,
        description: 'S/4HANA Cloud tenant',
        estimatedCost: 15000,
      },
      {
        name: 'SAP Integration Suite',
        technicalName: 'integration-suite',
        plan: 'enterprise',
        category: 'Integration',
        required: true,
        description: 'API management and integration flows',
        estimatedCost: 3000,
      },
      {
        name: 'SAP Build Work Zone',
        technicalName: 'sap-build-workzone',
        plan: 'standard',
        category: 'UX',
        required: true,
        description: 'Fiori launchpad and workspace',
        estimatedCost: 1500,
      },
      {
        name: 'SAP Business Application Studio',
        technicalName: 'sapappstudio',
        plan: 'standard-edition',
        category: 'Development',
        required: true,
        description: 'IDE for extension development',
        estimatedCost: 500,
      },
      {
        name: 'Cloud Identity Services',
        technicalName: 'identity',
        plan: 'default',
        category: 'Security',
        required: true,
        description: 'Identity authentication and provisioning',
        estimatedCost: 0,
      },
      {
        name: 'SAP HANA Cloud',
        technicalName: 'hana-cloud',
        plan: 'hana',
        category: 'Data',
        required: false,
        description: 'Side-by-side extension database',
        estimatedCost: 2000,
      },
      {
        name: 'SAP Event Mesh',
        technicalName: 'enterprise-messaging',
        plan: 'default',
        category: 'Integration',
        required: false,
        description: 'Event-driven integration',
        estimatedCost: 800,
      },
      {
        name: 'SAP Document Management',
        technicalName: 'sdm',
        plan: 'standard',
        category: 'Content',
        required: false,
        description: 'Document management service',
        estimatedCost: 400,
      },
      {
        name: 'SAP Cloud ALM',
        technicalName: 'cloud-alm',
        plan: 'standard',
        category: 'Operations',
        required: true,
        description: 'Application lifecycle management',
        estimatedCost: 0,
      },
      {
        name: 'Connectivity Service',
        technicalName: 'connectivity',
        plan: 'lite',
        category: 'Integration',
        required: true,
        description: 'On-premise connectivity via Cloud Connector',
        estimatedCost: 0,
      },
    ];
  }

  _generateTerraform(services) {
    const lines = [];

    lines.push('# Auto-generated BTP Terraform configuration');
    lines.push('# Generated by SEN Migration Tool');
    lines.push(`# Landscape: ${this.landscape}`);
    lines.push(`# Date: ${new Date().toISOString().split('T')[0]}`);
    lines.push('');
    lines.push('terraform {');
    lines.push('  required_providers {');
    lines.push('    btp = {');
    lines.push('      source  = "SAP/btp"');
    lines.push('      version = "~> 1.0"');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');
    lines.push('provider "btp" {');
    lines.push('  globalaccount = var.globalaccount');
    lines.push('}');
    lines.push('');
    lines.push(`resource "btp_subaccount" "migration" {`);
    lines.push(`  name      = "s4hana-migration"`);
    lines.push(`  subdomain = "s4hana-migration"`);
    lines.push(`  region    = "${this.landscape}"`);
    lines.push('}');
    lines.push('');

    for (const svc of services) {
      const resourceName = svc.technicalName.replace(/-/g, '_');
      lines.push(`resource "btp_subaccount_entitlement" "${resourceName}" {`);
      lines.push('  subaccount_id = btp_subaccount.migration.id');
      lines.push(`  service_name  = "${svc.technicalName}"`);
      lines.push(`  plan_name     = "${svc.plan}"`);
      lines.push('}');
      lines.push('');
    }

    lines.push('# Variables');
    lines.push('variable "globalaccount" {');
    lines.push('  description = "BTP Global Account subdomain"');
    lines.push('  type        = string');
    lines.push('}');

    return lines.join('\n');
  }

  _simulateProvisioning(services) {
    return services.map((svc) => ({
      ...svc,
      status: 'provisioned',
      instanceId: `inst-${Math.random().toString(36).substring(2, 10)}`,
      provisionedAt: new Date().toISOString(),
    }));
  }

  _estimateCost(services) {
    return services.reduce((sum, s) => sum + s.estimatedCost, 0);
  }
}

module.exports = Provisioner;
